### ISSUE TITLE
Full Youtube Support

### ISSUE THREAD

**Issue by MSOB7YY** [namidaco/namida#1]
#### Originally, youtube was only used to fetch videos for music library, or for history import, now that most backend stuff are ready, full youtube support is hoping on soon

- [x] Realtime Streaming
- [x] Cache Support (max cache in settings)
- [x] Offline Playback 
- [x] Audio Only mode 
- [x] Downloads 
- [x] Configurable downloads metadata (with auto extraction)
- [x] AV Sync
- [x] Metadata caching system (description/channel details/comments)
- [x] Queue, Playlists & History System
- [x] Video Controls (quality/speed menu, double tap to seek, volume slider)
- [x] Fullscreen & PiP
- [x] Download Tasks Page (ongoing/finished), pause/resume/remove etc
- [x] Watch later Playlist
- [x] Subscriptions ~with groups~
- [x] Import Youtube Playlists
- [x] Channel View
- [x] Playlist View
- [x] Queue View
- [x] History/Most Played/Liked Page

**Comment by okpyjs** [comment]
Hi

**Comment by MSOB7YY** [comment]
Hello, are you encountering any issues or willing to give a suggestion ?

**Comment by shalva97** [comment]
Also add Audio Tracks. For example, https://www.youtube.com/watch?v=3OFj6l2tQ9s&t=831s video has multiple translations and by default it seems to select Vietnamese audio

**Comment by MSOB7YY** [comment]
@shalva97  Newpipe backend provides all audio tracks with language identifiers, which means the only thing left is exposing, grouping & ui adapting, please open a new issue for better tracking

**Comment by MSOB7YY** [comment]
@shalva97 update: Audio tracks are added in  edda4ea438d323a48207966985fae7e0fc9c80b0 and available in [v1.3.0 Release](https://github.com/namidaco/namida/releases/tag/v1.3.0)

**Comment by 1YuvrajS** [comment]
Ticked checkbox seems to be Completed?

And Unchecked Box ongoing development...

**Comment by MSOB7YY** [comment]
@1YuvrajS 
yeah, they are done in code commits, releases are something else

**Comment by MSOB7YY** [comment]
@idontveapc yeah prolly next update with parsed comment timestamp etc

**Comment by kaii-lb** [comment]
any chance of autoplay recommendations? a bunch of other youtube music players have it, and its really useful

**Comment by MSOB7YY** [comment]
@kaii-lb why not add the videos u want to queue? that way u can choose which to play.
if its automatic, u mean to always play the first video after the current one ends?

**Comment by kaii-lb** [comment]
@MSOB7YY not like that no. you know how in Spotify or innertune you can search for a song, play it, and it keeps playing songs similar to the one you searched?

As i mentionend innertune which is ytmusic client and a bunch of other clients have it.

i'll look into implementing myself if i have the time, but thats gonna be FAR away (exams lol)

**Comment by MSOB7YY** [comment]
@kaii-lb i think you are referring to smth like "YouTube mix" or "YouTube music radio", it basically creates a playlist with recommended music.

currently u can achieve similar by tapping on the first mix you see in YouTube recommended videos.

the new youtube client should be able to request a mix playlist, so a button for that might exist later

**Comment by kaii-lb** [comment]
oh okay, thank you. It might be better to automatically play a mix (maybe have it be a setting?) or have a button for it. 

What i understand rn is that its not possible to play more than the mix's number of video, and that the only way to access the mix is by having the YouTube miniplayer turned on?

**Comment by MSOB7YY** [comment]
@kaii-lb yep exactly that's how it is currently

about having it automatic as a settings, will check when everything is ready

**Comment by Krispanda213** [comment]
Helo bro how to play YouTube without ads on namida and how to setup the app plz help

**Comment by Adityak102006** [comment]
I was trying to play songs on YouTube but it kept buffering and then black screen occurred and also when I tried to play video in high quality and then it automatically turns on audio mode and even my internet is fast YouTube takes time to load the content

**Comment by Mariga-jairus** [comment]
YouTube doesn't function at all

**Comment by MSOB7YY** [comment]
@Mariga-jairus #265

**Comment by Austrianpaintar** [comment]
> Hello, are you encountering any issues or willing to give a suggestion ?

hi good morning, I am encountering an error upon downloading the audio recently, and it just goes "download failed" after I press the download button
is there any solution for this? because this is my first time encountering this issue

**Comment by app-raita** [comment]
When trying to import my YouTube history, namida can't find the json file, what could be the reason?

**Comment by MSOB7YY** [comment]
@app-raita can u show a quick video on how to import it? u could be doing smth wrong

**Comment by MSOB7YY** [comment]
@idontveapc posts/shop/community tabs are not supported, this aint a js app

**Comment by app-raita** [comment]
> [@app-raita](https://github.com/app-raita) Nasıl içe aktarılacağına dair hızlı bir video gösterebilir misiniz? Smth yanlış yapıyor olabilirsin

İlgin için teşekkür ederim ertesi gün denediğim de oldu

**Comment by app-raita** [comment]
> [@app-raita](https://github.com/app-raita) Nasıl içe aktarılacağına dair hızlı bir video gösterebilir misiniz? Smth yanlış yapıyor olabilirsin

But I want to ask one more thing.
When I open a song, videos that have nothing to do with the music appear among the recommended music from YouTube, is there a way to hide them?

**Comment by MSOB7YY** [comment]
@app-raita  screenshot pls

**Comment by app-raita** [comment]
> [@app-raita](https://github.com/app-raita)ekran görüntüsü lütfen

![Image](https://github.com/user-attachments/assets/740da5cc-ace3-4a59-9c4d-5ad055bb40e7)
Is there a way to remove the video that I marked in the image

**Comment by MSOB7YY** [comment]
these are related video just like yt app.

if u are logged in it can be related to ur account, u can turn off personalization to get better results (youtube settings -> personalized related videos -> off)

**Comment by app-raita** [comment]
> bunlar tıpkı yt uygulamasında olduğu gibi ilgili videolardır.
> 
> eğer giriş yaptıysanız hesabınızla ilgili olabilir, daha iyi sonuçlar almak için kişiselleştirmeyi kapatabilirsiniz (youtube ayarları -> kişiselleştirilmiş ilgili videolar -> kapalı)

Is there any other way besides this? because I don't use playlists and the songs I like play entirely according to YouTube suggestions. 
Or is it even added?

**Comment by MSOB7YY** [comment]
@app-raita 
when u are signed in, home page & notifications are accessible if u have a memebership as explained here https://www.patreon.com/posts/namida-yt-112913142

if u want actual similar videos (like ytm radio) u have 2 options
1. open queue -> press add -> choose "Mix"
   - this will add a mix playlist (25+ videos just like ytm)
2. go to yt settings -> enable "auto start radio"
   - this will do the same but automatically whenever u play a single video

**Comment by salok08071998** [comment]
Hi

**Comment by salok08071998** [comment]
Facing the issue in YouTube ads how I can fix it

**Comment by divinebody143-tech** [comment]
No working. YouTube streaming is not working there are errors.It is showing the errors

**Comment by MSOB7YY** [comment]
@divinebody143-tech try v6.4.2 beta, if still issue then wait next beta https://github.com/namidaco/namida-snapshots/releases

**Comment by woushjaaj** [comment]
> @divinebody143-tech try v6.4.2 beta, if still issue then wait next beta https://github.com/namidaco/namida-snapshots/releases


Yeah it's not working with the beta version too
![Screenshot_20260818_165123.jpg](https://github.com/user-attachments/assets/6747817e-a31e-463f-b16f-19133465976a)

**Comment by vanshchaudhary286-wq** [comment]
Hey
Today (20 august 2026)
My youtube playback on namida has broke down completely.
From last week , i was facing this issue but after closing app and reopen after some time youtube was playing perfectly...
But today in afternoon
I was enjoying musics and suddenly youtube stops working
I was searching songs and playing them but suddenly songs was not playing
The songs which i played once was working but the new videos which was i playing wasn't working
I have also clear the cache and reinstall the app but its not working.
I have also checked on git hub if there is any update but the app is up to date
Please reply or fix my issue
If there is any new update available please let me know
By the way your namida app is very awesome 
But please fix this bug
