### ISSUE TITLE
Feature Request - Ability to manually create / insert songs into / remove songs from Albums.

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#10]
I know it seems a bit redundant considering what an Album is, but I think the option should be there considering that Namida detects folders as Albums, and if someone wants to, they'll do it through there. Why not skip the middle-man?

**Comment by MSOB7YY** [comment]
you mean an easy way to edit "Album" metadata tag? albums are organized by album tag of each track, folders are organized based on track path

which means that to add/insert/remove, you will **have to edit** `album tag` itself, or `track path` for folders

is that what you want?

**Comment by Red6785** [comment]
I may or may not have been having an oopsie and didn't realize it was a tag.
