### ISSUE TITLE
after updating to the new version; namida stuck on launch screen

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#100]
just did installing update.

and im stuck here...
![Screenshot_20240108-122041](https://github.com/namidaco/namida/assets/122597295/934ac37c-ac93-4d31-be85-451befc4092c)

- it's arm(32) libs version
- and it's the latest version, ofc
- android 11 go(32bit)

**Comment by 1YuvrajS** [comment]
You have to clear Data in order to work.

And Keep in mind, you must backup the Playlist when you are using the Namida App..

**Comment by PlumBlossoms13** [comment]
Do we really have to clear the app data? Mine is also stuck on launch

**Comment by 1YuvrajS** [comment]
> Do we really have to clear the app data? Mine is also stuck on launch
> 
> Edit: It didn't work for me. Still stuck on launch

Yes, Clearing data needed and making sure to keep in mind you need to do App data Backup and if not working then uninstall and install it.

If it still hasn't fixed then report it.

**Comment by PlumBlossoms13** [comment]
I had to reinstall the whole app. Clearing the data and all that won't be a regular thing to update, will it?

**Comment by MSOB7YY** [comment]
@1YuvrajS @PlumBlossoms13 @idontveapc 
### a fix has been made and published, pls install [v1.9.3](https://github.com/namidaco/namida/releases/tag/v1.9.3)
sorry for this, it was due to allowing new queue restoring logic

**Comment by PlumBlossoms13** [comment]
Thank you 💖

**Comment by MSOB7YY** [comment]
@idontveapc 
maybe ur temper
