### ISSUE TITLE
Bug(maybe)

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#107]
I have this .opus file, and when I open it with Namida, it plays just fine it even automatically shows the track in the tracks page, but when I refresh, the track disappears from the tracks page. when I searched for it,  it's right there, i can add it to a playlist, and i can see it on the home page, but it's not on the tracks page or the album that it is from and it doesn't appear in the folder that it is in when i look for it from the folders page. Then I converted it to mp3, and it works just fine. I don't know if you intend to support multiple file types like opus, so this might not be a bug. But it's weird that I can play the track, add it to a playlist, find it in the home page, and search for it, but I can't see it on the tracks page, nor can I find it in its folder or album.

**Comment by MSOB7YY** [comment]
opus files are supported normally, this might be a runtime-only issue, what happens when u restart namida? and also when u refresh/re-index library?

**Comment by z9xx7o0** [comment]
Update: after I posted this issue I converted the file to mp3 and deleted the opus, but you had some questions so I re-downloaded the opus and it worked just fine. so I'd say it was just a glitch, so I'll close this issue.
