### ISSUE TITLE
[BUG] No New Music Added in Recently Added.

### ISSUE THREAD

**Issue by 1YuvrajS** [namidaco/namida#108]
1. I downloaded some music from the internet yesterday and when go to Namida app. The music couldn't appearing in Recently Added in Home Tab.

2. Some file extensions are .temp and webm are showing in it 

3. When I start app then the Media library hasn't re scanned but I have to rescan from setting of Namida App.

Thank You,
Best of Luck.

Screenshots :-

1. .temp files

![IMG_20240113_114356.jpg](https://github.com/namidaco/namida/assets/93419850/d02da245-7e31-4cbd-8e99-1ac0135fb1e1)

2. .webm files downloaded from YT Shorts.

![IMG_20240113_114319.jpg](https://github.com/namidaco/namida/assets/93419850/c5db6fa1-6c02-45c3-aa98-6463c68d7f38)

**Comment by MSOB7YY** [comment]
1. thats because you have to refresh manually as u said in number 3
2. can u send a screenshot?
3. same as 1, u can swipe down to refresh in track page

**Comment by 1YuvrajS** [comment]
> 1. thats because you have to refresh manually as u said in number 3
> 2. can u send a screenshot?
> 3. same as 1, u can swipe down to refresh in track page 

I updated Screenshots.

**Comment by MSOB7YY** [comment]
thanks for pointing this out, fixed in 4c4471eb9a5b62e72d602ddfb2ea14e5d2e9e07d
