### ISSUE TITLE
Edit Tag Glitch.

### ISSUE THREAD

**Issue by 1YuvrajS** [namidaco/namida#109]
1. In Edit Tag, Title box has empty but song Title (while playing in Player) has Track Number like 01. etc and at end Track Name with Website with special symbols.

2. While whole Album Tag editing, when doing some change in it like Date, Album Title, Artist etc saved unchanged but till shows empty next time to check if it has edited or not.

**Comment by MSOB7YY** [comment]
1. not really an issue, tags editing reads the exact tags, wether its faulty or not, while in player, it tries to extract from **filename** (if tags were empty/faulty), thats why u see both different.
if you edited the track outside, select the track/s -> track dialog -> advanced -> force re-index.

2. also not an issue, group editing will **NOT** read each track tags, they will always be empty. the "changed" indicator only indicates that the "field" has been edited.

going to close as its not an issue, reopen if u have different comment

**Comment by 1YuvrajS** [comment]
> 1. not really an issue, tags editing reads the exact tags, wether its faulty or not, while in player, it tries to extract from **filename** (if tags were empty/faulty), thats why u see both different.
> if you edited the track outside, select the track/s -> track dialog -> advanced -> force re-index.
> 
> 2. also not an issue, group editing will **NOT** read each track tags, they will always be empty. the "changed" indicator only indicates that the "field" has been edited.
> 
> going to close as its not an issue, reopen if u have different comment

1. Batch Edit tag still empty when giving Album Name, Artist Name etc.

Screenshots:-

![Screenshot_2024-01-13-22-16-02-072_com.msob7y.namida.jpg](https://github.com/namidaco/namida/assets/93419850/a56da2ed-5339-4723-abe2-61d3d96a2160)

**Comment by MSOB7YY** [comment]
@1YuvrajS yeah thats how it's supposed to be
imagine reading tags of 100+ tracks all at once just to find out of they all share the same album name

**Comment by 1YuvrajS** [comment]
> @1YuvrajS yeah thats how it's supposed to be
> imagine reading tags of 100+ tracks all at once just to find out if they all share the same album name

Yes they share same Album, Artist, Release Year and Genre.

**Comment by 1YuvrajS** [comment]
@MSOB7YY Yes, they share the same Album, Artist, Release Year and Genre.
