### ISSUE TITLE
Bug Report - Cannot edit tags.

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#11]
![Screenshot_20231007_233451](https://github.com/namidaco/namida/assets/88458171/2216dafc-34bc-450f-a81f-fc3061dc6a7b)

**Comment by MSOB7YY** [comment]
please file logs

------
make sure `manage all files` permission is granted
if granted, and on android <9 and editing on sd card, then its a known issue as there is no permission to modify files on sd card with SAF (storage access framework)

**Comment by Red6785** [comment]
My phone doesn't even have an SD card slot. It seems to only affect certain files. Where are the logs?

**Comment by MSOB7YY** [comment]
logs are in `/storage/emulated/0/Android/data/com.msob7y.namida/files/logs.txt`

Next release will include easier log sharing, as well as **ffmpeg tag editing** in case default tagger failed
