### ISSUE TITLE
[FEATURE REQUEST] Previous button replays

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#112]
The previous button replays the current track. You can also make a toggle in the settings. Also, if you could make it that it works from any input method so I can do it  from the miniplayer, notifications, or Bluetooth gestures.

**Comment by MSOB7YY** [comment]
this behavior is honestly annoying, but bothways if it gets implemented it would be from any input.
you can currently long press the position text tho.

**Comment by z9xx7o0** [comment]
I dont mean the button always acts as a replay button that would be very annoying. What I meant is that when the track is more than 5 seconds in, the previous button acts as a replay button, but when it's at the beginning, it acts as normally.

So if I'm playing a track and want to go back I just press the button twice, the first time it restarts the song from the beginning, now it's less than 5 seconds in, when I press it the second time it goes back to the previous track. 

That's the behaviour I'm used to in every android player I've used. Also, you could add a toggle in the settings for the user to select if they want this behaviour or the one that we currently have.

Also, I don't know if it's 5 seconds. That's just a guess, so please check beforehand.

**Comment by MSOB7YY** [comment]
oh ofc ofc i know this, but still personally i don't like it.
it will be controlled by the seek duration inside settings
![Screenshot_20240120-201028_Namida](https://github.com/namidaco/namida/assets/85245079/4571654a-d7d3-439c-82d2-2174510ca684)

and surely it will be optional, only concern that prevents this is to not get settings page bloated, i have to carefully decide which options are really important, but dw i will get to this later

**Comment by z9xx7o0** [comment]
OK, no problem, but can this be controlled by the notifications or Bluetooth device? 

Also this reminds me, there is a small bug with the "minimum track duration to restore last played position" when I set it to don't restore, the next time I open the app, it automatically becomes always restore. So currently, I have it set to 120m.

**Comment by MSOB7YY** [comment]
opsss ur right thanks for pointing out, gonna check
