### ISSUE TITLE
[FEATURE REQUEST] Automatically updating missing tracks

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#117]
Currently, in Namida, when I move a track / rename the file, it detects it as a new track, so I have to recreate my playlists, and everything is messed up. So I think there should be an option where if a track is renamed, moved to a different folder, change the file type, or really any change where the track is still the same, instead of considering it as a new track, it should just detect its the same track (just like detecting duplicates). I constantly redownload my songs, which makes it hard to rearrange them and recreate the playlists and everything. I know there is an option where I can manually change the new file location, but that takes time if I have to do multiple or if I moved each track into a separate folder.

**Comment by MSOB7YY** [comment]
thats quite a heavy task, a missing track needs to be updated in
 - all playlists
 - all queues
 - all history days
 - player queue and selected tracks
 https://github.com/namidaco/namida/blob/1f10167b40ff0bccd44b8a64fab84b9095059726/lib/controller/edit_delete_controller.dart#L92-L111

i can think about a separate screen with missing tracks and their suggestions, but automatically identifying seems like a real no

**Comment by z9xx7o0** [comment]
Can't the tracks be identified just like duplicates can? Or provide a new folder for multiple tracks, and each track automatically finds its match. Or at least when manually selecting a new path, there could be a recommended track at the top.

**Comment by MSOB7YY** [comment]
the identification part is easy, but automatically updating is not possible
- recommended track at top: 
   - that already exists, check the video below, the first one has no possible matches while the second has

https://github.com/namidaco/namida/assets/85245079/a09514c7-dae1-4fa5-b4c4-67f04aeedeca

- providing a new screen with all missing tracks and their possible matches:
   - is what im thinking about

**Comment by z9xx7o0** [comment]
When adding the missing tracks page, is it possible to add an "update all to recommend" button? So each track that is missing that has a recommended track will get updated to that track. Also, it will be important to be able to delete missing tracks from that page because if I wanted to delete a track for good purposely, I should also be able to remove it from the page.

**Comment by MSOB7YY** [comment]
@z9xx7o0 as mentioned, its now implemented, will be found inside indexer page.
about removing missing tracks, well uhh not now, there should be a way to remove tracks from whole database first.. smth that idk if i should implement

**Comment by MSOB7YY** [comment]
just a note, updating ~200 tracks took around 20 seconds (as for 41k history + 2200 queue + 19 playlist)
