### ISSUE TITLE
Bug, issue when refreshing library

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#119]
Sometimes, when I download new tracks and refresh the library, namida doesn't notice them, I have to kill the app and then refresh, and the tracks get added to the library.

**Comment by MSOB7YY** [comment]
what does the report says when u hit refresh? how many new tracks it tells?

**Comment by z9xx7o0** [comment]
It says 0 new tracks even though I added 18 new tracks into my music folder. As I said, when I killed the app and then re opened it, it worked fine. This is not the first time this has happened. It happened maybe 3 or 4 times before.

**Comment by MSOB7YY** [comment]
@z9xx7o0  i really cant reproduce this, everything just works fine
i tried:

 0. checking new files -> 39 new files
 1. copying 2 files and refreshing immediately -> 41 new files
 2. downloading 1 item from yt section and refreshing -> 42 new files
 
 i got no clue how couldnt the files get detected, everything should be working fine

**Comment by z9xx7o0** [comment]
It might be an android 14 thing. It doesn't happen often, but it did happen multiple times. And it's not a big issue. All I have to do is close the app, and if it works fine.

**Comment by MSOB7YY** [comment]
@z9xx7o0 checked again on Android 14 and everything is fine.
got no more clue for this, any pattern that u follow before the issue happens?

**Comment by z9xx7o0** [comment]
Well, all I did was organise some of my files, move here to there, delete, add new files, etc. I go to see if my tracks have been updated in Namida, but when i refresh, it hasn't detected any change. I tried multiple times, and there were still no changes, so I closed the app, reopened it, refreshed, and then it worked fine. If you can't recreate this, don't bother wasting anymore time. it's a small bug. It isn't going to affect the user experience.

**Comment by MSOB7YY** [comment]
@z9xx7o0  it turns out the issue was that directories weren't force re-scanned, i was basically forcing it only when folders change from indexer folders, thanks again for pointing out.
