### ISSUE TITLE
[FEATURE REQUEST] Confirmation Dialogs

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#120]
It would be amazing if you could add a confirmation popup in certain places like:
- remove from playlist
- add tracks to a playlist
- adding duplicate tracks

It is annoying when I accidentally add tracks to the wrong playlist or removing tracks from the playlist accidentally or adding duplicate tracks and having to remove them, so I think adding this might help.

**Comment by MSOB7YY** [comment]
1. removing from a playlist: 
  - u already get an undo button when u remove something, this is better for faster removal, in the same time it's unlikely to accidentally remove tracks, u have to either press that in a dialog or manually enable reordering/removing then remove a track 
2. adding to playlist:
  - also not a good idea, its pain, pls be careful with ur touches. most players/services adds without confirmation already, at least all i have used.
3. adding duplicate tracks:
  - this might be good but what about when adding some tracks of which only few of them are duplicated? im thinking about showing dialog with 3 options:
    1. add all and remove old ones
    2. add only missing
    3. add all tracks

**Comment by z9xx7o0** [comment]
That seems great! If you don't like the confirmation popup for adding to a playlist, please consider adding an undo button just like the remove button.

**Comment by NikunjKhangwal** [comment]
What about deleting playlist? The delete button is on the lower end of screen and undo button appears at the very top of screen creating a displacement gap. There's more chances of missing it. I would suggest to have the undo button pop-up around the same area as delete if confirmation dialogue isn't possible.
