### ISSUE TITLE
Black screen bug

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#121]
Sometimes, when opening namida, I get a black screen. https://github.com/namidaco/namida/assets/83415416/5d77ec15-7c0a-47f4-b88a-ff6e354bca5b

**Comment by MSOB7YY** [comment]
this might be an Android 14 thingy, cuz as seen in the video going out and in again fixes the issue

**Comment by z9xx7o0** [comment]
It doesn't bother me. Just wanted to mention it in case it's important.

**Comment by MSOB7YY** [comment]
is this still happening? @z9xx7o0 on latest beta?

**Comment by z9xx7o0** [comment]
@MSOB7YY , I don't actually use the beta. But even in the latest full release 2.5.6, this seems to have stopped. I'll try to recreate it in the upcoming full release and let you know.

**Comment by MSOB7YY** [comment]
nice, gonna close then
