### ISSUE TITLE
[FEATURE REQUEST] Fallback artwork from folder.jpg etc

### ISSUE THREAD

**Issue by modestderp** [namidaco/namida#122]
Would really appreciate if the player has the ability to allow the user to select whether to use the folder album art in the folder path or the embedded album art within the song when using "Folder" or "Album" view.

Currently all my song collections have no embedded album art which makes finding a specific album a bit hard, and the now playing screen/dialog very bland because no album art is displayed.

**Comment by MSOB7YY** [comment]
so basically a fallback artwork from folders, i was intending to implement this but forgot at some point, thanks for reminding.
can u pls provide some examples for the filename of these folder artworks? i have plenty in mind but an addition is better

**Comment by modestderp** [comment]
Personally I only have two filenames for each album: "folder" and "cover" (in either PNG or JPEG formats).

I have seen people use "album" or "art" as well.

**Comment by MSOB7YY** [comment]
alright thankies
will work on this soon

**Comment by foreveryone1** [comment]
I've also seen front.* occur pretty commonly as well!
