### ISSUE TITLE
[BUG] Lyrics disappearance & app marking available track as deleted

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#123]
Both of these bugs occurred only once.

1. One time the lyrics suddenly disappeared for a track (it was working fine before) and appeared again when i switched tracks.
![IMG_20240207_190228](https://github.com/namidaco/namida/assets/99175083/50090a46-2072-4b94-8c15-b85f92a609fd)

2. When i pressed on a deleted track and clicked on the track after it, the app didn't played the 2nd track and marked it as deleted too. Tho switching between another track and then coming back fixed it.

**Comment by MSOB7YY** [comment]
the recent commits should have already fixed these, feel free to reopen otherwise (next update in few days or use the beta)

**Comment by NikunjKhangwal** [comment]
Okie
