### ISSUE TITLE
[Feature Request] Option to keep the screen awake when lyrics are active

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#124]
Pretty much the title. It's only possible for video rn.

**Comment by MSOB7YY** [comment]
the whole wakelock wasn't even well implemented, with d7bb2bf2fdfd3a017eea691825e60bf6a0823e8a, having a timed lrc on screen is automatically considered to be a video.

**Comment by NikunjKhangwal** [comment]
Doesn't seem to work for me. Is it same for embedded lyrics or online fetch lyrics?

**Comment by MSOB7YY** [comment]
bro i just rewrote the damn thing, wait the next release

**Comment by NikunjKhangwal** [comment]
F, i thought it was already implemented. My bad.
