### ISSUE TITLE
[BUG #126] WHITE OVERLAY ON SCREEN

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#126]
I had a bug earlier where when I tap the three dots, I get a white screen. As always restarting the app fixed the issue. https://github.com/namidaco/namida/assets/83415416/40a90b84-de6f-4536-9426-f98eb5231b20

**Comment by z9xx7o0** [comment]
Also, while you did an amazing job with adding all these new features, I'm sorry to say that the "resume if was paused by interruption" still doesn't work. I tested it out with multiple apps, and the only one it worked with is tiktok. It didn't work with youtube, video player, web browser, or yt music. Only tiktok. But anyways, thank you so much for fixing the notification resume bug!

**Comment by MSOB7YY** [comment]
please share logs, this should tell what exactly happens for white screen issue

as for resuming after interruption, its confirmed to work on insta, and u confirmed it working on tiktok, and it will work with any app that *properly* set media session as inactive whenever it pauses, in short this is other apps problem not namida's

**Comment by z9xx7o0** [comment]
Here are logs:

![logs.txt](https://github.com/namidaco/namida/files/14289738/logs.txt)
