### ISSUE TITLE
[SUGGESTION] - How do I Improve Treble of OnePlus Nord Bud with Namida Equalizer?

### ISSUE THREAD

**Issue by 1YuvrajS** [namidaco/namida#127]
I got a OnePlus Nord Buds 🎧 a Years ago. I tried listening to songs 🎶 for the first time in the OnePlus Nord Buds, I noticed full Bass and less Treble and Details. I tried Nord Buds on another device like Oppo phone, PC etc and it still sounds the same.

OnePlus Nord Buds uses Titanium Driver 🔈 with the size 12.4 mm. 

I have previously Samsung Level U but sound Balanced 50% BASS and 50% Treble. With the same 12 mm driver 🔈not a Titanium.

Is it possible to fix it using Equalizer or buying another Ear Buds for 12.4 mm driver 🔈 Balanced 50% BASS and 50% Treble. It is hard to find it.

**You can Refer to the OnePlus Site:-**

https://www.oneplus.com/uk/oneplus-nord-buds

**Comment by MSOB7YY** [comment]
obviously i have no idea, if u mean u want a treble/bass tweak support, then its not possible to do so directly in namida, u will have to manually modify frequencies sliders (as i do)
the lower ones (0-500 hertz for example) are for bass, and higher ones (2k+) will affect treble

you can also use external equalizer like poweramp but that would lead to another issue currently #60 

as for me, i use dolby atmos as root equalizer and lower the bars on the right (treble), the equalizer is system wide and doesn't depend on each player

**Comment by 1YuvrajS** [comment]
> EDIT: tldr; if u think the bass is too high, reduce the sliders on the left. if u think treble is too low, increase the sliders on the right
> 
> ---
> obviously i have no idea, if u mean u want a treble/bass tweak support, then its not possible to do so directly in namida, u will have to manually modify frequencies sliders (as i do)
> the lower ones (0-500 hertz for example) are for bass, and higher ones (2k+) will affect treble
> 
> you can also use external equalizer like poweramp but that would lead to another issue currently #60 
> 
> as for me, i use dolby atmos as root equalizer and lower the bars on the right (treble), the equalizer is system wide and doesn't depend on each player

I tried Adjusting EQ for OnePlus Nord Buds earbuds, it never gave any changes due to Titanium Driver (also tried on Miui EQ, gives little changes but not best).

I am confused between Dynamic Driver (might be Balanced in Vocal and Bass 🤔) in Realme Buds T300 earbuds ( I checked specs carefully and researched ) and Titanium Driver (Deep Bass and less details 😖) in Nord Buds.

Can you try listening to the song See You Again by Charlie Puth, Starboy by The Weekend and Hello by Adele in Dynamic and Titanium Driver in the same range of 7mm, 10mm, 11mm and 12.4mm driver, if you have these earbuds.

**Comment by MSOB7YY** [comment]
sorry i have no experience with this, u might ask on telegram group or in any telegram group/subreddit dedicated to audio equalizing, i have cleared my part of the question.
