### ISSUE TITLE
[BUG] Navigation Bar overlapping with music controls when lyrics are expanded

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#128]
This
![IMG_20240217_133644](https://github.com/namidaco/namida/assets/99175083/75b9ae69-b0b3-48b9-bac2-8fbabd5b125c)

**Comment by MSOB7YY** [comment]
opsss mb gonna fix

**Comment by NikunjKhangwal** [comment]
@holiq How's your text size small and mine is so big?

**Comment by MSOB7YY** [comment]
@NikunjKhangwal thats `font scale` percentage, decrease it inside customization settings

**Comment by NikunjKhangwal** [comment]
@MSOB7YY It's global setting sadly. I only wanted to decrease the lyrics size.

**Comment by MSOB7YY** [comment]
@holiq fixed
@NikunjKhangwal also u can now pinch in/out inside lyrics screen to scale text, this is separate from the global setting (final result = lyrics font scale * global scale)

**Comment by holiq** [comment]
@NikunjKhangwal I use font scale 80%
@MSOB7YY thanks it fixed

**Comment by NikunjKhangwal** [comment]
@MSOB7YY Thanks
