### ISSUE TITLE
Editing Tags corrupts files (changes duration of songs)

### ISSUE THREAD

**Issue by f4b4d1** [namidaco/namida#129]
When editing a songs tags and douple tapping on save while listening to it, the duration gets shortend when starting it again after another song has played.
Discovered it yesterday as I was naming some 1 hour long mixes on my phones SD-card. Sometimes I tapped a second time on "Save". When starting the song again it seems like the already listened part got cropped out and only the not listened part is left in the file. (The whole file size gets altered)

Steps to reproduce:
0. Have a Backup of Song A
1. Start a (long) song (Song A) and skip into the middle of the song
2. Edit tags of Song A (e.g. change Title)
3. Double-Tap on Save
4. Start a different song (Song B)
5. Start Song A again.
6. Compare duration of Song A before and after editing the tags

**Comment by MSOB7YY** [comment]
holy shit that's true 
damn, it seems like the issue happens only when double tapping "save", am i correct?
thats obviously due to concurrent writing to the same file, making it corrupted, gonna disable save button while saving
have u encountered a similar issue just by tapping "save" (not double tapping) ?

**Comment by f4b4d1** [comment]
I tried several times with just tapping once, but it only happend with double tapping.
I tapped a second time because saving took a little bit longer for the long songs. After that I thought they were gone (sorted by duration) but they were just shortend.

**Comment by MSOB7YY** [comment]
now the button will be disabled while saving, sorry for the issues caused.
if u want u can use the snapshot build from https://github.com/namidaco/namida/actions/runs/7966602874 (it will be separate version)

**Comment by f4b4d1** [comment]
No problem, fourtunately I noticed it early in the process.
Thanks for the quick fix and keep up the good work!
