### ISSUE TITLE
Downloaded songs to mp3 files?

### ISSUE THREAD

**Issue by mesutde** [namidaco/namida#131]
s it possible to share the download songs with other music player application. Can be shared by exporting downloaded songs to mp3 format?

**Comment by MSOB7YY** [comment]
i don't really get what's ur question
- sharing music: files are downloaded to their download location ("`Internal/Namida/Downloads`" by default), u can go there using any file manager and share it to whatever app
- downloading in mp3? im not doing that, audio is downloaded in its original format without editing, wethet it's `.m4a` (acc) or `.weba` (opus), it's kept as is without any conversion. refer also to #9
