### ISSUE TITLE
Is it possible to listen to YouTube clips only the music?

### ISSUE THREAD

**Issue by mesutde** [namidaco/namida#133]
![image](https://github.com/namidaco/namida/assets/16664425/42585481-e8c9-4522-814e-a8ed28032443)

Is it possible to listen to YouTube clips only the music? without video Like Spotify?

**Comment by MSOB7YY** [comment]
have u considered using "audio only" from quality menu? u can also persist it from YouTube settings

**Comment by mesutde** [comment]
> have u considered using "audio only" from quality menu? u can also persist it from YouTube settings

Which one ?


![image](https://github.com/namidaco/namida/assets/16664425/696d2de0-7f40-4f01-9e50-2873d3288590)

**Comment by mesutde** [comment]
Which One?
![image](https://github.com/namidaco/namida/assets/16664425/d2a3fb14-7dd4-40d8-9f7c-13f1523a9f55)

**Comment by MSOB7YY** [comment]
"remember audio only mode" 
u enable it, it will remember if u choose it from quality menu or not
