### ISSUE TITLE
[BUG] Emulator version crashes when starting up

### ISSUE THREAD

**Issue by HareToAme** [namidaco/namida#135]
namida-v2.0.1-x86-release-emulator.apk or namida-v2.0.1-x86_64-release-emulator.apk

I used the Android 13 emulator in Android Studio to install the application.

After installation, the application crashes when starting up.

The previous versions of the application did not provide x86_64 APK installation package, so I can't test whether the previous versions also have this issue.

**Comment by MSOB7YY** [comment]
no longer want to worry about this, just use the normal arm & arm64 variants
