### ISSUE TITLE
While sliding time to change YouTube video playback; thumbnail is showed and audio plays.

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#137]
When ever you change video playback duration the video thumbnail shows up and just audio plays from that duration. No image moves.

**Comment by MSOB7YY** [comment]
do u have any video to showcase? everything works fine on my side

**Comment by MSOB7YY** [comment]
nah i mean a video u record showing the bug

**Comment by OwenD30** [comment]
I can confirm I also have this issue. I wasn't able to replicate it while screen recording, but it's exactly as described: you scroll back and it starts playing audio only with the cover even though a video mode is selected. Here's a screen recording demonstrating that I can fast forward fine but going backwards never works. 

https://github.com/namidaco/namida/assets/77121604/2e1c52a0-ca00-48f4-9146-b9bee6093008

Right after I finished this recording it started displaying the thumbnail and audio only despite it being set to 1080p.

Other issues: the app seems to really tax my CPU (it doesn't run very smooth) and drains my battery. I have a pixel 7. Idk if this is efficiency related or just a result of having so many features on one app.

Also, sometimes if I go back to another song quickly by going next then previous it leaves off at the same time as when I skipped it. See below:

https://github.com/namidaco/namida/assets/77121604/b48c02a4-16ce-4485-9262-1be969972d08

However, these are all issues that can be fixed and I wanted to thank you for your insane amount of work on this app. It's crazy you were able to do this on your own and release it for free. Super hype for future YT Music integration :-)

**Comment by OwenD30** [comment]
Edit: how quick I move between songs doesn't affect it starting from where I left off. It does it no matter what.

**Comment by MSOB7YY** [comment]
@OwenD30 thanks for providing detailed report, here is some explanation:
1. video playback turns off/bugs when seeking backwards
   - gonna investigate in this, the playback is kinda sensitive cuz of how caching works (it opens a local proxy server and redirect to exoplayer), gonna see
2. getting smooth experience is still achievable
   - u gotta make sure that blur, glow, parallax is off from customization settings 
   - u can just enable balanced/performance mode from advanced settings, this will do the same + reduce image quality
   - auto coloring is also kinda expensive, u can disable it too (along with "`force miniplayer to follow colors`") to remove lag while switching tracks
3. track continuing from last played position
   - that's a feature lmao, u can tweak that in `playback settings > minimum track duration to restore last position`, increase it to a desired number or until u disable it
 
also thanks a lot for ur nice words, im just glad ppl still appreciate like u do 💖

**Comment by OwenD30** [comment]
Awesome. Thank you so much.

I noticed too that sometimes the playing audio only while in video mode bug happens when you finish a video and hit play to start it over again. But not always.

Also, the comment replies button has never done anything when I tapped it. I think it should show the comment replies?

**Comment by OwenD30** [comment]
Haha one more thing: the "v" in "views" under the channel page should be capitalized, I only notice this because the rest of the app is so polished :-)

![Screenshot_20240304-181302.png](https://github.com/namidaco/namida/assets/77121604/052ff169-c5f3-4e66-a563-cb4f450f3bba)

**Comment by MSOB7YY** [comment]
@OwenD30 alr imma investigate this video bug

comment replies is not implemented yet

and oki will capitalize "views"... BUT BRO WHY UR FONT SO BIG 😭

**Comment by MSOB7YY** [comment]
also i noticed ur miniplayer is on top of navbar without background.. is this normal?

**Comment by OwenD30** [comment]
Haha for some reason I like the bigger fonts look for this app 😂

Yeah for the videos it looks like this

![Screenshot_20240304-195550.png](https://github.com/namidaco/namida/assets/77121604/0dd56fbb-6b22-4d08-a2ce-2293f94d6cf9)

And for music it looks normal

![Screenshot_20240304-195614.png](https://github.com/namidaco/namida/assets/77121604/8ad30c3b-5709-4db7-8bd6-51c22b42ba10)

Also, just remembered that when switching songs without a Bluetooth device connected my phone speakers make very loud blips sometimes.

**Comment by MSOB7YY** [comment]
is this still issue after v2.0.6?

**Comment by OwenD30** [comment]
Which issue? I mentioned a few haha

**Comment by MSOB7YY** [comment]
@OwenD30 oh i was mentioning the author. your issues are already resolved.

for this issue, it should be already fixed bothways either since that version or in the next one (v3.x.x), if not just reopen this again
