### ISSUE TITLE
Picture in Picture and downloads not working

### ISSUE THREAD

**Issue by OwenD30** [namidaco/namida#140]
The picture-in-picture mini player sometimes works and sometimes doesn't when I swipe out of the app. It seems to not work more than it works. I have it enabled in settings.

Also, downloads will get to the very end, then freeze and never finish.

**Comment by MSOB7YY** [comment]
wdym doesn't work? doesn't show at all or shows with black screen?
ultimately, u need to press home button (or swipe up), and not pressing back or recents button, while a video is available and is playing (not paused)

if it shows but with black screen, then it was a bug and was fixed lately

---

which end? the progress is 100%? if so then do u find a downloaded file at the download location or not? if not then pls send logs from settings>about

**Comment by OwenD30** [comment]
https://github.com/namidaco/namida/assets/77121604/34281da7-b9fa-4e71-8a99-edf06ed32357

That's the picture-in-picture problem.

I'll try to recreate the download problem

**Comment by MSOB7YY** [comment]
download issues are probably all fixed by now. about pip can u confirm it its still an issue?
latest version is v4.0.8 beta https://github.com/namidaco/namida-snapshots/releases
