### ISSUE TITLE
Downloaded music files are not automatically added to the playlist

### ISSUE THREAD

**Issue by mesutde** [namidaco/namida#141]
Music files downloaded from YouTube are not automatically added to the playlist.

How should I go about the solution?

**Comment by MSOB7YY** [comment]
hello, what playlist u mean ?
by default, downloaded music **only** files will be added to library normally. videos are not added.
what is ur issue exactly?

**Comment by MSOB7YY** [comment]
but this already should happen.. it might be required to give "manage all files" storage permission, give it and everything should be fine

**Comment by mesutde** [comment]
![image](https://github.com/namidaco/namida/assets/16664425/189c21c0-4a7a-4994-806e-317d4b4b3a53)

I don't have this process.
What else do I need to do?

Do I need to do anything else to get the songs I downloaded to the home page instantly?

**Comment by MSOB7YY** [comment]
@mesutde what format are u downloading in exactly? can you provide a screenshot or a video? + screenshot for ur downloads page

to make sure permission is given: go to ur phone settings > apps > namida > permissions > enable this one
![Screenshot_20240328-171930_Permission_controller](https://github.com/namidaco/namida/assets/85245079/5a8db43b-8f26-4ec9-b78f-d80f308f77c9)
