### ISSUE TITLE
[bug] download error 

### ISSUE THREAD

**Issue by farzana840** [namidaco/namida#143]
After downloading a video from YouTube, when I play it without internet, it plays in audio mode only and there is no video option even if I downloaded the video version

**Comment by MSOB7YY** [comment]
downloading and caching are 2 different things, in ur case u will have to enable this (there will be 2 copies of the file so storage taken will be doubled..)
![Screenshot_20240312-144829_Namida](https://github.com/namidaco/namida/assets/85245079/9b33cc71-5972-45c9-9c8c-8f11307ea562)
