### ISSUE TITLE
[BUG](snapshot) next/prev buttons, queue not saved after shuffling

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#147]
The next and previous buttons don't work, and when I try to navigate through the queue it just doesn't work, I restarted the app, and I was on a different track and queue and when I went to see the queue history because I liked the shuffle, the queue was not there only the new different queue I have when I opened the app which was the normal unshuffled playlist.

**Comment by MSOB7YY** [comment]
yo, the first issue was in the snapshot version, its fixed now in https://github.com/namidaco/namida/actions/runs/8409091353

second issue is just queue not being saved after shuffling, now fixed, will be available in https://github.com/namidaco/namida/actions/runs/8410348636 "rip for the shuffled queue u liked :<"
