### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#148]
I don't know if this is related to the previous bug #147, so I was on that queue and removed a track from the playlist with the "Enable reordering" paused for a couple of minutes and came back and that's when #147 happened, anyways when I finished reporting that bug i wanted to continue so I shuffled the same playlist again and when the second song finished the sound of that removed track started playing, I skipped it with my Bluetooth gestures so I couldn't see if it was played or just the sound, so I came back and skipped to the previous track but that removed one wasn't there nor was it in the queue. I don't know if this will ever happen again, but I just wanted to point it out.
Log:
![logs.txt](https://github.com/namidaco/namida/files/14704882/logs.txt)

**Comment by MSOB7YY** [comment]
this really is weird, i checked the logs and found nothing.
removed tracks reflects instantly in the queue, same as shuffling. so playing smth should exactly be in the same order that u see

if u can reproduce it would be better, otherwise this seems so sus for a bug
