### ISSUE TITLE
[FEATURE REQUEST] Sorting sub folders within an album according to album path? 

### ISSUE THREAD

**Issue by modestderp** [namidaco/namida#151]
I'm not sure how to word this, so please forgive me if this sounds confusing.

I have albums that contains more than 1 discs, and usually I would manage them by creating separate folders for each disc like the below:

**/main/Music/Some Artist A - Album A/Disc no.**

So as you can see, under Album A, I could have several folders corresponding to the number of discs from that album.

Currently I'm running into a situation with Namida is that under Folder view, all the "Disc no." folders are grouped together ignoring the respective parent album folder:

_What I want:_
**/main/Music/Some Artist A - Album A/Disc 01
/main/Music/Some Artist A - Album A/Disc 02**
/main/Music/Some Artist B - Album B/Disc 01
/main/Music/Some Artist B - Album B/Disc 02

_What's happening:_
**/main/Music/Some Artist A - Album A/Disc 01**
/main/Music/Some Artist B - Album B/Disc 01
**/main/Music/Some Artist A - Album A/Disc 02**
/main/Music/Some Artist B - Album B/Disc 02

I have Poweramp as well and somehow it is able to achieve what I want. I am wondering if Namida is able to as well?

Thanks!

**Comment by MSOB7YY** [comment]
that happens due to current logic of folder view, where sub-folders that have no tracks are shortened (like displayed directly to reduce 1 folder step). apparently this seems non convenient in many cases so either this needs to be turned of or implemented better, i should get into this sooner

**Comment by modestderp** [comment]
> that happens due to current logic of folder view, where sub-folders that have no tracks are shortened (like displayed directly to reduce 1 folder step). apparently this seems non convenient in many cases so either this needs to be turned of or implemented better, i should get into this sooner.
> 
> also a screenshot would be better in case i understood wrong

Please see the [link](https://imgur.com/a/tFY8ADu) for the screen cap. As you can see all the "Disc 01" and "Disc 02" are grouped together, regardless of the actual album/parent folder.

**Comment by MSOB7YY** [comment]
yeah it's cuz of what i said, gotta get into it soon

**Comment by MSOB7YY** [comment]
hey uh, the new logic should keep things more consistent now. u shall navigate as u would in file manager, no more deep folders extraction
