### ISSUE TITLE
[FEATURE REQUEST] Allow word wrap for folder name when in "Folder" view

### ISSUE THREAD

**Issue by modestderp** [namidaco/namida#152]
Just wondering if it is possible to implement a toggle to allow word wrap for long folder names when in "Folder" view. As currently I have some folders with long album names and they are just abruptly cut off.

Thanks.

**Comment by MSOB7YY** [comment]
can u show screenshot?

**Comment by modestderp** [comment]
> can u show screenshot?

Please see the [link](https://imgur.com/a/k3dfiBo) for screen cap. You can see the folder name/album name is cropped because it's too long.

**Comment by MSOB7YY** [comment]
uhh im not so sure about this yet, the height is fixated to improve scrolling, so allowing word wrap might just cause the text to be cropped.. might have to allow dynamic size and it should be okay since there aren't always much folders in the list.. gonna see

**Comment by MSOB7YY** [comment]
did this in 409d464868072ff662a46d787047b225f8a6a516, u can use the beta build if u want to use it right away https://github.com/namidaco/namida/actions/runs/8862996634
