### ISSUE TITLE
[Feature request] Subsonic

### ISSUE THREAD

**Issue by GGORG0** [namidaco/namida#153]
It would be really nice to integrate with the open Subsonic API for streaming music from servers such as Navidrome!

**Comment by MSOB7YY** [comment]
this duplicate of #91, i dont use navidrome/subsonic or similar services so idk how to implement it, if u know other open source players that support this lemme know, although bothways this ain't a priority at all currently

**Comment by NikunjKhangwal** [comment]
[This app](https://github.com/austinried/subtracks) supports both, also written in Dart.

**Comment by MSOB7YY** [comment]
@NikunjKhangwal @GGORG0  as expected, its a pure api. no plans for this at all currently, especially that it will require separate playback, read #156 for more info

**Comment by NikunjK8** [comment]
I don't need it actually. Just shared if it might help :)

**Comment by MSOB7YY** [comment]
@NikunjKhangwal oh i see that was a wrong mention, thanks :)

**Comment by MSOB7YY** [comment]
hi guys
Subsonic (navidrome, airsonic, gonic, etc) and WebDAV support is added in v5.7.2, check it out ^^
https://github.com/namidaco/namida-snapshots/releases
