### ISSUE TITLE
[Feature request/suggestion] Add Yt downloaded videos also in main library 

### ISSUE THREAD

**Issue by arun28082007** [namidaco/namida#156]
When we download video of a song it was considered in other downloaded section of youtube tab, we can't play it with other m4a or mp3 files. We have to play it differently.

For example:) when I play a playlist of 30 songs after Playing 2-3 song  if i want to play a song downloaded in video format and saved in yt section. I can't do this because my playlist is stopped and only music video is played 

I want a feature that consider downloaded music videos in main library

**Comment by MSOB7YY** [comment]
hello, downloaded music
-only files are added normally to ur local library, while videos are not. its called local tracks, adding videos to it is kinda uuh...

also the playback is separated currently for many reason, but overall, changing this behavior will require a full refactor of the code and a reimplementation of some features (ex. queues, playlists), this also means changing how namida should behave and making many parts useless (like youtube queues or playlists) resulting in a complete mess. i had promised to relook into this after implementing full video playback but currently im not changing this

simple workaround is to download music only, and when u play it it will automatically fetch the video

**Comment by MSOB7YY** [comment]
now that local video playback is implemented in beta, everything downloaded in namida is added to local library immediately (including videos), just make sure that the folder of namida downloads is included in indexer folders in settings.

*note: swipe to refresh had a bug and was fixed earlier*

you can use the latest beta from here https://github.com/namidaco/namida-snapshots/releases (v4.0.5 as of now)
