### ISSUE TITLE
App Creating Multiple Empty Queues

### ISSUE THREAD

**Issue by PlumBlossoms13** [namidaco/namida#16]
Hello! So far I really love the app but I'm having a problem. I've created a playlist with the tracks I wanted. When I go to the playlist tab, I click the three dots on the side and press the shuffle option. But when I do this, instead of playing the songs shuffled, it creates an empty queue that I can't delete like this and nothing plays. Any help would be appreciated!

![Screenshot_20231011-003220](https://github.com/namidaco/namida/assets/109384939/07152285-8f8d-4621-b2c2-5f04878f677a)

**Comment by MSOB7YY** [comment]
Interesting, i were able to reproduce the issue, will push a fix soon, thanks for the notice.
(as for now u can "play all" and then shuffle from player queue view)

**Comment by MSOB7YY** [comment]
fixed in d2953e238f1442309c70b46537e53866f04d96fb
basically i was optimizing one of the internal methods that shuffling depends on, causing it to play items before queue is filled.
thanks for reporting

**Comment by PlumBlossoms13** [comment]
Thank you for all your hard work!
