### ISSUE TITLE
[FEATURE REQUEST] Separate lyrics font size in miniplayer and in lrc fullscreen

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#160]
I set a medium text size for lyrics and they appeared fine for a while on thumbnail but then got too small 
![IMG_20240408_105328](https://github.com/namidaco/namida/assets/99175083/f6e79968-f117-401e-bf58-a2a18cfbc6b0)

**Comment by NikunjKhangwal** [comment]
Looks like the size is applied directly for both
![IMG_20240408_105643](https://github.com/namidaco/namida/assets/99175083/77c574af-88bb-4ef5-9914-d9abdc63e4fc)

**Comment by MSOB7YY** [comment]
i dont get what exactly is the issue, lyrics font size is bigger in fullscreen and always has been, check https://github.com/namidaco/namida/blob/492813e66a6920371f6ed3e858205e35bce176e5/lib/packages/lyrics_lrc_parsed_view.dart#L177-L178

**Comment by NikunjKhangwal** [comment]
Then i think it should be same for both

**Comment by MSOB7YY** [comment]
i don't think so, the focus on lyrics in fullscreen is not the same as when viewed along with other ui elements

**Comment by NikunjKhangwal** [comment]
As mentioned, the size on thumbnail becomes too small when size in fullscreen isn't big enough. So you have to manually change the size for thumbnail lyrics again if you want to read lyrics there and then need to change it again for fullscreen. That's what i was referring to.

But also i don't use thumbnail lyrics a lot so i guess it's fine. Closing the issue

**Comment by MSOB7YY** [comment]
hmmm maybe an easier solution is to separate font scale for both expanded lyrics and normal, gonna look into it

**Comment by MSOB7YY** [comment]
they are now separated in d7afa9a8435f33f3f3507a9b46041236a1e6217e <3

**Comment by NikunjKhangwal** [comment]
Keep cooking like this

![bear-byebear](https://github.com/namidaco/namida/assets/99175083/6254f627-3163-4f0a-ab93-700bdad30560)
