### ISSUE TITLE
[Bug] Random Lyrics disappearance

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#162]
This happens while seeking

https://github.com/namidaco/namida/assets/99175083/5070f4ce-35b9-4c7e-ad79-dbd63e5e2b7e

https://github.com/namidaco/namida/assets/99175083/efb6e9a8-e579-4317-84e0-bb598126edc4

**Comment by MSOB7YY** [comment]
thanks for the showcasing videos, this is a duplicate of #132, pls follow up there
