### ISSUE TITLE
Blank queue in history

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#163]
![Screenshot_20240409_050131.png](https://github.com/namidaco/namida/assets/83415416/6b30f71a-68e5-474c-873c-32fab5b43a4d)

After tapping it, it became a queue with 0 tracks.

![Screenshot_20240409_050459.png](https://github.com/namidaco/namida/assets/83415416/bc046abf-39cd-4242-be5c-80f9e71b6ee5)

**Comment by MSOB7YY** [comment]
wutdaheeeeeel what exactly happened? any steps to reproduce?

**Comment by z9xx7o0** [comment]
I don't really know, I lost a good shuffle (again) and went to find it and saw it blank

**Comment by MSOB7YY** [comment]
this should be fixed by 87c59b077d55dcc99a6ef201104e8f8bd73c7a50.. probably.. hopefully..
