### ISSUE TITLE
[BUG] lyrics full screen button rarely works

### ISSUE THREAD

**Issue by aneesh1122** [namidaco/namida#171]
I touched the lyrics full screen icon
## Expected Behavior

It should have expanded easily
## Current Behavior

It doesn't expand even after multiple touches
## Steps to Reproduce

1.open any song
2.enable lyrics
3.let the lyrics load
4.click the icon which gets the lyrics in full screen

## Screenshots

https://github.com/namidaco/namida/assets/45353488/34b6fe92-a452-4ad7-a608-4ccb999a11c7

**Comment by MSOB7YY** [comment]
that's due to artwork being scaled up, this causes the hittest to slightly go out of range, for more info check https://github.com/namidaco/namida/issues/50#issuecomment-1837556192

- workaround:
  - pinch in/zoom in while synced lyrics is shown to enter fullscreen 
- fix:
   1. enable artwork gestures from customization settings
   2. open miniplayer/player ui
   3. pinch out/zoom out to scale artwork down
   4. *optional*: disable artwork gestures again

**Comment by aneesh1122** [comment]
> that's due to artwork being scaled up, this causes the hittest to slightly go out of range, for more info check [#50 (comment)](https://github.com/namidaco/namida/issues/50#issuecomment-1837556192)
> 
> * workaround:
>   
>   * pinch in/zoom in while synced lyrics is shown to enter fullscreen
> * fix:
>   
>   1. enable artwork gestures(scale multiplier) from customization settings
>   2. open miniplayer/player ui
>   3. pinch out/zoom out to scale artwork down
>   4. _optional_: disable artwork gestures again

The fix is working although pinch in/zoom in only increases the lyrics font, it doesn't let me enter full screen.

**Comment by MSOB7YY** [comment]
ops ur right lemme check

**Comment by NikunjKhangwal** [comment]
Since pinching is now used for scaling text size, the fullscreen method isn't possible. I would recommend changing double tap on artwork to enter fullscreen lyrics directly as a workaround for now. We already have extra button to toggle minimized lyrics anyway. In future more shortucts could be added for tapping, double tap and hold as mentioned in #81

**Comment by aneesh1122** [comment]
> Since pinching is now used for scaling text size, the fullscreen method isn't possible. I would recommend changing double tap on artwork to enter fullscreen lyrics directly as a workaround for now. We already have extra button to toggle minimized lyrics anyway. In future more shortucts could be added for tapping, double tap and hold as mentioned in #81

I actually like how I can have lyrics by double tapping on the album cover. 

The fix works great though. At 90% the full screen toggle works perfectly and the cover is barely smaller

**Comment by NikunjKhangwal** [comment]
Just a workaround for time being, not a permanent solution. I like it too :)

**Comment by MSOB7YY** [comment]
@NikunjKhangwal @aneesh1122 i agree that double tapping should enter fullscreen, or at least make it optional
so the proposal:
 - tap: does nothing (used to tap lyric line to jump to it)
 - double tap: could be "enter fullscreen" or "toggle lyrics"
 - long press: could be "enter fullscreen" or "toggle lyrics"
 - pinch/zoom in: scale font size

**Comment by NikunjKhangwal** [comment]
How about:
Tap: Trigger minimized lyrics (thumbnail lyrics) when they're not active and keep lyrics seeking when lyrics are shown
Double Tap: Directly enter fullscreen lyrics
Hold: Honestly could be used for anything. Like showing add to playlist pop-up, track info, lyrics options etc. In Musicolet it shows the option to view song artwork freely and replacing artwork with local pictures.

**Comment by aneesh1122** [comment]
> @NikunjKhangwal @aneesh1122 i agree that double tapping should enter fullscreen, or at least make it optional so the proposal:
> 
> * tap: does nothing (used to tap lyric line to jump to it)
> * double tap: could be "enter fullscreen" or "toggle lyrics"
> * long press: could be "enter fullscreen" or "toggle lyrics"
> * pinch/zoom in: scale font size

double tap: mini lyrics
long press: full screen lyrics. This should open fullscreen lyrics even when mini lyrics is enabled.

'pinch/zoom in' is not exactly seamless. I end up changing songs most of the times. This option is great but for guys like me who can't do it properly please add a option in the settings where I can manually enter the scaling %.

**Comment by aneesh1122** [comment]
> How about: Tap: Trigger minimized lyrics (thumbnail lyrics) when they're not active and keep lyrics seeking when lyrics are shown Double Tap: Directly enter fullscreen lyrics Hold: Honestly could be used for anything. Like showing add to playlist pop-up, track info, lyrics options etc. In Musicolet it shows the option to view song artwork freely and replacing artwork with local pictures.

how will you close the minilyrics?

**Comment by NikunjKhangwal** [comment]
> how will you close the minilyrics?

By tapping lyrics button on bottom right. Or if something additional can be implemented then another app i use close minilyrics by tapping on the edges of thumbnail and lyrics seeking happen only when tapping in middle.

**Comment by aneesh1122** [comment]
>  > how will you close the minilyrics?
> 
> By tapping lyrics button on bottom right. Or if something additional can be implemented then another app i use close minilyrics by tapping on the edges of thumbnail and lyrics seeking happen only when tapping in middle.

Well, the touching region is limited already right now. I can only touch the middle one and sometimes above and below the middle one.

The lyrics can be closed by touching an empty area. An area where there are no words.

**Comment by NikunjKhangwal** [comment]
> Well, the touching region is limited enough already. I can only touch the middle one and sometimes above and below the middle one.
> 
> The lyrics can be closed by touching an empty area. An area where there are no words.

I'm guessing that would be harder to implement but let see what dev have to say

**Comment by MSOB7YY** [comment]
i suggest removing lyrics from namida

**Comment by MSOB7YY** [comment]
yo just allowed entering fullscreen by long pressing. sadly allowing double tap will make normal tap delayed so i gave up on the whole gesture customizing thing, thats for lyrics.

so the current issue has a fix for the button & separate gesture to enter lyrics fullscreen. as for album artwork gestures, there is another request for that at #81

**Comment by aneesh1122** [comment]
> yo just allowed entering fullscreen by long pressing. sadly allowing double tap will make normal tap delayed so i gave up on the whole gesture customizing thing, thats for lyrics.
> 
> so the current issue has a fix for the button & separate gesture to enter lyrics fullscreen. as for album artwork gestures, there is another request for that at #81

Thanks man

**Comment by NikunjKhangwal** [comment]
Cool. Now i can make my artworks bigger freely. Thanks :)
