### ISSUE TITLE
[BUG] Selecting tracks that have duplicates

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#179]
Trying to manually remove duplicate tracks from a playlist. 

## Expected behaviour

When selecting a track, it should be individually highlighted and selected without its duplicate. 

## Current Behaviour

1- When selecting a track that has a duplicate, the duplicate is highlighted without it actually being selected. 

2- When unselecting the duplicate, the original's highlight gets removed without it being unselected. 

3- When reselecting the track,  the menu has a ghost track that doesn't exist, but it is being counted.

fixed/implemented?-->
## Steps to Reproduce

1. Have a playlist with duplicate tracks 

2. Select one of them by long pressing. The other one gets highlighted without being selected.

3. Tap on the duplicate to remove the highlight, and the highlight from the original gets removed.

4. Tap on the original to rehighlight it, which causes the menu to say 2 are selected while only one is selected.

5. Repeat steps 3 and 4 many times.

6. The menu will have ghost tracks that don't exist.

## Screenshots

![Screenshot_20240420_205251.png](https://github.com/namidaco/namida/assets/83415416/5661db3c-75f9-4a0c-bb9b-bd39260361e1)

## Possible Solution
<!--- u know coding? any suggestions? How could this be possibly 

I don't know coding, but it seems both of the tracks are treated as one. They should each have individual identifications.

Btw please fix the spelling and grammar of this template. My grammar check is killing me.

**Comment by MSOB7YY** [comment]
if you just want to remove duplicates, why not use this button?
playlist menu -> third button here
![image](https://github.com/namidaco/namida/assets/85245079/000c3de0-07b1-47b8-8c87-7ca680f3685f)


**however** i reproduced the bug, totally not the intented behavior. gonna fix the ghost tracks and push.

note that the behavior will not change, selecting a track will still highlight all the other duplicates as if they were selected too, its nonsense that one might want to select same track again

**Comment by MSOB7YY** [comment]
this was fixed in 07f457599a25f45b96bb885a20e9678e776fe798, u can use the [beta build](https://github.com/namidaco/namida/actions/runs/8775895763) if u wish. btw the ghost was a ui issue, otherwise the list would display all of the ones u selected
