### ISSUE TITLE
ADD LETTERS TO SCROLLER [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Sethkms** [namidaco/namida#180]
< !--- ce modèle est ** SEULEMENT** utilisé pour demander des fonctionsnalités, utiliser d'autres modèles pour d'autres éléments -->

**Votre exige de fonctionalité est-elle liée à un problème? Veuillez décrier.**
Une description claire et concise de ce qu'est le problème. Ex. Je suis tous frustré quand [...]
Non

**Décrivez la solution que vous aimeriez**

please add letters to the scroller pls it would be more practical I think

![Téléchargement de Screenshot_2024-04-20-22-38-46-
623_com.dywx.larkplayer-edit.jpg...]()

**Décrivez les alternatives que vous avez envisagées**
Une description claire et concise de toutes les solutions ou fonctions alternatives que vous envisagez.

**Contexte supplémentaire**
Ajoutez ici tout autre contexte ou capture d'écran sur la demande de fonctionalité.

**Applications**
Ajoutez toutes les autres applications/services connus qui font cela de la bonne manière

**Comment by MSOB7YY** [comment]
please update your issue in English

**Comment by MSOB7YY** [comment]
if u mean the a-z scrollbar, i was working on it but the case is different with namida, u get to customize which info to display on track tile, so adding support for each info will be real pain, we could just use track title always but that will not be helpful, also it will change how namida generally looks so i have decided to leave it for now, just scroll while looking at the tracks?
