### ISSUE TITLE
[BUG] Editing/updating tags and saving, playing this track it is still the old tag?

### ISSUE THREAD

**Issue by l300lvl** [namidaco/namida#181]
## Expected Behavior

the track/s tag should auto update after clicking save. instead you have to do a library refresh. this is confusing.
## Current Behavior

it remains the same in all parts of the player except "edit tag" until you go to index and refresh
## Steps to Reproduce

1. edit a tag and click save
2. go back to the player, i.e track, folder, album view
3. tag remains same as before tapping save
4. go to settings>indexer>tap refresh button. i would expect this to be somewhat automatic?

**Comment by l300lvl** [comment]
regardless, fabulous app. hands down my new fav. any chance itll ever make it to the play store?

**Comment by MSOB7YY** [comment]
i can't reproduce, i have tested this many times and it instantly updates the details, not sure what going wrong on ur side, can u provide a quick video and the logs?

here is what happens when u edit tags:

https://github.com/namidaco/namida/assets/85245079/faec2446-5e57-4b23-9121-87b287c0bdc9

**Comment by MSOB7YY** [comment]
also ty so much <333 play store is probably not possible, we got an yt client that supports downloading so lmao.. also the `manage_all_files` permission is quite hated by google so i dont think it will

**Comment by l300lvl** [comment]
> also ty so much <333 play store is probably not possible, we got an yt client that supports downloading so lmao.. also the `manage_all_files` permission is quite hated by google so i dont think it will

oh totally didnt think about that. dur. thx.


in response to the bug though, it only happened once so far, and i did not try to reproduce. i only edited one tag total, because it was not tagged previously. the player just took the file name as the track title. i still have the original file, but ill have to remove it and copy it over from my phone.

as you say this doesnt usually happen and i believe you, can you perhaps check with a track that has no metadata, and add metadata?

**Comment by MSOB7YY** [comment]
if it had the filename as track title (i.e: tried parsing file name to artist - title), then this means that the tags couldnt be extracted, and most probably will not be editable(?) cuz usually some of them are kinda corrupted

i checked with a track that has no tags, edited artist field, it was then updated in namida but not the actual file. if ur case is similar then probably nothing we can do about it. u better download from official source or use scripts like yt-dlp

**Comment by l300lvl** [comment]
got it. ya it's the only one I had actually dld, coincidentally from a different ytdl method... Usually I purchase/rip flac. I'll just convert and fix tags manually for anything like that. Thanks for explaining. Anyway of some kind of notification of corruptness, or do you know of any mac app that can check for that?

Closing.

**Comment by MSOB7YY** [comment]
usually it should report any error if failed, not sure what exactly happened in ur case since no video or logs. feel free to reopen in case ur issue was still not fixed 

[lib/ui/dialogs/edit_tags_dialog.dart._editSingleTrackTagsDialog](https://github.com/namidaco/namida/blob/07f457599a25f45b96bb885a20e9678e776fe798/lib/ui/dialogs/edit_tags_dialog.dart#L458-L468)](https://github.com/namidaco/namida/blob/07f457599a25f45b96bb885a20e9678e776fe798/lib/ui/dialogs/edit_tags_dialog.dart#L458-L468)

---

i dont use mac so idk sry, but with simple search i think `Music Tag Editor` on mac app store could do, no idea tho

**Comment by l300lvl** [comment]
https://drive.google.com/file/d/12f0HkrMEvo0l8upC2IeAa5fqEZhTuCt9/view?usp=drivesdk

https://drive.google.com/file/d/12ew1evoHF0umHRPC4M9YxOmb5vLyBLxQ/view?usp=drivesdk

Both logs I have, lmk when you get em?
