### ISSUE TITLE
[BUG] Audio loss when pausing and resuming

### ISSUE THREAD

**Issue by John-Gee** [namidaco/namida#184]
It seems whenever I turn off my buds and turn them back on I lose the ability to hear anything. I have to can the app and restart it to fix it. I haven't tried just stopping the current track though. This has happened with different buds/headsets and also nothing comes out of the speaker so it doesn't seen hardware related.

## Expected Behavior

On pressing play the sound should be heard like in other players.

## Current Behavior

No sound is heard.
## Steps to Reproduce

1. Listen to something
2. Turn off BT headset
3. Not sure if waiting is needed
4. Turn back on headset and let it reconnect
5. Press resume

## Logs

[logs_2.0.6_240409151.txt](https://github.com/namidaco/namida/files/15221831/logs_2.0.6_240409151.txt)

## Possible Solution

Edit: actually this just happened by pausing the audio but keeping the headset on and connected so no disconnection needed.

**Comment by MSOB7YY** [comment]
by checking the logs, it seems like a problem with A14/MIUI, make sure u downloaded the arm64 version not arm. i should also test more.
also does this happen with phone speakers/ wired headphones? or just Bluetooth earbuds?

---

for self: might be related to progaurd

```
release {
...
            // add this
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
```
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class androidx.lifecycle.DefaultLifecycleObserver
```

**Comment by John-Gee** [comment]
I believe I already used 64 but I reinstalled, no difference.
I've just tried with only the speakers and I didn't have the issue but maybe I didn't wait long enough, I'll retry later and reply.

Thank you!

**Comment by John-Gee** [comment]
OK I was able to have the same issue with just the speakers so it's not BT related.

**Comment by MSOB7YY** [comment]
@John-Gee i see, how much did u wait for tho? more than 5 minutes or less?

**Comment by John-Gee** [comment]
About 10 minutes I think between pausing and resuming.

Maybe I should play with the battery optimization stuff to see if it changes anything.

**Comment by John-Gee** [comment]
Putting the app in unrestricted battery mode didn't help here.

**Comment by MSOB7YY** [comment]
yo i tried reproducing on Android 14 Emulator but it just aint happening, paused for more than 10 minutes and with player in background and it still resumed normally. have u noticed a specific pattern? anyways i did what "might" be causing it, but can't test it. u can check [beta build](https://github.com/namidaco/namida/actions/runs/9086391722) to see if its fixed

**Comment by MSOB7YY** [comment]
@John-Gee is this still an issue with [**v3.8.5**](https://github.com/namidaco/namida/releases/tag/v3.8.5) ?

**Comment by MSOB7YY** [comment]
im assuming its no longer an issue, should close soon.
for reference the latest beta is v4.0.8 https://github.com/namidaco/namida-snapshots/releases/

**Comment by MSOB7YY** [comment]
quick update: 
just realized what caused the issue and fixed here hopefully https://github.com/MSOB7YY/just_audio/commit/41a49732cb9ef3f05b14e437a3f6cde930ad0a3b, pls wait the [new beta here](https://github.com/namidaco/namida-snapshots/releases) (v4.8.3+) in few days or less

**Comment by MSOB7YY** [comment]
v4.8.3 beta released https://github.com/namidaco/namida-snapshots/releases
