### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Saidsito4** [namidaco/namida#185]
Track/Album cover shown in notification.

other apps like Apple Music, Spotify and Tidal already do this. simply display the album or track cover on the notification instead of the app logo.

it wouldnt let me put pictures so ill put here a google docs link with my screenshots.

https://drive.google.com/drive/folders/1mDOr7z7jw2f4hpqISDB5-vRwkDSBE_2F

its really no biggie, but it would change the listening experience, at least for me.

thank you

**Comment by MSOB7YY** [comment]
the app logo only shows when **the track has no embedded artwork**, u gotta download music correctly or edit your artwork manually in track dialog -> edit tags.

other than that, there is a request for fetching artworks from online services (check #5), but this also would appear only while edit the track tags
