### ISSUE TITLE
[FEATURE REQUEST] Shuffle/Play placement

### ISSUE THREAD

**Issue by Saidsito4** [namidaco/namida#187]
is it possible to change the way the play and shuffle buttons are placed?

the way they are now, i feel its more intuitive to have the PLAY button as the main one instead of the shuffle.

![Screenshot_20240510_222553.jpg](https://github.com/namidaco/namida/assets/169318098/dd53c245-02de-471d-ad97-38cb5cf020d5)

![Screenshot_20240510_222846.jpg](https://github.com/namidaco/namida/assets/169318098/e4a40da5-36f6-4444-a9be-086c773f61b2)

here is my suggestion compared to the original.

but let me know what you think, in the end, im not a dev.

**Comment by Saidsito4** [comment]
i REALLY love your app, its so cool.

please continue to care for it. you are doing the lords work.

**Comment by MSOB7YY** [comment]
literally pressing the first track is the same as "play all".
by this, u can have 3 options: shuffle/play last/play all
while ur suggestions removes ability to shuffle, floating action button is a separate thing and for example i have it as a search button
(you can change the floating action button from extra settings)

**Comment by MSOB7YY** [comment]
also thansks a lot for loving it ;-; im not doing the lord work but u are surely doing the cutie work <33 i love namida too so dw
