### ISSUE TITLE
[QUESTION] Individual tracks saved as whole albums

### ISSUE THREAD

**Issue by Saidsito4** [namidaco/namida#190]
you're probably annoyed by me at this point, but i keep having questions (im dumb :<).

when i was in the process of downloading tracks for a playlist, i noticed all the songs saved as parts of the album theyre from (i.e. i downloaded the song Never Felt So Alone from Endings & Begins, and in the albums section, the whole E&B album showed up there.) and, having multiple 50 song playlists, those are a lot of albums,

is there any way i can save them as only tracks? (in the tracks tab, instead of the albums one)

i know this is usual, like this very thing would happen to me in apple music, but i was wondering if you maybe have a solution for me.

**Comment by MSOB7YY** [comment]
so usually, enabling this option from YouTube settings will put the channel uploader as the album, disabling it leaves it empty (Unknown Album)
![Screenshot_20240512-125452_Namida](https://github.com/namidaco/namida/assets/85245079/07c7bfff-5bb8-468e-b5d5-9624504d281f)

**Comment by MSOB7YY** [comment]
other than that, u can press the edit icon while downloading single/bulk and edit the tags from there

**Comment by MSOB7YY** [comment]
oh and u should make sure that "album identifiers" in indexer settings only has name/album artist. cuz having year too will separate the tracks into different albums
