### ISSUE TITLE
[BUG] Namida Deleted downloaded Video. 

### ISSUE THREAD

**Issue by 1YuvrajS** [namidaco/namida#193]
## Steps to Reproduce

1. Namida deleted my 10 videos previously downloaded video but I can't remember Name of Video.
2. I never know when updated or Cleared Data caused this happened, So Sad.

**Comment by MSOB7YY** [comment]
which videos? you downloaded as files from youtube? or it was auto fetched for ur local track or while just playing youtube?

obviously anything that is not downloaded manually, will only live inside app data as a cache, clearing it or uninstalling namida will clear the cached videos

if you downloaded them manually, then namida cannot delete these files unless u press "delete" and confirm from yt downloads page

**Comment by 1YuvrajS** [comment]
> which videos? you downloaded as files from youtube? or it was auto fetched for ur local track or while just playing youtube?
> 
> obviously anything that is not downloaded manually, will only live inside app data as a cache, clearing it or uninstalling namida will clear the cached videos
> 
> if you downloaded them manually, then namida cannot delete these files unless u press "delete" and confirm from yt downloads page

@MSOB7YY 
I already downloaded from YouTube to shareing to Namida to download video and it saved to Default directory Namida>Downloads...

**Comment by MSOB7YY** [comment]
in that case there is no way to delete them unless u manually do it from inside namida or from a file manager, did u do such thing?

**Comment by 1YuvrajS** [comment]
> in that case there is no way to delete them unless u manually do it from inside namida or from a file manager, did u do such thing?

@MSOB7YY 
1. I didn't touch any settings inside Namida.
2. I Uninstalled Namida app for Update - I don't know which Architecture I downloaded previously it cause me trouble for uninstalling and downloading new Version.
3. I cleared cach and data from System App info...

**Comment by MSOB7YY** [comment]
@1YuvrajS again, there is no way to automatically delete downloaded files, u need to give "manage all files permission" and manually press delete for each video separately from youtube download page.

maybe you had set different download location in the old version. since namida database was cleared, u can no longer access them from namida without backup, u gotta use a file manager or video player to access the folder and maybe send a screenshot

**Comment by 1YuvrajS** [comment]
> @1YuvrajS again, there is no way to automatically delete downloaded files, u need to give "manage all files permission" and manually press delete for each video separately from youtube download page.
> 
> maybe you had set different download location in the old version. since namida database was cleared, u can no longer access them from namida without backup, u gotta use a file manager or video player to access the folder and maybe send a screenshot 

@MSOB7YY 
I tried finding a files that I moved to Another folder and I started coming in my mind that the file was downloaded with Namida.

I forgotten for file was moved, not deleted by Namida. I Apologise to you.

**Comment by MSOB7YY** [comment]
@1YuvrajS yep as i said lmao, no worries
