### ISSUE TITLE
[FEATURE REQUEST] Bilingual lyrics, with the two languages displayed in separate lines(Edited)

### ISSUE THREAD

**Issue by darkduck9** [namidaco/namida#195]
Edited:correct lyrics have been updated.

**Is your feature request related to a problem? Please describe**
Pls support the display of bilingual lyrics. 
When there are two lyrics with the same timestamp, Namida can only display the latter one.

Lyrics format:
![06](https://github.com/namidaco/namida/assets/60059377/2ffe6042-772c-4df5-bee7-d83f5032e62b)

**Describe the solution you'd like**
 the lyric and its translation can be displayed in separate lines,the translation should not be highlight

**Describe alternatives you've considered**
just like the follow pic

**Additional context**
ESLyric✔️
![4](https://github.com/namidaco/namida/assets/60059377/e252d442-7a5a-4b89-9bb5-93ee1e1b9327) 
Namida❌
![12](https://github.com/namidaco/namida/assets/60059377/14b319d9-912f-45c5-8678-20390204c084)
(updated for test) [Keep You Mine - NOTD.zip](https://github.com/namidaco/namida/files/15360474/Keep.You.Mine.-.NOTD.zip)
**Apps**
foobar ESLyric plug-in https://github.com/ESLyric/release?tab=readme-ov-file
netease music web https://music.163.com/#/song?id=1381706037

**Comment by darkduck9** [comment]
I also found that Retro Music supports this feature. Embedding the lyric source might be difficult (but that's okay). I hope Namida can display embedded lyrics ![4](https://github.com/namidaco/namida/assets/60059377/f99c5859-296e-45c4-b4e5-732791686e0a)

**Comment by MSOB7YY** [comment]
I'm just tryna figure out how the second language is identified. looking at the lrc file it seems that it only has double space "`  `" but is it really that simple? can't seem to find info online too

**Comment by darkduck9** [comment]
![3](https://github.com/namidaco/namida/assets/60059377/b88bf00d-f519-41e2-add3-9b3583920268)

Honestly, I used the Music Tag software to batch edit audio tags and lyrics. It can retrieve information from various music platforms and modify it into a specified lyric format.Here is link:https://www.cnblogs.com/vinlxc/p/11347744.html,

Of course, using a double space " " is also a format that can separate the original text from the translation.
I think if  treat the earlier lyrics on the same timeline as the original text, and the later ones as the translation, 
it may be easier to implement the effect using code.

Sorry, the test file has been updated 2 weeks ago. Please download it again.

**Comment by MSOB7YY** [comment]
i see, it makes sense now that translation line has same timestamp as original. alr will eventually implement it. just curious if double space is still a valid format? or if there are more alternatives to these two? thanks for the detailed request and sample files tho

**Comment by darkduck9** [comment]
![8](https://github.com/namidaco/namida/assets/60059377/50247c5e-44a3-436c-ba5f-73367a850864)
If you choose the first format in the image, you can customize the delimiter between the original text and the translation.  As far as I know, only NetEase (source 163) uses the double space " " format.

**Comment by darkduck9** [comment]
I'm not sure if you can download Music Tag from the original link if you're in another country.

 If you need it, here's the link and the extraction code: www.coolapk.com, https://mega.nz/file/HIxzAYoY#eEL6MQBcPFfOYUT8IqF53S8myT1yaw1DcJ_zR7qiU1s

**Comment by MSOB7YY** [comment]
hey, just finished working on this now. bilinguals lyrics will now be supported if they follow one of these format

- double space: `[00:06.87]Yes we started a fire, now the bedroom is burning  我们点燃了一场火，现在卧室正燃着熊熊大火`
- semicolon: `[00:13.99]'Cause we're both saying things that we're gonna regret when;我们总会说一些令人后悔的事`
- this thing | : `[00:19.16]Every word's too loud|每个字都是那么刺耳`
- just normal 2 lined with the same timestamp: 
```lrc
[00:21.12]We gotta slow, slow, slow down
[00:21.12]我们只需要冷静下来
```

---
done in https://github.com/namidaco/namida/commit/4a71dd42738b74eadbe37723b691fed04fb42dea (v4.0.55) & https://github.com/MSOB7YY/dart_lrc/commit/d95622bed067877cbe135a3e7e6ab784b502033a, u may check it in beta from here https://github.com/namidaco/namida-snapshots/releases when its released

thanks for reporting & for providing a test stuff! much luvv <33

**Comment by VerySweetBread** [comment]
IMHO, 
- Double spaces might be a TYPO
- semicolons might be in a regular text ([ex](https://russian.stackexchange.com/questions/386/when-is-semicolon-used-in-russian))
- Pipes and double timestamp are good options

**Comment by MSOB7YY** [comment]
@VerySweetBread always russian ruining the fun

- the semicolon are in english too so uhh should we just remove it?
- double spaces typo may be a sign to fix ur lyrics. there are more chances of it being multi-lang than being a typo

**Comment by MSOB7YY** [comment]
@darkduck9 @VerySweetBread just removed `;` as splitter https://github.com/MSOB7YY/dart_lrc/commit/3a9fa8112d2a3ac5ecd55d73f94f2ef2b2ad9619

now the supported are only `|`, `  ` & normal 2 separate lines

**Comment by darkduck9** [comment]
New feature worked well,thx for your work
