### ISSUE TITLE
[QUESTION] Dependency Resolution Failing

### ISSUE THREAD

**Issue by acharya8848** [namidaco/namida#196]
Hi:
I want to add support for connecting to and downloading songs from a [Jellyfin](https://jellyfin.org/) instance.
I was trying to get set up for development when I ran into a repository not found error.
It seems like the git repository at `https://github.com/MSOB7YY/known_extents_listview_fancy` is private.
As it stands right now, I can't resolve dependencies to start development. I wonder if making the repo public is possible or something else can be done.
I branched off of the latest v2.0.6 release.
Thank you

**Comment by MSOB7YY** [comment]
hello! appreciate your commitment, but as referred many times earlier, code is not fully open source, explained why also, check #37 for details

apologize for that really, this may change in future. also check similar requests for navidrome at
#91 & #153
