### ISSUE TITLE
Request for a Widget

### ISSUE THREAD

**Issue by faizan123455** [namidaco/namida#197]
I would like to request a widget for the player. It's pretty annoying to open the app everytime. As an app focused so much on aesthetics and customisation, there should be a widget. Please add it as soon as possible 🙏

**Comment by MSOB7YY** [comment]
not that easy tho, this was requested many times and is a duplicate of #168, progress can be noticed on [home widgets branch](https://github.com/namidaco/namida/tree/home-widgets)
