### ISSUE TITLE
Feature Request (Eventually) - Spotify download support

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#20]
The Spotify Web API is available to everybody and free, so if (and probably big if) possible, I'd love to eventually see Spotify downloading locally.

**Comment by MSOB7YY** [comment]
spotify sucks

**Comment by Red6785** [comment]
I'm aware, but YouTube doesn't have everything, and neither does Spotify.
Combining the two allows for a greater selection.

**Comment by MSOB7YY** [comment]
it would be good actually but lmao the amount of effort needed is too much
there is also ytm support
i *may* work on it only if got nothing more to add, but thanks for the suggestion

**Comment by Red6785** [comment]
Closing for a few reasons:
Spotify audio files are somewhat low quality
Anything not found on YouTube or YouTube Music is likely found on SoundCloud or BandCamp
Looking into it, it seems no direct downloaders from Spotify have been made, and that all that currently exist search for the video file from one of the aforementioned sources.

**Comment by MSOB7YY** [comment]
well quite the big help u gave, i wasnt considering adding it any soon tho
~also u just proved how spotify sucks~

**Comment by Red6785** [comment]
🤓
