### ISSUE TITLE
some lyrics are unreadable

### ISSUE THREAD

**Issue by PigeonCoding** [namidaco/namida#200]
so basically when displaying some lyrics instead of showing the characters the app will show random unicode characters (i have tested it with some japanese songs and an indian song)

## Expected Behavior

show the lyrics with the correct character

## Current Behavior

show instead random unicode charatcers

## Steps to Reproduce

1.play a song and activate the lyrics
2.if you are unlucky (for me it's most of my library) it will not display the correct characters

## Screenshots

![Screenshot_2024-05-19-09-55-43-617_com msob7y namida](https://github.com/namidaco/namida/assets/77279028/6ff809cf-f0f3-4941-a8fa-6c475c921795)

## Possible Solution

it's possibly an issue with the parser or the source since some songs in Japanese have the correct characters while others don't but son;t quote me on that i haven't read the source code it's just a guess

**Comment by MSOB7YY** [comment]
thats a duplicate of https://github.com/namidaco/namida/issues/188#issuecomment-2111170448, it was already fixed in beta and next release gon be in few days. nice guess tho was kinda close lmao

**Comment by PigeonCoding** [comment]
sorry didn't see that it was a duplicate will just wait for next release

Thank you for your work
