### ISSUE TITLE
[BUG] Namida keeps crashing

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#205]
Namida keeps crashing after the latest update.
## Expected Behavior

It should ve crashed just before Indexing!! OR REINDEXING!!!
## Current Behavior

Umm... I don't know.
## Steps to Reproduce

1. Download namida-v2.5.6-armeabi-v7a.apk
2. Then install it
3. Try open
4. Keep trying
5. *Kill me*

## Screenshots

> 
## Logs

How??
## Possible Solution

May be when you fix YouTube Comments (WITH REPLIES), make GUI better going and add video player (as you promised).

**Comment by MSOB7YY** [comment]
why is bro mentally killing me ☠️☠️ uhmm have u ever once in a random day.. decided to download arm64 version and not v7a ?

**Comment by MSOB7YY** [comment]
my bad the didn't notice the armabi-v7a wasn't probably built. gotta rebuild and upload it again
