### ISSUE TITLE
Some song lyrics in Korean aren't displayed correctly 

### ISSUE THREAD

**Issue by Lionharth** [namidaco/namida#210]
I am not sure why but about half of my song's song lyrics that are in korea doesn't display correctly. Do you think it's something weird with the file or the app? Maybe they use some other type of character encoding (I don't know much about this) 

![Screenshot_20240526_225445.jpg](https://github.com/namidaco/namida/assets/90109349/62b9a019-ce1b-4a3d-a485-1fabf5e312ab)

![Screenshot_20240526_225634.jpg](https://github.com/namidaco/namida/assets/90109349/702de221-c7ca-405e-b3cf-143647ae08e2)

![Screenshot_20240526_225653.jpg](https://github.com/namidaco/namida/assets/90109349/4aafda97-b2a9-45c8-a86a-c7567890828f)

**Comment by MSOB7YY** [comment]
are u on v2.5.6? 
![Screenshot_20240526-231145_Namida](https://github.com/namidaco/namida/assets/85245079/1a5b655e-757a-427e-8131-510d982d14b1)

**Comment by Lionharth** [comment]
Yes, I am

**Comment by MSOB7YY** [comment]
@Lionharth probably your file is still from an old version (which incorrectly parses and save lyrics file). what u can do is long press these tracks -> open menu -> advanced -> clear -> clear lyrics

then let it fetch again, it should work properly

**Comment by MSOB7YY** [comment]
otherwise if these lyrics are already embedded, u may want to send me a sample file
