### ISSUE TITLE
[FEATURE REQUEST] Download function

### ISSUE THREAD

**Issue by Ehab-d** [namidaco/namida#216]
**Is your feature request related to a problem? Please describe.**
Sometimes I go away and I can't listen to the content offline.

**Describe the solution you'd like**
Add a download button so that the content is available offline.

**Describe alternatives you've considered**

**Apps**
I see that InnerTune implements this feature very well.

**Comment by MSOB7YY** [comment]
have u ever seen the download icon under the video ?

**Comment by MSOB7YY** [comment]
not to mention the videos/audios played are automatically cached so no need to download if u will listen on namida. bulk downloads are also supported for playlists/queues/ channels etc..
