### ISSUE TITLE
[BUG] blank area when removing track from queue 

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#219]
Removing a track from the queue leaves its place empty 
## Expected Behavior

The track goes away when dismissing it without leaving a trace
## Current Behavior

The place of the track stays empty

## Steps to Reproduce

1. Start a queue 
2.remove one of the tracks by swiping it away
3.
4.

**Comment by MSOB7YY** [comment]
this probably caused by new flutter version mixed with own optimizations to prevent unnecessary rebuilds

anyways i already discovered it and is fixed in local repo, just need to do many refactoring before i push the changes so yah

**Comment by MSOB7YY** [comment]
forgot to mention it's fixed in beta
