### ISSUE TITLE
Bug - Reindexing hides my tracks

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#22]
This error still happens even on the newest version.

**Comment by Red6785** [comment]
Hides whatever playlist you are currently listening to. I suggest attempting to index forces you to stop listening to something.

**Comment by MSOB7YY** [comment]
re-indexing is meant to rebuild the library from scratch, so it will obviously clear all tracks and start all over

if you just want to check for newly added/deleted or if u added/removed a folder, just do a refresh

did i understand this correctly?

**Comment by Red6785** [comment]
Whenever I reindex, it hides the already existing songs of whatever playlist I am listening too and attempting to refresh does not work. You have to force-stop the app then refresh.

**Comment by MSOB7YY** [comment]
this should be fixed in https://github.com/namidaco/namida/commit/5079801572474284493ff3e4318108d3c6094e25 and is available with v1.8.5
