### ISSUE TITLE
[FEATURE REQUEST] Add adaptive icons to Namida

### ISSUE THREAD

**Issue by septsea** [namidaco/namida#220]
**Is your feature request related to a problem? Please describe.**
Namida does not seem to have adaptive icons. 

**Describe the solution you'd like**
Here is information about adaptive icons: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive .

**Describe alternatives you've considered**
Use Namida as it is and wait for the implementation of the feature silently.

**Additional context**
As is shown in the screenshot, Namida does not seem to have adaptive icons as many other apps do.
![Screenshot_20240604-095312_crDroid Home](https://github.com/namidaco/namida/assets/57337516/af9ead00-0eb8-4483-9d90-3583593f3d45)

**Apps**
Musicolet does it in the manner which I suggest in the request.

**Comment by MSOB7YY** [comment]
waiting for your icon submission 🥰 (no ur NOT gonna wait in silence 🫵😹😹👎)

**Comment by septsea** [comment]
@MSOB7YY I am sorry that I do not know how to design such adaptive icons.

**Comment by MSOB7YY** [comment]
@septsea no worries, i don't know too

**Comment by saltsoftdrink** [comment]
> @septsea no worries, i don't know too

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by MSOB7YY** [comment]
forgot to mention that was added in https://github.com/namidaco/namida/commit/d3d32e086515b969a3e26b177811d74f2e3f0199

available currently [in beta](https://github.com/namidaco/namida-snapshots/releases)
