### ISSUE TITLE
[FEATURE REQUEST] more rows in 

### ISSUE THREAD

**Issue by nuser222** [namidaco/namida#221]
**Is your feature request related to a problem? Please describe.**
When you got to Artists and then click on one in the next screen the albums are only shown in a single row. So if you have a lot of albums from a single artist you need to do side scrolling which I don't like

**Describe the solution you'd like**
give an option in settings to have more rows 

![a2sk](https://github.com/namidaco/namida/assets/169761159/ef70e8e5-129d-41b2-89d6-d2c8d5d0d397)

**Comment by nuser222** [comment]
![a2sk](https://github.com/namidaco/namida/assets/169761159/bcc9f290-43fb-43aa-8743-980ca09ec59a)

**Comment by MSOB7YY** [comment]
no sorry, the album rows is really just extra. and its already taking almost 30% of the available screen. more than this is not an option to consider
