### ISSUE TITLE
[FEATURE REQUEST] Long press favourites button to "Add to playlist"

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#223]
So yeah, another random request. I think it would be easier to use then going into 3 dots menu. Also better for one hand usage.

**Comment by MSOB7YY** [comment]
are u talking about the small heart icon in the track tile?

**Comment by NikunjKhangwal** [comment]
Is this what we call track tile? Then yes

![IMG_20240614_091603](https://github.com/namidaco/namida/assets/99175083/044e7800-9603-4a44-a780-7d87863fb91c)

**Comment by MSOB7YY** [comment]
added with 0647e835a2e155ed107e320f9b290e771633c6ce, thank u for the suggestion ^^

**Comment by NikunjKhangwal** [comment]
Based & Thanks
![th (1)](https://github.com/namidaco/namida/assets/99175083/5df77bcb-f339-4d9e-9b70-91e114c7dabd)

**Comment by MSOB7YY** [comment]
@NikunjKhangwal IM STEALING THAT

**Comment by NikunjKhangwal** [comment]
It's all urs ;)

**Comment by MSOB7YY** [comment]
just a side note in v5.5.3+ u can also set artwork gestures to do the same thing (in customization settings -> artwork gestures)
<img width="404" height="213" alt="Image" src="https://github.com/user-attachments/assets/affaff61-8a49-4f48-ba59-cb352e346680" />
