### ISSUE TITLE
My search function is broken somehow?

### ISSUE THREAD

**Issue by hernglchoi** [namidaco/namida#229]
nothing shows up when I search in the youtube tab

## Screenshots

https://github.com/namidaco/namida/assets/161813598/086b4ea5-f54b-40ad-8c6c-164fda71b6c0
## Logs

[logs_clean_2.5.6_240522118.txt](https://github.com/user-attachments/files/15888299/logs_clean_2.5.6_240522118.txt)
[logs_2.5.6_240522118.txt](https://github.com/user-attachments/files/15888300/logs_2.5.6_240522118.txt)

**Comment by MSOB7YY** [comment]
[in the process of migrating to a new client](#227). some ppl had the same issue before tho

**Comment by MSOB7YY** [comment]
my bad didnt check the video before replying. the button u pressed only closes the search menu. u gotta press "enter" in your keyboard
