### ISSUE TITLE
[ISSUE] app using 400mb

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#231]
The app uses too much storage. I mean, if it's all necessary, then no problem. But I don't think a music player needs 400mb.

![Screenshot_20240623_021749_Settings.png](https://github.com/namidaco/namida/assets/83415416/1845796a-71d5-4af2-86d7-1db65fa0fdf6)

**Comment by MSOB7YY** [comment]
go to settings -> advanced, from there u will find what's taking up storage. usually it will be your music thumbnail extracted and cached, this allows for faster display and showing of original artwork.
you can clear thumbnail cache, but then it will try to extract from media store (which is slower, not original quality and more cpu consuming). also opening an image (from track info dialog) or viewing it in expanded miniplayer will be the only ways to extract full image qualities and cache them again.
![Screenshot_20240623-012444_Namida](https://github.com/namidaco/namida/assets/85245079/e533d9d0-7270-4adc-91a7-554f7354db65)
(note that max image cache is only for youtube thumbnails)

**Comment by z9xx7o0** [comment]
Oh, okay. I thought there was something wrong. I didn't think just 500 tracks' thumbnails would be that much.

**Comment by MSOB7YY** [comment]
@z9xx7o0 if its critical u could try compressing these images using the compress option in advanced settings. the result will be in `internal storage/Namida/Compressed` u would move them manually to artwork cache in app data folder

other than that yeah its pretty normal
