### ISSUE TITLE
[ISSUE] Incorrect Date For Recently added tracks

### ISSUE THREAD

**Issue by lewismalili** [namidaco/namida#232]
![Screenshot_20240624-110631.jpg](https://github.com/namidaco/namida/assets/173634815/1626dbf3-6b04-46b0-ab82-7ab8e5a0f55d)

**Comment by MSOB7YY** [comment]
i remember preventing using of 1970 as date time if extraction failed. make sure you are on v2.5.6 AND make sure u did a re-index

**Comment by lewismalili** [comment]
I've just followed all the instructions but the problem is still there. Let me try reinstalling.

**Comment by MSOB7YY** [comment]
still an issue on v4.0.8? https://github.com/namidaco/namida-snapshots/releases/
