### ISSUE TITLE
Bug - Incorrect lyrics being fetched.

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#24]
It fetched the lyrics for Roger Waters' "4:39AM (For the First Time Today, Part 2)" instead of his Time - Dark Side of the Moon Redux. 
![Screenshot_20231016_160426](https://github.com/namidaco/namida/assets/88458171/da75f866-45af-4c3a-8898-c8d78d92a81d)
![Screenshot_20231016_160550_Firefox](https://github.com/namidaco/namida/assets/88458171/938a2e5a-dc7c-45c9-8494-a9564d023942)

**Comment by MSOB7YY** [comment]
the database first search result is always used, if the database decided that this may be a match then it should be, i can prevent using the result unless the title is the same but that wont be efficient and wont cover all cases, please search manually in such cases

**Comment by Red6785** [comment]
Well here's the thing- searching Time, Dark Side of the Moon Redux, and Roger Waters together only has one result, the right one. This only happens if you don't search the album name.

**Comment by MSOB7YY** [comment]
should be fixed with e85cd6048cf3d03d46a65e4a03b4e04db29e9a64, thanks for reporting.
