### ISSUE TITLE
[ISSUE] the app yt or even the function non of that works properly.

### ISSUE THREAD

**Issue by heyjumanji** [namidaco/namida#240]

**Comment by MSOB7YY** [comment]
idk what youtube did recently that might broke the old client. currently in beta a new client is implemented and working fine

**Comment by MSOB7YY** [comment]
quoted from #250
> thats due to google disabling feed without a watch history (which requires a browser session or account).
about the search im not so sure, but the new client is working fine [in beta](https://github.com/namidaco/namida-snapshots/releases), the login part is almost done too so the feed will work along with it, track it at #227
