### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Unknownlyy** [namidaco/namida#242]
The youtube player is not working the video just doesn't play and can't download any music 

## Expected Behavior

The video shall be played the download shall happen.

## Current Behavior

The video stops at 0:00 doesn't play, the download button ain't working 

## Steps to Reproduce

1. 
2.
3.
4.

## Screenshots

![Screenshot_2024-06-26-21-46-17-56_efbfb0790a8187cbd43560835da1b509.jpg](https://github.com/namidaco/namida/assets/145676481/69dcaf2a-b585-4168-bc87-e30589433900)

![Screenshot_2024-06-26-21-46-24-84_efbfb0790a8187cbd43560835da1b509.jpg](https://github.com/namidaco/namida/assets/145676481/cae55f62-9ea5-48a3-ae0d-6b995a2fb39a)

**Comment by MSOB7YY** [comment]
duplicate of #240, damn the current client seems so cooked. in beta everything is working fine
also nice music 🎀
