### ISSUE TITLE
[FEATURE REQUEST] Ability To Loop Local Videos 

### ISSUE THREAD

**Issue by sujitFYI** [namidaco/namida#244]
**Is your feature request related to a problem? Please describe.**
It'll be good if a local video get loop instead of leaving black or last video frame stuck throughout the song. 

**Describe the solution you'd like**
Looping video will be good option like Spotify, Apple Music Canvases.

**Describe alternatives you've considered**

**Additional context**

**Apps**

**Comment by MSOB7YY** [comment]
wait that should be already a thing, is it not working? what's the duration of video and the track?

**Comment by sujitFYI** [comment]
> wait that should be already a thing, is it not working? what's the duration of video and the track?

Yup it sometimes work sometimes not 

Audio Duration- 4:55
Video - 1:00

Audio: Ramin Djawadi - Pacific Rim (feat. Tom Morello).flac

Attached Behaviour Video 

Sorry can't Produce video due to #246 issue

**Comment by MSOB7YY** [comment]
as pointed out in ur other issue, looping videos is also working perfectly.. there must be a separate issue that prevents ur video playback generally https://github.com/namidaco/namida/issues/246#issuecomment-2198533570
