### ISSUE TITLE
[BUG] Naminda is not able to detect or display local videos on my device despite granting all required permissions and ensuring the setup is correct.

### ISSUE THREAD

**Issue by sujitFYI** [namidaco/namida#246]
Naminda is not able to detect or display local videos on my device despite granting all required permissions and ensuring the setup is correct.

## Expected Behavior
Naminda should display local videos stored on the device.

## Current Behavior
No local videos are found or displayed in the app.

## Steps to Reproduce
1.Same name Audio and video in Same folder
2. Video playback on, Video Source Local, Video Matching Auto
3. Open the Audio file 
4.You'll see question mark beside video [Video•?] 

Usually It should Be Video • Resolution bitrate

## Screenshots
![Screenshot](https://github.com/namidaco/namida/assets/105970492/261ef87b-61c4-401a-a800-3f5afe188070)
![Screenshot](https://github.com/namidaco/namida/assets/105970492/b16826c8-e28f-4ebb-8751-9b6409399682)
![Screenshot](https://github.com/namidaco/namida/assets/105970492/374751af-c693-4bd3-b267-499595576d84)

## Logs
[logs_clean_2.5.6_240522118.txt](https://github.com/user-attachments/files/16018230/logs_clean_2.5.6_240522118.txt)
[logs_tagger_2.5.6_240522118.txt](https://github.com/user-attachments/files/16018231/logs_tagger_2.5.6_240522118.txt)
[logs_2.5.6_240522118.txt](https://github.com/user-attachments/files/16018232/logs_2.5.6_240522118.txt)

## Possible Solution
Nope I don't know coding but the solution would be same as how its designed to work.

## Attached File to Produce Issue 
Actually its same case on all the songs but still here

https://github.com/namidaco/namida/assets/105970492/ede90fda-ce80-4e74-8ee1-57c5f582c560

Audio- Copyright Content

**Comment by MSOB7YY** [comment]
thanks for the detailed report, just to be sure, the folder "Music/Ayugram" is surely inside indexer folders right? also u might want to do `re-scan videos` from `advanced settings`, have u tried it?

**Comment by sujitFYI** [comment]
Yes, the folder ayugram is my main Audio folder i keep all my songs collection in it also all video with same name are in same folder so nothing about indexer issue.

I've already tried rescan video, cache deleting etc before posting this issue.

**Comment by MSOB7YY** [comment]
![Screenshot_20240630-131809_Namida](https://github.com/namidaco/namida/assets/85245079/1673a7b7-132d-405e-be01-ed1289591446)

i tried local video playback after a while and it worked just fine

i tested your video and it worked perfectly too, both music and video doesn't have to be in the same folder, but the folder HAS to be inside indexer folders, here is what i did


https://github.com/namidaco/namida/assets/85245079/f4e38206-e107-41e6-b01e-02a5ed6ac326

**Comment by MSOB7YY** [comment]
just to be sure, playing a YouTube video works fine right? (if it doesnt load, u should try it at [latest beta here](https://github.com/namidaco/namida-snapshots/releases))

**Comment by sujitFYI** [comment]
> playing a YouTube video works fine right?

I haven't checked that yet :[

BTW i installed beta that's same story. Here's new video how my video loop isn't working :/ 
[Telegram video Link In Naminda Because Of GIT File size limit](https://t.me/c/1697858359/16639)

**Comment by sujitFYI** [comment]
@MSOB7YY Just For record did you get my Last comment? 😅 Also that Link is in your naminda channel nothing goofy.

**Comment by MSOB7YY** [comment]
yeah i did and i honestly got no clue what might have gone wrong. i tried it many times on my phone (and showed you) and works fine for other ppl too so i really dont know..

**Comment by sujitFYI** [comment]
> yeah i did and i honestly got no clue what might have gone wrong. i tried it many times on my phone (and showed you) and works fine for other ppl too so i really dont know..

Oo, I'll Also try to from my end. Thankyou

**Comment by sujitFYI** [comment]
@RGMBOY See me screenshot section again

**Comment by MSOB7YY** [comment]
[there was a vary silly bug](https://t.me/namida_chat/32005) which might have caused this, can u try the v4.0.5 from here? https://github.com/namidaco/namida-snapshots/releases

**Comment by sujitFYI** [comment]
Yup videos are now working fine but my Spiderman loop is still a issue 😕 no loop.

**Comment by MSOB7YY** [comment]
@sujitFYI fixed with https://github.com/MSOB7YY/just_audio/commit/55356d71bb6672133d48b86f57982ee049928af1

u can use v4.0.8 from here https://github.com/namidaco/namida-snapshots/releases/
