### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#248]
This is a small bug that is not really important.

Steps to reproduce:
1. Go into a queue
2. Hold a track from the 3 lines on the right.
3. Press the trash bin at the bottom.
4. Fiddle around, go to different pages. I found skipping to the next track works the most.
5. The track just appears on the screen, then disappears.

If the track doesn't appear, try doing it again with a different one.

If you keep doing this, the tracks will stack.

you can interact with it normally.

**Comment by MSOB7YY** [comment]
i think this is already fixed with the new implementation (available in beta) 
tried reproducing just in case and everything working fine

thanks for noticing and reporting tho
