### ISSUE TITLE
Bug/Oversight - Lyrics screen does not update when song ends

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#25]
![Screenshot_20231016_163610](https://github.com/namidaco/namida/assets/88458171/2f88cf62-437d-47b4-b027-596656add354)
This is the lyrics screen for the last song.

**Comment by MSOB7YY** [comment]
i made sure are updated properly before releasing, gonna investigate

**Comment by MSOB7YY** [comment]
closed as fixed in 906e10ff0b54433bf19560ebf26c2edd91835744, thanks for the report.

**Comment by Red6785** [comment]
Oops! Looks like we're back again.

**Comment by MSOB7YY** [comment]
I was able to reproduce on v1.5.4, the whole screen might need a refactor.. lets see

**Comment by MSOB7YY** [comment]
should be fixed now with d344461af32c59c757432f7519a0009b9fbd0189, again thanks for reporting!
