### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by abdpro300** [namidaco/namida#250]
nothing from YouTube or YouTube search is loading 

## Expected Behavior
for the YouTube section music/videos to load in the app

## Current Behavior
it just loads infinitely 

## Steps to Reproduce

1.open the app on the Samsung a54
2.check it's version 2.5.6
3.go to YouTube library or search for a YouTube music video 
4.nothing loads 

## Logs

{
  "#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)\n#1      _Directory.listSync (dart:io/directory_impl.dart:228)\n#2      _cleanOldLogs (package:namida/main.dart:194)\n#3      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)\n#4      _RemoteRunner._run (dart:isolate:1090)\n#5      _RemoteRunner._remoteExecute (dart:isolate:1084)\n#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)\n#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)\n": {
    "PathNotFoundException: Directory listing failed, path = '/storage/emulated/0/Android/data/com.msob7y.namida/files/Logs/' (OS Error: No such file or directory, errno = 2) => PathNotFoundException": 1
  },
  "#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721)\n#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914)\n#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)\n#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299)\n#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)\n#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2480)\n#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2923)\n#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2928)\n#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2783)\n#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2625)\n#10     NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:104)\n#11     NetworkImage.loadImage (package:flutter/src/painting/_network_image_io.dart:66)\n#12     ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:520)\n#13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:377)\n#14     ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:517)\n#15     ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:104)\n#16     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:366)\n#17     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:479)\n#18     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43)\n#19     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:476)\n#20     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:363)\n#21     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1111)\n#22     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1061)\n#23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5636)\n#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#37     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#56     SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:295)\n#57     SlottedRenderObjectElement.mount (package:flutter/src/widgets/slotted_render_object_widget.dart:249)\n#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#84     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#94     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#99     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#117    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#125    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#134    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#140    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#145    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#161    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#166    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#173    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#175    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#180    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#184    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#186    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#187    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#188    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#189    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#194    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#200    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#205    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)\n#206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#209    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)\n#210    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#212    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)\n#213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#217    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#218    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)\n#223    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)\n#224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)\n#225    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)\n#226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)\n#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)\n#228    SingleChildRenderObjectElement.mount (

## Possible Solution
i have no idea and i have tried using multiple VPNs and VPN locations

**Comment by MSOB7YY** [comment]
thats due to google disabling feed without a watch history (which requires a browser session or account).
about the search im not so sure, but the new client is working fine [in beta](https://github.com/namidaco/namida-snapshots/releases), the login part is almost done too so the feed will work along with it, track it at #227
