### ISSUE TITLE
[FEATURE REQUEST] :Display  Artwork on lockscreen 

### ISSUE THREAD

**Issue by yash9574** [namidaco/namida#251]
I would like to request a feature to display the album artwork on the lock screen while using the app Currently, there is an option for this "Display  artwork on lockscreen" , but it does not support newer Android version (or atleast on my phone : Android 11)  google removed that back then

**Comment by MSOB7YY** [comment]
android 11 here and is working fine using custom rom. if google removed it from your device then im afraid i can do nothing. any other players that bypass this?
