### ISSUE TITLE
[ISSUE] Slow YT video caching/loading

### ISSUE THREAD

**Issue by mattiamazzari** [namidaco/namida#252]
As already discussed, there are caching issues for the videos, which take a bit of time to load. Since I already know that a new caching strategy is in development (like audio only), I just explicitly open the issue until the new version will be released

## Expected Behavior
The videos should load without interruptions

## Current Version
v2.8.6-beta

**Comment by MSOB7YY** [comment]
i kinda got away from that lmao, thank u for opening a separate issue to remind me, will finish login and some other small stuff and return back to this

**Comment by MSOB7YY** [comment]
as mentioned, this is now done and can be checked in beta v3.5.9 https://github.com/namidaco/namida-snapshots/releases/
