### ISSUE TITLE
[FEATURE REQUEST] landscape mode and delete button in the three dot menu

### ISSUE THREAD

**Issue by Rushikesh321** [namidaco/namida#255]
I really love your app, it's perfect in almost every way but two.

This app has everything but just two things and i believe(just my opinion) that these two features are basic for every music player, which is a delete button and the landscape mode.

It feels kind of waste to not have landscape mode in this almost perfect music player.

And it's kind of hassle to delete songs from the file manager. It would save time and energy if you add delete button in the three dot menu.

I hope you get what I'm trying to say here.
Thanks 👍

**Comment by MSOB7YY** [comment]
thank you so much for loving it, ur perfect too <3

as for the landscape, [there is already an issue for that #202](#202), although as mentioned having a landscape will require many redesign considerations, especially for the miniplayer which is real pain to work with

for the delete option, its not so hard so add it, but i personally kept my thinking that a music player shouldn't touch user files, but yeah kind of gave up and will eventually add it, the main issue tracking is here tho #66 so im gonna closes this

thank u again for ur requests ^^
