### ISSUE TITLE
[BUG] Black screen / video cover after going back 10s

### ISSUE THREAD

**Issue by mattiamazzari** [namidaco/namida#258]
While playing a video, after a while if we go back 10 seconds the video disappears, we are able to listen to only the audio and it displays either the cover of the video or black screen

## Expected Behavior
It should continue displaying the video

## Current Behavior
The player becomes black or shows the cover, while still playing the audio

## Steps to Reproduce
1. Watch a video for more than 2-3 minutes
2. Go back 10 seconds

## Logs
[logs_2.9.0-beta_240702229.txt](https://github.com/user-attachments/files/16113404/logs_2.9.0-beta_240702229.txt)
[logs_clean_2.9.0-beta_240702229.txt](https://github.com/user-attachments/files/16113405/logs_clean_2.9.0-beta_240702229.txt)

**Comment by MSOB7YY** [comment]
this will also be linked to #252, internally when an issue happens with the source, it falls back to audio immediately

**Comment by MSOB7YY** [comment]
also ur logs indicate that "manage all files" permission is not given, downloading from yt will not be possible

**Comment by MSOB7YY** [comment]
can you confirm wether this is still an issue or not in beta v3.7.0? https://github.com/namidaco/namida-snapshots/releases/

i had no such issues since [the new video implementation](0d15636c039ad7941b931cd452dcab443228183f)
