### ISSUE TITLE
[BUG] "play after" dissappears after the center of the queue 

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#259]
After you reach the center of the queue, the play after dissappears.

**Comment by MSOB7YY** [comment]
play after button main purpose is to put smth after the latest added item, while remembering their position. when u keep playing until u reach the "latest added item" this means that play after is now same as play next. i don't see any issue here unless im missing smth?

**Comment by z9xx7o0** [comment]
I don't get it. Is the center of the queue considered the latest added item? Isn't the last track the latest added item?

**Comment by MSOB7YY** [comment]
can you provide reproducable steps

**Comment by z9xx7o0** [comment]
1. Start a queue 
2. Go to a track after the center of the queue (be on the track)
3. Try to use the play after on any track, and it won't be there

**Comment by MSOB7YY** [comment]
you really missed the purpose of that button. u need to use "play next" or "play last" button before "play after" becomes available.

gonna close, if i somehow still got it wrong, please provide a video cuz the steps leads to normal behavior

**Comment by z9xx7o0** [comment]
@MSOB7YY , I'm sorry, I now feel really stupid after this. I thought that the play after inserts the track in the middle of the queue because of the icon, and that the first time I tried it, I used the play next while in the middle of the queue, then went back to the beginning.

**Comment by MSOB7YY** [comment]
mugahagahah dont worry its not really ur problem, many app parts really miss a good explanation.

a quote from the readme tho, talking about that button
> Insert after latest inserted
> - Want to insert multiple tracks one after each other? this will get your back.

**Comment by z9xx7o0** [comment]
@MSOB7YY , this is unrelated, idk if this is an issue or a feature request, so i will just put it here. I think that this menu is a little too big and cluttered. I think you should think about shrinking it a little. Here are some ideas:
![Finished1.png](https://github.com/namidaco/namida/assets/83415416/159456c5-2054-425a-8641-6e22e3fb8683)

And it would look like this:
![Finished2.png](https://github.com/namidaco/namida/assets/83415416/30262a17-ba58-4ab4-8c09-abd076689909)

Here is how it looks now for perspective:
![Original.png](https://github.com/namidaco/namida/assets/83415416/4864fbc8-828b-4941-8d10-122f6a3fa786)

**Comment by MSOB7YY** [comment]
@z9xx7o0 i also think the same, its always hard to remove/reorder things but i kinda like your ideas. the "pause after this track" icon would be misleading tho, and yeah as u have shown there would be no place left for ratings/tags/moods.. idk 
should i convert it to a new issue?

**Comment by z9xx7o0** [comment]
@MSOB7YY , It's up to you if you want to convert this to an issue or create an entire new one. but for the moods, ratings, and tags, I had this idea: In the image I showed you earlier, instead of the question mark, there would be an icon for all of them. And when you press it, you will get a menu like this:
![1720484885219.png](https://github.com/namidaco/namida/assets/83415416/468a90d3-1702-472e-bfa8-fd166c74cdf7)

**Comment by z9xx7o0** [comment]
@MSOB7YY , It's up to you if you want to convert this to an issue or create an entire new one. but for the moods, ratings, and tags, I had this idea: In the image I showed you earlier, instead of the question mark, there would be an icon for all of them. And when you press it, you will get a menu like this:
![1720484885219.png](https://github.com/namidaco/namida/assets/83415416/468a90d3-1702-472e-bfa8-fd166c74cdf7)

**Comment by MSOB7YY** [comment]
yeah i really like these, #262 is the new issue, lets follow up there
