### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by VipinVIP** [namidaco/namida#26]
A release in [F-Droid](https://f-droid.org/)  would make the  app more accessible to some people. I'm happy with using it via obtainium, but an fdroid publishing will give more exposure to the app. 

In case fdroid rules are too restrictive, you can possibly look into [Izzydroid](https://android.izzysoft.de/intro.php) repo too.

**Comment by MSOB7YY** [comment]
yeah i thought about that, but currently there are few numbers of libraries of mine still private, im planning to make them public but only if Namida ever got recognition (cuz dont wanna ppl stealing project)

i tried looking into Izzydroid but couldn't find any way to publish a project there

**Comment by coderkei** [comment]
> A release in [F-Droid](https://f-droid.org/) would make the app more accessible to some people. I'm happy with using it via obtainium, but an fdroid publishing will give more exposure to the app.
> 
> In case fdroid rules are too restrictive, you can possibly look into [Izzydroid](https://android.izzysoft.de/intro.php) repo too.

Not possible for F-Droid specifically as they only allow FOSS apps (like GPL or Apache licensed), and this app has a proprietary license.

**Comment by coderkei** [comment]
> yeah i thought about that, but currently there are few numbers of libraries of mine still private, im planning to make them public but only if Namida ever got recognition (cuz dont wanna ppl stealing project)
> 
> i tried looking into Izzydroid but couldn't find any way to publish a project there

You apply by creating an issue on Izzysoft's Repo here:
[https://gitlab.com/IzzyOnDroid/repo](https://gitlab.com/IzzyOnDroid/repo) 

It's unlikely your app will be accepting though considering your code is not licensed under a "FOSS" license.

Aruguably getting your app into F-Droid or IzzyDroid is what you need to get that needed recognition however so make as you will.

**Comment by Red6785** [comment]
I'd say worrying about getting more attention is something for later. Right now, in the apps early stages, I think it would be better to slowly expand, quash bugs, add more features, etc, than it would be to go big and possibly get overwhelmed.

**Comment by coderkei** [comment]
> I'd say worrying about getting more attention is something for later. Right now, in the apps early stages, I think it would be better to slowly expand, quash bugs, add more features, etc, than it would be to go big and possibly get overwhelmed.

I'd prefer that we didn't have more apps with proprietary licenses (this can sometimes discourage contributors) however that is the developer's choice.

**Comment by MSOB7YY** [comment]
i agree with @Red6785 
Namida is still pretty new and fixing bugs/adding features is what to care about now, maybe later also after making the private packages public.

thanks for the suggestion btw

closing as won't fix "for now"

**Comment by regorxxx** [comment]
Linking related issues here about this, since some devs may only consider adding 3rd party support changes for Namida if Namida is on an app store:
https://github.com/WheresWaldo/FiiOat/issues/10
