### ISSUE TITLE
Add Login System 

### ISSUE THREAD

**Issue by MaheshHande** [namidaco/namida#261]
1. Add Login System Through Google So user Can use there YouTube account Directly from this App
2. There is YouTube Video Loading Problem Not that free Feel like YouTube 
3. Make Animation Like YouTube For Faster Experience 
4. Everyone one Want to watch Ad Free YouTube So make this app YouTube Friendly 
5. Need To Load fast Video on YouTube and also thumbnail its take to much time 
6. Always Show trending video on home page , Recommendations Like YouTube 
7. Change App logo its like a game logo 
8. Thank you For This App overall is Awesome

**Comment by MSOB7YY** [comment]
thank you, but these stuff are already either fixed in beta or planned in #227 

about the logo am not really changing it for now
