### ISSUE TITLE
[BUG] Youtube Replay And Downloading Not Working

### ISSUE THREAD

**Issue by Yolomic** [namidaco/namida#265]
Since some hours ago it all worked now it doesnt
## Expected Behavior
Downloading and playing songs doesnt work only for yt
## Current Behavior
Downloads fail and replaying just skips to next song after a while
## Steps to Reproduce

1. Try to interact with youtube downloading/vid playing

## Logs
Nothing of importance in them tested on 2 sevices

**Comment by MSOB7YY** [comment]
try the latest beta https://github.com/namidaco/namida-snapshots and check related youtube progress on #227. download might have some issues but im working on that

**Comment by Yolomic** [comment]
Thanks will check

**Comment by Yolomic** [comment]
Can confirm works on latest beta

**Comment by IamMahdi23** [comment]
![Screenshot_20240726-194603](https://github.com/user-attachments/assets/408be896-f90a-4719-86e7-3c95d3fef38c)
Didn’t login.....  Beta app.... I clicked download then choose the option then when i clicked the final download button this shows up

**Comment by MSOB7YY** [comment]
@IamMahdi23 can u create a backup with "metadata cache" only and send it? 
![Screenshot_20240726-164755_Namida](https://github.com/user-attachments/assets/4613bad9-3445-428f-9009-2eff30c798c6)

**Comment by MSOB7YY** [comment]
for newcomers, please check latest beta for a working yt https://github.com/namidaco/namida-snapshots/releases
