### ISSUE TITLE
App is not working properly 

### ISSUE THREAD

**Issue by EswarDas123** [namidaco/namida#266]
The app can't play a music from YouTube search. Also download feature is not working. 
I shared screenshots of the problem.

So work on these in app bugs and issues.

Thank you
![Screenshot_20240709_234051](https://github.com/namidaco/namida/assets/175151602/4159985d-8c45-4fe1-94b1-d9f4a6ec774c)
![Screenshot_20240709_235552](https://github.com/namidaco/namida/assets/175151602/ff82926d-28c5-41fd-8ad8-a82ba1bc36ed)
![Screenshot_20240709_235632](https://github.com/namidaco/namida/assets/175151602/139e03dc-6b80-4d17-a8c1-80b8f3cbc858)

**Comment by Jassigamer3070** [comment]
I am also currently facing the same problem 
![Uploading Screenshot_2024-07-10-07-18-04-48_efbfb0790a8187cbd43560835da1b509.jpg…]()

**Comment by MSOB7YY** [comment]
duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346

**Comment by An889-hue** [comment]
When this issues going to fix ?( YouTube music not getting played and much more )

**Comment by MSOB7YY** [comment]
@An889-hue already fixed long ago in beta. 
stable will be in few weeks hopefully

**Comment by RaunakBIT** [comment]
Please resolve this issue as soon as possible, also tell me why the Namida application removed from play store ?
It's also not working with VPN

**Comment by RaunakBIT** [comment]
When this issue is going to resolve

**Comment by MSOB7YY** [comment]
@RaunakBIT who told u it was ever on playstore?

**Comment by VerySweetBread** [comment]
> @RaunakBIT who told u it was ever on playstore?

Isn't every single app on Play Store?

**Comment by MSOB7YY** [comment]
> Isn't every single app on Play Store?

no

**Comment by RaunakBIT** [comment]
> @RaunakBIT who told u it was ever on playstore?

Bro this was available on play store just one & half month ago, i downloaded it from there, but when I face problem in operating it then I uninstalled it and went to play store to again download it, it wasn't there, TRUST ME DUDE

**Comment by RaunakBIT** [comment]
> > @RaunakBIT who told u it was ever on playstore?
> 
> Isn't every single app on Play Store?

Bro it was there

**Comment by VerySweetBread** [comment]
> > @RaunakBIT who told u it was ever on playstore?
> 
> Bro this was available on play store just one & half month ago, i downloaded it from there, but when I face problem in operating it then I uninstalled it and went to play store to again download it, it wasn't there, TRUST ME DUDE

The creator said it wasn't, dude

**Comment by MSOB7YY** [comment]
@RaunakBIT u just got scammed then
