### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 0dusk** [namidaco/namida#267]
I'm facing a big ig everytime I play any video on Namida it says Error playing the video or something... please see to this matter. 
![Screenshot_20240710-015649](https://github.com/namidaco/namida/assets/175159094/2c4e3cb7-ed05-4365-a3cc-87c2ef87dbb2)

**Comment by Maxitendo1** [comment]
@0dusk https://github.com/namidaco/namida/issues/265#issuecomment-2218342339
