### ISSUE TITLE
[BUG]  namida app is not playing online youtube mp4 or mp3

### ISSUE THREAD

**Issue by Khan0019** [namidaco/namida#268]
When I am trying to play a youtube video it's not playing and not even in audio. It says error playing video try again. Then it says skipping video

## Expected Behavior
 It should have play the youtube video or audio

## Steps to Reproduce

1.
2.
3.
4.

**Comment by 0dusk** [comment]
Hey; that's exactly what I'm facing right now too. Let's hope developers fix this issue asap!

**Comment by Khan0019** [comment]
Yep one day they will I guess and some how new version will be coming

**Comment by KumarKamble03** [comment]
![Screenshot_20240711-082342_Namida](https://github.com/namidaco/namida/assets/175274784/1bc33ea4-fd9a-481b-b35a-4519469c7926)
Error while playing YouTube videos.

**Comment by CoolOmar26** [comment]
Yes I have it too

**Comment by Khan0019** [comment]
Now what should I do

**Comment by Khan0019** [comment]
Now how should I fix it then?

**Comment by Khan0019** [comment]
I don't have thread.

**Comment by krishnagupta1229** [comment]
What should I do now I wanna listen to music

**Comment by MSOB7YY** [comment]
@Khan0019 @0dusk @KumarKamble03 @CoolOmar26 @krishnagupta1229 duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346
to make it clear youtube recently broke existing clients that depend on web client. everything is working fine in beta

**Comment by murmuvikash** [comment]
Me too

**Comment by Here4atharvvv** [comment]
> @Khan0019 @0dusk @KumarKamble03 @CoolOmar26 @krishnagupta1229 duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346
> to make it clear youtube recently broke existing clients that depend on web client. everything is working fine in beta

When it will fix?

**Comment by MSOB7YY** [comment]
@Here4atharvvv fixed in beta? wait the new release for stable

**Comment by youbitchy00** [comment]
Can anyone tell me how to fix this issue?🙏 I'm so saddd cause I can't play or download any video.. please 😭😭😭😭😭

**Comment by FastCocobo** [comment]
@ybitchy00 What version are you on?

**Comment by youbitchy00** [comment]
> [@youbitchy00](https://github.com/youbitchy00) What version are you on
It's v.4.9.2 - beta.

**Comment by MSOB7YY** [comment]
fixed in **v4.9.4** https://github.com/namidaco/namida-snapshots/releases

**Comment by youbitchy00** [comment]
> fixed in **v4.9.4** https://github.com/namidaco/namida-snapshots/releases

THANK YOU SO MUCH FOR HELPING ME OUTT!!!!😭. YOU'RE SO COOL💗💗💗

**Comment by MSOB7YY** [comment]
and you are varry cute❣️❣️
