### ISSUE TITLE
Custom Pitch & Playback speed 

### ISSUE THREAD

**Issue by Lumiknight869** [namidaco/namida#271]
The ability to set custom Playback speed and pitch like 0.98181818182 for 432Hz or 1.00909090909091 for 444Hz and so on

**Comment by MSOB7YY** [comment]
yeah as discussed earlier, will check if there is any place for an extra button

**Comment by MSOB7YY** [comment]
hey, this is implemented in https://github.com/namidaco/namida/commit/ec970848bf8f6fc0a6037906b997effc4b3f52aa and should be available from next beta release (v4.0.53+)
there is no dedicated button for this, just press these icons
![image](https://github.com/user-attachments/assets/29d292c7-f9f6-4385-ad4f-201371342590)
