### ISSUE TITLE
Youtube videos, downloads and playback is not working. [BUG] 

### ISSUE THREAD

**Issue by Leyze1** [namidaco/namida#273]
So the youtube section wont work.
Ive given it permission to files, other permisions, etc.
Redownloaded it 3 times, didnt work.
## Expected Behavior

If it worked it wouldnt give me an eror, would let me play or download a video.
## Current Behavior

Currently the youtube section is still not working.
## Steps to Reproduce

1. i
2. d
3. k
4. man

## Screenshots

![Screenshot_20240711_195717](https://github.com/namidaco/namida/assets/175347722/f37193ab-bf40-45a4-98fb-059f370bf122)

## Logs

https://drive.google.com/file/d/1hdDBUyJ6daWy5xd6nyfOqQD8klaIqUwa/view?usp=drivesdk
  
https://drive.google.com/file/d/1hRfX_iE6S_QUlApq_pTIlpirg8gkhBWv/view?usp=drivesdk

https://drive.google.com/file/d/1hfI7uGpPgfiJYfYD7b6BKvXwXOY-0KdM/view?usp=drivesdk

## Possible Solution

nope

**Comment by Maxitendo1** [comment]
@Leyze1 https://github.com/namidaco/namida/issues/265#issuecomment-2218342339
