### ISSUE TITLE
[FEATURE REQUEST] Volume normalization 

### ISSUE THREAD

**Issue by endless-stupidity** [namidaco/namida#274]
**Is your feature request related to a problem? Please describe.**
I have an album that is (for some reason) much quieter than the rest of my music *portfolio*. I know the equalizer section has a loudness enhancer but that's global (for all tracks) which doesn't help much here.

**Describe the solution you'd like**
Perhaps a simple toggle in the settings menu (in the Playback section?) that sets the volume of all tracks to the same level (or as close as possible)

**Describe alternatives you've considered**
I guess I could use an audio editor and edit the gain for all the tracks in that particular album, but idk, I feel like it lacks *finesse* 

**Additional context**
🥱

**Apps**
[ViTune](https://github.com/25huizengek1/ViTune) does this really well I believe.

**Comment by MSOB7YY** [comment]
this will require parsing of replay gain tag and is already requested at #57, i know it's been a long while but sorry, should eventually work on it..
