### ISSUE TITLE
[FEATURE REQUEST] search for cover on the Web and download it

### ISSUE THREAD

**Issue by Rushikesh321** [namidaco/namida#276]
So to describe the feature, 
When a song is playing and you click on the three dot menu and you will see a edit tags menu(it can be either edit tags or advanced since they are related to this feature) and after you click on it. The feature to search for cover on the Web should be there. If you visit the images of stellio player on the [play store](https://play.google.com/store/apps/details?id=io.stellio.music) you will understand what I'm talking about.
Thanks.

**Comment by MSOB7YY** [comment]
that actually been requested for a long while at #5. kudos for using stellio tho, was my fav player
