### ISSUE TITLE
[ISSUE] round corners on tracks

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#283]
In this app, nearly everything has round corners except the tracks. That ruins the theme of the app. So I think the tracks should have round corners. Here is an example of what it would look like: 
![Untitled2_20240715153604.png](https://github.com/user-attachments/assets/d980403d-8fc7-4cbd-b56a-ab8acddada3c)

**Comment by MSOB7YY** [comment]
im lowkey against this. its not that everything should have rounded corners, its more about uniqueness and nice design. having card-like shape for tracks would just make it worse/boring/cheap.

the app bar and navigation bar roundness looks nice but i tried them before and they made the app look kinda cheap so yeah same thing

**Comment by z9xx7o0** [comment]
@MSOB7YY , i didn't know that. I'll close this issue. I just thought that the app should be more uniform since everything else has round corners.

**Comment by MSOB7YY** [comment]
woah thanks a lot for understanding <3
