### ISSUE TITLE
[FEATURE REQUEST] refresh to update metadata and artwork 

### ISSUE THREAD

**Issue by Rushikesh321** [namidaco/namida#284]
So basically when I want to update artwork or metadata of a song i typically use a auto tagging app. But when I update the metadata and artwork of that song in that app the song is not updated in the player instantly or when I refresh the music player or reindex it in settings, first I have to click on three dot menu of the song i have updated => select advanced option => click on artwork button => click on reindex button => then it's updated. so my request is if you can shorten the process to like
      update the song in auto tagging app => refresh the music player or reindex the whole library in settings => voila the song is updated. 
So yeah there you go I hope you add this feature as soon as you can. Thanks 👍

**Comment by MSOB7YY** [comment]
why not use indexer => reindex (with enabled "clear image cache")?

**Comment by Rushikesh321** [comment]
Yeah I was able to update it but there is still a little bit of a problem
left and that is when you minimise the song, in the song directory of music
player you can see that the artwork is still not seen clearly updated. I
hope it doesn't bother you too much

**Comment by MSOB7YY** [comment]
hmm i think we had a similar problem before and i think it was fixed in beta. not so sure tho
if its not fixed i would need reproducable steps

**Comment by MSOB7YY** [comment]
@Rushikesh321 hopefully this is fixed with [v4.0.8](https://github.com/namidaco/namida-snapshots/releases/), can you confirm?

**Comment by Rushikesh321** [comment]
The problem still persists but i found a workaround.
update the metadata of the multiple songs => go to the music player => use
indexer to reindex(select 'select image cache') => then select one of the
updated songs => click on three dots => advanced => select artwork =>
click  reindex => both metadata and artwork of the songs are updated.
problem solved. Thanks.

**Comment by MSOB7YY** [comment]
that's not a workaround lmao that's how it should be
either full reindex from indexer settings or select tracks -> advanced -> reindex

anyways glad it's working!

**Comment by Rushikesh321** [comment]
Congratulations!
