### ISSUE TITLE
[BUG] error 0

### ISSUE THREAD

**Issue by Here4atharvvv** [namidaco/namida#286]
Video is not playing.

## Expected Behavior
video is not playing on YouTube, Means no audio or video is playing.. 

## Current Behavior
 Video not playing on YouTube, Means no audio or video is playing.. 
And it showing error 0 

## Steps to Reproduce

1.
2.
3.
4.

## Screenshots

![image](https://github.com/user-attachments/assets/2751c9da-b158-4fd8-a08e-db6850ef2980)

**Comment by MSOB7YY** [comment]
#265
