### ISSUE TITLE
[FEATURE REQUEST] Import/open m3u playlist file

### ISSUE THREAD

**Issue by christubuntu** [namidaco/namida#293]
As far as I can tell, the app doesn't allow importing or even opening m3u playlist files, so I have no way to bring over my playlists from the music app I was using.

**Comment by christubuntu** [comment]
Duplicate

**Comment by MSOB7YY** [comment]
@christubuntu  yep glad u noticed. btw m3u reading and syncing is already there (it was just a small issue in v2.5.6 that prevented reading them)
