### ISSUE TITLE
[BUG] Download Failed

### ISSUE THREAD

**Issue by IamMahdi23** [namidaco/namida#296]
everytime I try to download something says download failed. both on audio and video. it doesn't download at all I have tried several times. 

please see what is causing this. 
![Screenshot_20240725-072011_Chrome](https://github.com/user-attachments/assets/bab98998-020e-4878-ad3f-ae1eb7b0bc94)
![Screenshot_20240725-072345](https://github.com/user-attachments/assets/12e9c0d5-b62c-4d03-b35b-31b46472e8c7)
Check ⚠️ these

**Comment by Hopiie** [comment]
The same keeps happening to me and I thought it was just a device issue 
![Screenshot_20240725-154404_Chrome](https://github.com/user-attachments/assets/db27be66-dfdd-4ca6-94bf-1a2b7810950b)

**Comment by MSOB7YY** [comment]
this is like the 100th issue about this.. #265
