### ISSUE TITLE
Feature request - Add audio metadata info

### ISSUE THREAD

**Issue by fedikhatib** [namidaco/namida#30]
Hi thanks for your efforts amazing application.
Can you add an audio metadata and other File info like the location for Local files

**Comment by MSOB7YY** [comment]
thank u so much

this already exists, by opening track menu and then clicking on the top part (the one with an arrow)
- u can also copy any field by tapping or long pressing
- u can save artwork to "Internal Storage/Namida/Artworks" by opening the image and long pressing
- u can show/hide unknown fields
- preview track (without affecting the current queue)
![Screenshot_20231018-192302_Namida](https://github.com/namidaco/namida/assets/85245079/e8167255-a1f9-4687-81f0-e16c3eddae02)
