### ISSUE TITLE
[BUG] The video does not play and doesn't get downloaded from youtube

### ISSUE THREAD

**Issue by skgupta507** [namidaco/namida#303]
The does not play videos from youtube and audio it doesn't even download the audio and video anymore. 

## Expected Behavior

Shuld have played and downloaded

## Current Behavior

Its not downloading and playing

## Steps to Reproduce

1.
2.
3.
4.

**Comment by crnobog69** [comment]
Same

**Comment by hamsteruf** [comment]
The same for me on the current latest verison

**Comment by MSOB7YY** [comment]
#265 everything is working in beta. the stable version should release soon in a week or two
