### ISSUE TITLE
[QUESTION] about  tranks title and artist

### ISSUE THREAD

**Issue by mhdamine15** [namidaco/namida#304]
so im facing a problem here,and it happens especially in the player
the problem is the mp3 file/ track name 

the track starts with the artist name, not the file name 
(ex:
Toto
Toto-hold-the-line-official-video)

i want to make it the opposite, i mean tracks name first then artist like other music players
(ex 
Toto-hold-the-line-official-video)
Toto)

## Screenshots

![a8052d0b-ab2e-4e96-ad76-ad3797de057d](https://github.com/user-attachments/assets/deabe39f-50b9-44fd-bfd9-8e43d4f8c278)

**Comment by z9xx7o0** [comment]
@mhdamine15 Settings>Customizations>Display artist before title (at the very bottom). Turn it off.

**Comment by MSOB7YY** [comment]
as @z9xx7o0 mentioned, if ur talking about miniplayer.
if you mean all track tiles, then `settings > customization > track tile customization` from there u can put literally any track into in any place in the track tile

**Comment by mhdamine15** [comment]
> as @z9xx7o0 mentioned, if ur talking about miniplayer. if you mean all track tiles, then `settings > customization > track tile customization` from there u can put literally any track into in any place in the track tile
wym? can u explain further?

**Comment by MSOB7YY** [comment]
![Screenshot_20240729-232433_Namida](https://github.com/user-attachments/assets/f9629d12-289f-4f8d-9705-1840086d6ba3)
explain what? you can customize the track tile from here. press any chip to put the info u want

**Comment by nhan000** [comment]
Hi @MSOB7YY  how can I customize what to be displayed here?
<img width="1080" height="2160" alt="Image" src="https://github.com/user-attachments/assets/34198911-9a59-437e-ae28-fc10f19b265d" />

**Comment by MSOB7YY** [comment]
@nhan000 u can only swap places https://github.com/namidaco/namida/issues/304#issuecomment-2256648530
