### ISSUE TITLE
After logging in to my yt account when i try to access the feed it says error operation feedfetch requires atleast membership cutie your current membership is unknown

### ISSUE THREAD

**Issue by User6899j** [namidaco/namida#306]

**Comment by User6899j** [comment]
And now yt works but after watching 1 vid it says skipping source error 0

**Comment by VerySweetBread** [comment]
Is the template a joke for you?

**Comment by User6899j** [comment]
Sry but i have a problem and im new to github

**Comment by User6899j** [comment]
Sorry but im new to github and i had a problem

**Comment by raeuz** [comment]
The same problem too.

**Comment by User6899j** [comment]
> The same problem too.

The latest beta release fixed it

**Comment by MSOB7YY** [comment]
this is what happens when u skip messages on tg channel

upcoming youtube action would require u to be a patreon, except for a choose one which is voted also on telegram.

**Comment by PavanTelugugamer** [comment]
![Uploading Screenshot_20240821_114546.jpg…]()

**Comment by PavanTelugugamer** [comment]
![Screenshot_20240821_114546](https://github.com/user-attachments/assets/8b9cfd43-cd52-40bc-9880-21d979770f75)
  Please help me

**Comment by VerySweetBread** [comment]
@PavanTelugugamer, are you stupid or what? Read a message above
