### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Yami350** [namidaco/namida#307]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yami350** [comment]
![Screenshot_2024-08-04-06-19-27-17_efbfb0790a8187cbd43560835da1b509](https://github.com/user-attachments/assets/96a12d25-7086-4a99-a397-98bf58492e4f)

**Comment by Yami350** [comment]
Video not working

**Comment by l300lvl** [comment]
See with eyes, open:

https://github.com/namidaco/namida/issues/308#issuecomment-2267304622
