### ISSUE TITLE
Customization, Sorting & Possible Bug

### ISSUE THREAD

**Issue by PlumBlossoms13** [namidaco/namida#31]
1. On the screen with now playing screen (?) I was wondering if it was possible to swap where the title of the song and artist are (screenshot one). Right now, the artist is on top. It's not a big deal, if not!

2. Also, on the top of that screenshot you can see that it's playing song 62/1000 but in that playlist, I have 1058 songs. Is that supposed to happen?

3. For the track view, I have the tracks sorted by album artist. But for some reason, it splits up the album (screenshot two). I've tried playing around with the settings but it doesn't seem to put the tracks in order by track number
![Screenshot_20231019-001529](https://github.com/namidaco/namida/assets/109384939/2c4851a2-0276-48d5-afc6-8cd13d2e9719)
![Screenshot_20231019-032756](https://github.com/namidaco/namida/assets/109384939/ce7544e9-e6a5-4859-82b1-53705d6a21d5)

Any help is appreciated and thank you for all your hard work! ✨

**Comment by MSOB7YY** [comment]
thank u so much firstly

1. there is no option for that currently, but some ppl asked for it too and its not hard, so i will add it
2. - player queue is limited to 1000 tracks, for performance/storage concerns, since these tracks are saved as queues in storage and loaded when the app opens
   - one way to bypass this is to 
     1. play 1 track (open track menu and select play)
     2. select all tracks/album/playlist etc and choose (play next/play last), they will be all added
 3. i dont quite get whats the problem, the third line u see is the `album` and tracks are correctly sorted by `album artist`, if u want to change what items to display, please change from customization settings (see screenshot below)
    - do you possibly mean that sorting by album/album artist should also sort by tracknumber?
![Screenshot_20231019-154503_Namida](https://github.com/namidaco/namida/assets/85245079/8da285cd-42fe-4f53-802f-c0d89b823bd3)

**Comment by PlumBlossoms13** [comment]
You're welcome!
1. Thank you!
2. Okay so if I just click the three dots and press shuffle from the playlist tab it'll only play the first 1000 tracks? When I press play from the tracks menu, it says track/501 and using the shuffle option is still track/1000. Using the play next/play last option creates a queue of sorts of more songs than I actually have and not shuffled.  I'm not sure if there's something I'm doing wrong?
3. And yes to the sorting by track number! I'm not sure if anyone else cares about it but I just like to see my albums grouped together in order of track#

**Comment by MSOB7YY** [comment]
1. added in c9919cdbca38220495a23c105a7e7bca59c89fc9
2. - no, it will shuffle the whole playlist, then pick 1000 tracks
   - the 1000 limit is divided 500 before and 500 after
   - when u press play from track menu, it should only play the selected track/s, this should be used just to clear the queue
   - using shuffle will add 1000 tracks and thats expected
   - using play next/play last should add ALL selected tracks, and that should solve ur issue
3. subpages tracks sorting is now implemented in b82dce29d98b01f69fba1ea44bee7e131dd44a41, they are configurable and reorderable (see screenshot) (for example: sort by `track number`, if both are similar, then sort by `duration`.. and so on
   - for ur case, tracks page sorting goes the same way, if u want to sort by album, and want specific order for the album, then u got to configure `album subpage tracks sorting` (the one in screenshot)
   
![image](https://github.com/namidaco/namida/assets/85245079/0dd4c226-8aa2-4ce9-aaf8-a8ac4ac230f0)

-----
- closed as completed, you can reopen if there is still a related issue/bug.

**Comment by PlumBlossoms13** [comment]
Sorry, I'm still a bit confused. I'm just trying to shuffle the 1110 tracks I have now and just 1000. Using the play next/play last option is creating queues that are 1600+ tracks when I don't have that many songs

**Comment by MSOB7YY** [comment]
here's what i would do to shuffle more than 1000 track
1. play any 1 track
2. select tracks i want to shuffle (or playlist/album etc) and do "play next" 
3. open player queue and press "shuffle" on bottom right
    - or long press and choose "shuffle all"
4. the resulting queue should be 1110 shuffled tracks
- if u were playing a queue before (skipped step 1), then pressing trash icon (beside shuffle button in queue) will  remove all duplicates
-------
- if this is still not working for u, can u please provide a short video showing what is happening with u? sorry for the inconvenience
- im not sure too if i should increase the maximum limit, cause ppl usually don't listen to that many tracks in one go

**Comment by PlumBlossoms13** [comment]
Oh I got it now! I didn't realize the player queue was the two boxes beside the lyrics box 😅
(I work from home so I listen to a lot of music at once lol)
Thank you so much for your patience with me, I really appreciate it! 💖

**Comment by MSOB7YY** [comment]
glad its working for u 🌺, btw all swipe gestures are working (swipe up to open queue/miniplayer, swipe left/right to change track, swipe down to close queue/miniplayer, etc)
thank u too for ur notices, let me know if i should increase the limit for u :3 (even tho 1000 are atleast 30hr+ 💀)

**Comment by PlumBlossoms13** [comment]
You're welcome! And no you don't have to increase the limit 😅 I'm a unique case 😂

**Comment by MSOB7YY** [comment]
update to max queue part, i allowed unlimited queue if u play using any button (except when pressing the track tile itself)
can be checked in v4.8.3 beta here https://github.com/namidaco/namida-snapshots/releases
