### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Amanravi1** [namidaco/namida#310]
**Is your feature request related to a problem? Please describe.**
bro i want to stop after certain period of time to stop music each time i have to put manually stop music

**Describe the solution you'd like**
can you add a feature where music will stop after certain period of time like 5 min 10 min

**Describe alternatives you've considered**
i have seen other app having sleep timer 

**Apps**
oto music have sleep timer in his player
![Screenshot_2024-08-04-22-52-16-62_8837454c1a92d7fdcae10cd5efc3743a](https://github.com/user-attachments/assets/318b948d-de49-488b-b1f2-493831495d4b)

**Comment by MSOB7YY** [comment]
sleep timer is in app sidebar (drawer)
