### ISSUE TITLE
[BUG] App not opening after latest update (3.8.5)

### ISSUE THREAD

**Issue by endless-stupidity** [namidaco/namida#312]
Updated the app by changing the Android/data folder name. Now after installing the new version the app refuses to open.
## Expected Behavior

The app should have opened? Lol
## Current Behavior

The app opens to an empty screen and nothing happens 
## Steps to Reproduce

1. have old version (not beta)
2. rename Android/data folder and uninstall app
3. install the new version but don't open it 
4. rename the Android/data folder back to the original, be faced with disappointment 

## Screenshots

It's literally a black screen (or white, if you aren't in dark mode)
## Logs

Can't, since the app doesn't open 
## Possible Solution

Sorry!

**Comment by MSOB7YY** [comment]
woah just checked and it really didnt open, apparently accessing the old folder is denied by the system so yeah sorry for this. i will edit the guide and u gotta follow method 3 (which is taking & restoring backups). sorry again

**Comment by endless-stupidity** [comment]
Just deleted the old data folder and sure enough, the app opened. Gotta thank the auto backup though, otherwise I would have been very distressed!

Thanks for your work btw 👌

**Comment by MSOB7YY** [comment]
glad u had an auto backup! u could install the old version again and take backup tho so nothing to be distressed about 
i think it would work too if copied the internal files *after* the new version installed (instead of renaming) but yeah backup is safer ig

thank you so much! <3
