### ISSUE TITLE
[BUG] Obscure white screen bug

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#315]
So while testing the new update i found this very random and funny bug. When you swipe with two finger vertically in opposite direction in song queue (with the intention of sorting the song) and release, the white screen appears.

## Screenshots
https://github.com/user-attachments/assets/20b7dcbd-9af0-49be-aeeb-54fd718e8ebd

**Comment by MSOB7YY** [comment]
lmao im quite impressed about the bugs u discover and how u do it, just pushed a fix for this at 30218658049d64f2f2b2ea76e18ec68aee87c830. thank you so much for this <3

**Comment by NikunjKhangwal** [comment]
Pure coincidence really. I was trying to change the size of thumbnail and completely forgot i had to pinch out from the middle instead of corner. Because of this the queue was opening and the white screen started appearing. I tried the same pinching out input and discovered the bug after a while lol.

**Comment by MSOB7YY** [comment]
wow quite the scenario there.. glad it was discovered before someone *tries to reorder 2 items at the same time* 💀
