### ISSUE TITLE
[FEATURE REQUEST] Option to hide "unknown genre" and Keeping screen awake for video only

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#316]
1. When a song doesn't have genre tag, it shows "unknown genre" which looks weird. Maybe an option to not show any genre at all for these songs?
![IMG_20240807_114626](https://github.com/user-attachments/assets/10a520ec-d564-4492-995b-5a12486ba09c)

2. Keeping screen awake for video only as you have to keep it for both expanded player and video right now.
![IMG_20240807_111727](https://github.com/user-attachments/assets/a0fc2087-f78b-4a21-8fe3-efad1a3252ab)

**Comment by MSOB7YY** [comment]
1. woah the first one is like a bug, just fixed it (it will now show whatever original genre, just like artist)

2. hmm but what is the actual purpose? if a video is playing but u not even looking at it (ie. minimized)?

**Comment by NikunjKhangwal** [comment]
A bit of misunderstanding here. I want to keep screen awake for video but disable it for expanded miniplayer (this screen)
![Screenshot_2024-08-08-01-07-15-823_com msob7y namida](https://github.com/user-attachments/assets/26bfe6bf-bfe2-492a-a353-7651a4a7bcd6)

**Comment by NikunjKhangwal** [comment]
> it will now show whatever original genre, just like artist

Btw how will it show the genre if song doesn't have genre tag embedded?

**Comment by MSOB7YY** [comment]
sorry i still dont get it
there are 4 possible scenarios
1. miniplayer expanded + video playing (already available)
2. miniplayer expanded + video not playing (already available)
3. miniplayer **minimized** + video playing (this is what you want?)
4. miniplayer **minimized** + video not playing (no purpose for this)

---

> Btw how will it show the genre if song doesn't have genre tag embedded?

will just show nothing (like an empty slot)

**Comment by NikunjKhangwal** [comment]
Ah! I'm dumb 😩
I was thinking about youtube section video instead of video in miniplayer. Now it all makes sense. Sorry about that.

**Comment by MSOB7YY** [comment]
yep the same behavior applies for both local player and youtube player, glad it's all cleared up!
