### ISSUE TITLE
[ISSUE] New tracks wont refresh

### ISSUE THREAD

**Issue by User6899j** [namidaco/namida#318]
I downloaded song from the built in youtube client and also some from my sd card but now the songs in tracks wont refresh
## Expected Behavior

The new songs should have showed up agter refreshing

**Comment by MSOB7YY** [comment]
the folder of these music should be included in indexer folders in settings.

note: 
  - swipe to refresh had a bug and was fixed earlier
  - now that video playback is implemented, everything downloaded in namida is added to local library immediately

you can use the latest beta from here https://github.com/namidaco/namida-snapshots/releases (v4.0.5 as of now)
