### ISSUE TITLE
[FEATURE REQUEST] Youtube Video Subtitles

### ISSUE THREAD

**Issue by Eliya-Manoj** [namidaco/namida#319]
**Is your feature request related to a problem? Please describe.**
I watch the video with subtitles and without it i don't understand anything.

**Apps**
Youtube, Newpipe, Libretube

**Comment by MSOB7YY** [comment]
duplicate of #165

**Comment by MSOB7YY** [comment]
checkout v7 https://github.com/namidaco/namida-snapshots/releases
