### ISSUE TITLE
[BUG] Lyrics being used when it shouldnt

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#32]
![Screenshot_20231019_211052.png](https://github.com/namidaco/namida/assets/78287172/47113b69-26df-48b4-9790-df1db50f7615)

How to fix
Already enabled java in default browser still showing

![Screenshot_20231019_214228.png](https://github.com/namidaco/namida/assets/78287172/7eac6cc1-a80b-464b-bfb0-6fe03cae20f4)

And add amoled theme & crossfade feature up to 30

**Comment by MSOB7YY** [comment]
hello,
1. this only appears when google search fails, google is being used when 
   - no lrc could be found in online database, same track directory, or embedded
   - no txt (plain) lyrics found embedded
- so this means that you gotta put ur own lyrics
- i will push a fix to prevent using the lyrics when it fails like this
2. AMOLED theme is implemented and will be available next release
3. crossfade is quite tricky and might or might not come soon

**Comment by MSOB7YY** [comment]
fixed in 4707c3d3e5bcf88882ae46bf6901c18c4fe9d299
