### ISSUE TITLE
[ISSUE] video and audio is not playing form youtube. Showing error

### ISSUE THREAD

**Issue by IshaanR26** [namidaco/namida#320]
![Screenshot_20240807_083946](https://github.com/user-attachments/assets/c46a67fa-51ab-4c1c-bcc1-bc5acbf5c2fe)

**Comment by MSOB7YY** [comment]
uhmm where are the logs?

**Comment by MSOB7YY** [comment]
bothways u can try the new beta at https://github.com/namidaco/namida-snapshots/releases/tag/3.8.8-beta%2B240809206, u can install it on stable without issues
