### ISSUE TITLE
[FEATURE REQUEST] option to show play count in custom track tile

### ISSUE THREAD

**Issue by Staubsaugerbeutel** [namidaco/namida#323]
Since we are able to sort by most played (although that seems broken and shows another track every time resort), I'm assuming that thr play count information is available. It would be nice to be able to add this to the track tile (for example in the space below "duration")

Shockingly good app by the way.. I'm so glad I found this!

**Comment by MSOB7YY** [comment]
seems like a nice idea. although i would prefer relying completely on the "most played" page.
sorting by most played was added only for subpages (like album/artist tracks etc), so im not sure if displaying play count would be helpful. it might also need a separate space tho.

will check and see, thanks a lot for *finding* and *liking* namida tho!

**Comment by Staubsaugerbeutel** [comment]
Oh I hadn't seen that page yet! My guy you have so many features xd
Assuming the play count is easily available, I thought it wouldn't be much effort to just add it to the list of items that can be added in these individual blocks:

![Screenshot_20240811-143953481 (1)](https://github.com/user-attachments/assets/3ea0f7aa-22f8-4358-a4e1-0a3fedadb3a8)

I have a more "explorative" listening style so I have thousands of tracks downloaded that I didnt listen to yet, so I'd like to be able to keep track on what I've already listened to and listen to the stuff that I haven't heard yet.

In the same context I was thinking of a feature like "(automatic) bookmarks" in playlists that let's you resume to where you left off in a playlist last time so I can progress through the whole thing over time and can forget where I left off. That would be a bit more sophisticated though I guess.

**Comment by MSOB7YY** [comment]
thats also another cool request lmao, pls open a new issue with the title "Resume Playlists (bookmark)", i will probably get into implementing soon

about "play count" in track tile, i will check it as well

**Comment by MSOB7YY** [comment]
just added "play count" and "latest listen date" as optional info in 408a4ef5fec38e92513cffa20c45b4f66d04e30d, thanks for the suggestion! u can try it out from v3.9.2 here https://github.com/namidaco/namida-snapshots/releases/

**Comment by Staubsaugerbeutel** [comment]
dude u a legend. only now that I see that feature I see how nice it actually is to have that lol

**Comment by MSOB7YY** [comment]
yeah i also found it quite helpful lmao thanks for suggesting it

**Comment by MSOB7YY** [comment]
opps i lowkey forgot that the info line built is cached, i will fix by rebuilding the cached info on each listen
same thing for when whole history is loaded at first too
