### ISSUE TITLE
[FEATURE REQUEST] Set Image for Playlist

### ISSUE THREAD

**Issue by injusticedevil** [namidaco/namida#324]
A feature where we can add our own images to our playlist album 
![Screenshot_2024-08-11-18-19-41-831_com spotify music](https://github.com/user-attachments/assets/a710140a-1700-4a6a-9079-06a565c19f52)
Like this

**Comment by injusticedevil** [comment]
![Uploading IMG_20240811_191350.jpg…]()

**Comment by MSOB7YY** [comment]
just added this in 719ead30ded124ed5da5537ffae7509accdecefb

![image](https://github.com/user-attachments/assets/42091f90-cf3e-4709-9156-86669ea27e1f)
use this edit button to edit/delete playlist artwork
