### ISSUE TITLE
[BUG] The notification doesn't show album art

### ISSUE THREAD

**Issue by Drac1652** [namidaco/namida#327]
The notification panel doesn't show album art instead it shows app icon on every album
![Screenshot_20240812_090659](https://github.com/user-attachments/assets/ae6dfd53-fff2-4d99-ab08-5e5e7b308c20)

**Comment by MSOB7YY** [comment]
because the track doesnt have any artwork embedded and the folder doesnt have any fallbacks!? or u may chose to enable media store
