### ISSUE TITLE
[FEATURE REQUEST] Discord RPC implementation

### ISSUE THREAD

**Issue by Moodzz1** [namidaco/namida#329]
There is an android app known as [Kizzy](https://github.com/dead8309/Kizzy) which allows people to create Discord RPC's when an app/media is detected. I noticed that the dev of [InnerTune](https://github.com/z-huang/InnerTune) had requested to use kizzy's library to allow innertune to make discord RPC's. Maybe there a chance you could maybe do smth similar to the dev of InnerTune for adding Discord RPC support to namida.

Here is the issue opened by the dev of innertune asking about implementing kizzy for Discord RPC support in innertune
- https://github.com/dead8309/Kizzy/issues/276

**Comment by MSOB7YY** [comment]
yeah we at #114 lmao
