### ISSUE TITLE
Showing opposite song name

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#33]
First line is singer or artist and second line is Song name

![Screenshot_20231019_175816.png](https://github.com/namidaco/namida/assets/78287172/6ed775d5-6a8e-48e4-8e11-26a7c3c662d9)

It is looking reverse rather song name should be visible first followed by singer name
Plz fix it

**Comment by Red6785** [comment]
This is a setting in the settings in the latest update. Close issue.

**Comment by MSOB7YY** [comment]
as @Red6785 said

disable this in customization settings

![Screenshot_20231024-143042_Namida](https://github.com/namidaco/namida/assets/85245079/33cd887c-fd52-4b21-9979-b582fb046b84)

**Comment by Shivamhobbyist** [comment]
Got it
