### ISSUE TITLE
[FEATURE REQUEST] youtube-less version 

### ISSUE THREAD

**Issue by Oxeda** [namidaco/namida#332]
Now that the yt part of the app has become pay to use, could you guys make a smaller (faster?) version without the yt compound? I love your app for fletching lyrics automatically, and not having ads, but with the yt change I just don't see how revanced is not a better alternative for that specific thing.

Thanks.

**Comment by MSOB7YY** [comment]
youtube part was never a pay to use, and will never be.
https://github.com/namidaco/namida/discussions/328#discussioncomment-10327195

**Comment by MSOB7YY** [comment]
about making a (light) version with no youtube, sorry no. youtube logic is really everywhere which is one of main features (connecting local library with videos, either local or from yt)

u can however remove the youtube "tab" from settings -> extra -> library tabs
