### ISSUE TITLE
[FEATURE REQUEST]  Swipe to play next / swipe to queue

### ISSUE THREAD

**Issue by Xraifoo** [namidaco/namida#333]
Pretty self explanatory, Spotify has it, Apple music has it, would love to see it implemented on my favorite media player of all time! Swiping to queue is one of my favorite features for on the go and when I don't want to think to much about what to play next.

**Comment by MSOB7YY** [comment]
so u basically wanna swipe left a track tile to "play next"?
i know it can be useful but is tapping dialog and pressing play next kinda hard?

**Comment by Xraifoo** [comment]
The quality of life change is about being able to not go into any menus and just look for a song you want to play and swipe it to the left to play next, even tapping the song and holding it to swipe left or right to have it queue is beyond useful for a lot of people.

**Comment by MSOB7YY** [comment]
wakatta. will get into it soon

**Comment by MSOB7YY** [comment]
as mentioned, this was added in v4.0.8.
**left & right swipe with actions (play next/play last/play after/add to playlist)**

note that its disabled by default and u need to enable it from `customization settings -> track tile customization`

thanks for recommending this!
