### ISSUE TITLE
[FEATURE REQUEST] Integrate JioSaavan as a music source

### ISSUE THREAD

**Issue by James-Willer** [namidaco/namida#334]
Add Jio Saavan as a music source.
It provides a large library of pretty high quality music for free.
I am not sure of how it works outside of India but I have seen apps like Blackhole(RIP) and spotube implement it.

The dev of Spotube seems to have written an api client for jiosaavan : https://github.com/KRTirtho/jiosaavn

**Comment by MSOB7YY** [comment]
sorry supporting other apis are out of scope, especially when its an api focused for a country/area, namida is all about local & youtube.
if we ever support extra apis it would be only ytm.

other similar requests: #153 #91 #20
