### ISSUE TITLE
[BUG] Playlist Cropping on Android

### ISSUE THREAD

**Issue by KBell91** [namidaco/namida#336]
Hello. I am using this app on an Android (Galaxy s10 Lite) and when using a playlist I nitice that the left sode is cropped and I can not manually change the order of songs in a playlist.

![Screenshot_20240901_134442](https://github.com/user-attachments/assets/84e97d89-f14b-4a94-99f1-36c99dbecf10)

**Comment by MSOB7YY** [comment]
its not cropped but rather **locked**.
press the lock icon on top right to unlock reordering & dismissing

**Comment by KBell91** [comment]
That did it, but it's still so close that I have to remove my phone case just to move them around. That might need some adjusting.

![Screenshot_20240901_173150](https://github.com/user-attachments/assets/8e9eda55-3356-4778-9416-9d3c26d8f1d1)

**Comment by MSOB7YY** [comment]
@KBell91 
> also the 3 lines are just a visual indicator, u should drag the thumbnail itself
