### ISSUE TITLE
[QUESTION] My MP3 files don't show up and I have a lot of them. Only m4a files do. Can I change it? Or am I doomed???

### ISSUE THREAD

**Issue by anonSale** [namidaco/namida#337]

**Comment by MSOB7YY** [comment]
nah ur doomed
unless u fought back and added the folder of these mp3 files to ur indexer folder in settings

**Comment by anonSale** [comment]
I've moved my files like 100 times by now to different folders😭😭

**Comment by anonSale** [comment]
YAYYYY IT WORKED
THANK YOU FOR YOUR COMMENT THOUGH YOU A REAL ONE

**Comment by MSOB7YY** [comment]
i knew u were strong enough. congrats
