### ISSUE TITLE
[BUG] Refresh fails with .opus files in library

### ISSUE THREAD

**Issue by domportera** [namidaco/namida#340]
Attempting to import a library with .opus files hangs forever, no namida for me /:

## Expected Behavior

namida would ignore my opus files and tell me that it did 

or ideally, namida would welcome my opus files with open arms

## Current Behavior

Refresh fails at X%, with the last log entries basically saying that it hates your opus files

## Steps to Reproduce

1. Try to refresh a libraey with .opus files

## Logs

[logs_tagger_3.8.5_240805177.txt](https://github.com/user-attachments/files/16869344/logs_tagger_3.8.5_240805177.txt)

## Possible Solution

Maybe not much, as if you're working with native audio playback/tag reading android may not support the specific file extension?

I did [find this](https://stackoverflow.com/questions/44435259/how-to-play-opus-audio-file-in-android) - if there is a way for you to specify ".ogg" in file readback, thatd be rad. otherwise a user prompt to change their file extensions could be enough

--- 

PS - thank you for making this app! it seems like it's EXACTLY what ive been waiting for for a long time now and I can't wait to see how it develops :)

**Comment by MSOB7YY** [comment]
hey dis pretty sad for ur opus mates :<
so 
  1. does the indexing finish or get stuck? 
  2. have u tried renaming `.opus` to `.ogg`? i suspect this fixing anything cuz extension doesnt really matter, but u mentioned ppl saying it fixed similar thing
  3. when tags extraction fail, ffmpeg is used. if it failed too then it attempts to extract artist & title from filename. there were issues with this process fixed lately, can u try [beta v4.2.0](https://github.com/namidaco/namida-snapshots/releases)? 
  4. if nothing succeeded, would u provide me a sample opus file?
> PS - thank you for making this app! it seems like it's EXACTLY what ive been waiting for for a long time now and I can't wait to see how it develops :)

much luvvv for yo
