### ISSUE TITLE
[BUG] Imports M3U but Displays Wrong Music

### ISSUE THREAD

**Issue by Nadim147c** [namidaco/namida#342]
## Expected Behavior
The tracks in the playlist should match those in the M3U file.

## Current Behavior
When importing M3U playlists into the music player, the playlist loads, but the tracks include a random track (most likely name starting with a number). Additionally, metadata of the tracks that are included in the m3u files aren't shown.

## Additional Information
1. The m3u file uses 'lf' (\n) and relative path. Here's the head of the file. 
```m3u
#EXTM3U
#EXTINF:0,Hold Of Me
./Hold Of Me [6dIZb64N6ICAWrf1RJrKfB].mp3
#EXTINF:1,7 Minutes
./7 Minutes [6FYbr9QzRoZPh0Re8lDO9z].mp3
#EXTINF:2,A Place We Knew
./A Place We Knew [3Pbvin812FYYIh8cnHSSEz].mp3
```
2. I tried the same thing with the beta version and got the same result.

## Steps to Reproduce
1. Open Namida.
2. Import any M3U file (a playlist from a local file).
3. Check the list of songs displayed.

## Screenshots
![Screenshot_2024-09-11-15-34-49-64_efbfb0790a8187cbd43560835da1b509](https://github.com/user-attachments/assets/7194622e-b499-469c-9892-ea5f3c3ab141)

## Logs
[logs_3.8.5_240805177.txt](https://github.com/user-attachments/files/16961684/logs_3.8.5_240805177.txt)

**Comment by MSOB7YY** [comment]
this seems like an issue with path parsing, the "Anne-Marie - 2002" is repeated on purpose right?

**Comment by MSOB7YY** [comment]
i did a fix in a0fc75e8cda7352bd27654c79dad36e43927a1f6, pls try out the beta v4.3.0 from https://github.com/namidaco/namida-snapshots/releases/

**Comment by Nadim147c** [comment]
Hey @MSOB7YY,
I updated to the [latest snapshot](https://github.com/namidaco/namida-snapshots/releases/tag/4.3.0-beta%2B240913231) and the metadata bug seems to be fixed. But invalid track is still existing. 

My “.m3u” files actually looked like this:
```
#EXTM3U

#EXTINF:0,Hold Of Me
./Hold Of Me [6dIZb64N6ICAWrf1RJrKfB].mp3

#EXTINF:1,7 Minutes
./7 Minutes [6FYbr9QzRoZPh0Re8lDO9z].mp3

#EXTINF:2,A Place We Knew
./A Place We Knew [3Pbvin812FYYIh8cnHSSEz].mp3
```
I thought empty lines couldn't cause any issue but turns out I was wrong. The issue is the empty lines, and removing them from the “.m3u” files fix all the playlist.

**Comment by MSOB7YY** [comment]
i see, thanks for literally debugging lmao i just added a check for empty lines just in case, will be available in 4.3.5 or later https://github.com/namidaco/namida-snapshots/releases, thank you <3

**Comment by ahmadnbl** [comment]
Hi! Sorry for bump this issue.

I think I got the same issue in here, cmiiw. I already try to use your latest beta atm (4.4.4) and I still got the issue. Here's the screen record and screenshot that might help to explain the issue.

<details>
<summary>Spoiler warning</summary>

https://github.com/user-attachments/assets/101d6d57-badc-4ae7-86d5-50a31a92296b


![Screenshot_20240920_201054](https://github.com/user-attachments/assets/2bca217c-7579-4363-8ebf-b3fefa486fd7)

</details>

The issue occurred when I try to play any music that came from playlist. The miniplayer and expanded fullscreen player is just showing the file name and not the metadata. But if I play it through the Tracks, Artist, or Album menu it works fine.

The content of my m3u8 playlist is looks like this, immediately giving the media path without any starting or ending comments/texts. This is auto-generated by some music-service importer. I don't know if these contents causing the issue.

```
../../Bring Me The Horizon/DArkSide - Single/01 DArkSide.m4a
../../Bring Me The Horizon/That's the Spirit/02 Happy Song.m4a
../../Bring Me The Horizon/Sempiternal (Deluxe)/04 Sleepwalking.m4a
../../Bring Me The Horizon/amo/02 MANTRA.m4a
../../Bring Me The Horizon/POST HUMAN_ SURVIVAL HORROR/03 Teardrops.m4a
../../Bring Me The Horizon/Kool-Aid - Single/01 Kool-Aid.m4a
../../Bring Me The Horizon/Sempiternal (Deluxe)/06 Shadow Moses.m4a
../../Bring Me The Horizon/POST HUMAN_ NeX GEn/05 liMOusIne (feat. AURORA).m4a
../../Bring Me The Horizon/AmEN! (feat. Lil Uzi Vert, Daryl Palumbo & Glassjaw) - Single/01 AmEN! (feat. Lil Uzi Vert, Daryl Palumbo & Glassjaw).m4a
../../Bring Me The Horizon/POST HUMAN_ SURVIVAL HORROR/06 Kingslayer (feat. BABYMETAL).m4a
../../Bring Me The Horizon/POST HUMAN_ SURVIVAL HORROR/02 Parasite Eve.m4a
../../Bring Me The Horizon/Sempiternal (Deluxe)/09 Antivist.m4a
../../Bring Me The Horizon/That's the Spirit/05 Follow You.m4a
../../Bring Me The Horizon/LosT - Single/01 LosT.m4a
../../Bring Me The Horizon/Sempiternal (Deluxe)/01 Can You Feel My Heart.m4a
../../Bring Me The Horizon/That's the Spirit/01 Doomed.m4a
../../Bring Me The Horizon/That's the Spirit/09 Drown (New).m4a
../../Bring Me The Horizon/That's the Spirit/03 Throne.m4a
```

**Comment by MSOB7YY** [comment]
@ahmadnbl i see, i will test ur m3u and improve parsing. apparently i didnt give much attention for relative paths

**Comment by MSOB7YY** [comment]
@ahmadnbl should be fixed in 156742a75f8b39b870b34c5180631a907430900b (beta v4.4.6 https://github.com/namidaco/namida-snapshots/releases/), can you check?

**Comment by ahmadnbl** [comment]
@MSOB7YY I'm sorry last week I'm on vacation so I just read your reply :D

I tried using latest beta 4.5.2 and it still not showing the metadata

https://github.com/user-attachments/assets/24e6c0bc-531f-4795-af80-e589dca798a6




If I compare the song properties that came from "Track Tab" and "Playlist Tab", here's the result

Track | Playlist
---|---
<img src="https://github.com/user-attachments/assets/da49e229-b73e-4e32-8da4-f3f36e268cdc" width=128/> | <img src="https://github.com/user-attachments/assets/dd91ec32-89d1-4a01-942e-a29f254970fe" width=128/>

**Comment by MSOB7YY** [comment]
@ahmadnbl damn its bcz one path starts with `/` and the other doesnt. u can fix by adding `/` in all paths in the m3u file or wait till i do smth about it ig

**Comment by MSOB7YY** [comment]
@Nadim147c u got the same issue as above? pls explain

**Comment by Nadim147c** [comment]
Sorry, I forgot to attach screenshots. 
| v4.3.0-beta | Latest snapshot |
| ----------- | --------------- |
| ![Screenshot_2024-10-15-16-30-48-81_efbfb0790a8187cbd43560835da1b509](https://github.com/user-attachments/assets/89171d22-af5f-4903-b7fb-3f4ecdbc3cce) | ![Screenshot_2024-10-15-16-37-21-89_76169158703de17dd8d9d0f5c2b96fc9](https://github.com/user-attachments/assets/5740fa19-5e4c-4995-84e7-f8c6b264d6b5) |

You fixed that issue but the issue on this comment/commit

> i did a fix in [a0fc75e](https://github.com/namidaco/namida/commit/a0fc75e8cda7352bd27654c79dad36e43927a1f6), pls try out the beta v4.3.0 from https://github.com/namidaco/namida-snapshots/releases/

**Comment by MSOB7YY** [comment]
@Nadim147c oh sorry forgot to mention this was also fixed few weeks back
latest beta is 4.7.0 now https://github.com/namidaco/namida-snapshots/releases

gonna close, feel free yall to reopen if any issue still exists

**Comment by MShekow** [comment]
@MSOB7YY I have a similar issue. However, the paths don't seem to be the problem. Here is the m3u file:

```
/storage/emulated/0/Music/LOS ASTROS/MI SALSA.MP3
/storage/emulated/0/Music/EL RUBIO LOCO/GOZALO.MP3
```
Namida shows the metadata of the first file correctly, but not for the second file.

I made the following observations:
* _Playing_ the second file works fine
* Opening the _tag editor_ also shows all the expected MP3 metadata for the second file
* I suspect that this has to do with the MP3 file itself, it is not a matter of order in the playlist. This bug occurs deterministically for that file in various playlists
* If I open "Edit tags" for the second song, make some random change, and save the tag changes, Namida now shows the metadata correctly.

If you want, I could send you the MP3 file via email of by other means.

**Comment by MSOB7YY** [comment]
@MShekow this looks very similar to #1046, we are having a discussion there, but TLDR: make sure the path in the m3u is identical to actual path, it's case sensitive

**Comment by MShekow** [comment]
I can confirm that the case-sensitivity is the issue, thank you.
