### ISSUE TITLE
[BUG] Removing all songs from playlist creates white translucent overlay

### ISSUE THREAD

**Issue by pheedback** [namidaco/namida#343]
I swipe left or right on songs to remove them from the play queue. When I swipe on the last remaining song in the queue a white translucent overlay appears and then I can't see to navigate around the app. I need to then close the app or sometimes force close it to be able to use the app.

## Expected Behavior
The songs sould be removed from the play queue.

## Current Behavior
A white translucent overlay appears covering the screen

## Steps to Reproduce
1. Add a song or songs to the play queue.
2. Bring up the play queue.
3. Swipe right or left on all of the songs to remove them from the queue.
4. The white translucent overlay will appear.

## Screenshots
No screenshot sorry.

## Logs
Sorry no logs

## Possible Solution
Sorry no help

**Comment by MSOB7YY** [comment]
just fixed in a0fc75e8cda7352bd27654c79dad36e43927a1f6, please try beta v4.3.0 from here https://github.com/namidaco/namida-snapshots/releases/
