### ISSUE TITLE
[QUESTION] Album Sort Order

### ISSUE THREAD

**Issue by pheedback** [namidaco/namida#347]
I might be doing something wrong or not doing something to make it work so posting as a question. When I go to the Artists page and click on an Artist the albums are not sorted by year. The albums are not even sorted by title. How do I sort albums by year? 
![Screenshot_20240917-093929](https://github.com/user-attachments/assets/c4907735-8a1f-4243-86ef-43d3a768e169)

**Comment by MSOB7YY** [comment]
yeah they are not really sorted, just extracted by the order of the tracks, i should do a sorting for them which will be based on the same sort for the albums page

**Comment by pheedback** [comment]
Yes please allow sorting of the albums in the artist specific page. I prefer to navigate to a specific artist and being able to sort their albums would be very good. The app is awesome, but that feature would make it almost the best.

**Comment by pheedback** [comment]
Closing the ticket as my question was answered.

**Comment by MSOB7YY** [comment]
nooo ill leave it open until its done, also the albums won't have a separate sort, **they will follow the same sort specified in the albums page**
