### ISSUE TITLE
[BUG] Remove tracks from currently playing queue

### ISSUE THREAD

**Issue by pheedback** [namidaco/namida#348]
I have added tracks from an album to the default playing queue and select tracks. I then click on the paintbrush to remove them from the queue, but they don't go off the list.

## Expected Behavior
Remove tracks from the play queue

## Current Behavior
Removes 0 tracks

## Steps to Reproduce
1. Go to an album
2. Click Play Last
3.Click on the mini player
4. Pull up the list of queued tracks
5. Select multiple tracks
6. Click the paint brush to remove the tracks from the queue

## Screenshots
![Screenshot_20240917-102002](https://github.com/user-attachments/assets/1978da61-0317-4633-b571-a3958335e99c)
things easier-->

## Logs
No logs sorry

## Possible Solution
Not sure if I am doing something wrong, but seems it should be removing the tracks.

**Comment by pheedback** [comment]
That screenshot says it removed tracks, but it did not. This one shows no tracks removed.
![Screenshot_20240917-103005](https://github.com/user-attachments/assets/d150b2a9-ba42-48c9-8c43-d2c4f33de9eb)

**Comment by MSOB7YY** [comment]
if you long press the icon, it will tell u what it does. this icon is for removing duplicated items. if you want to remove tracks from queue, simply swipe right or left

**Comment by pheedback** [comment]
Okay so then is it possible to remove all tracks from the queue at one time or do we have to swipe left or right in each one?

**Comment by Piyush1625** [comment]
No , you have to do it by swiping each left or right.

**Comment by MSOB7YY** [comment]
@pheedback as piyush said. if u want to clear the whole queue, make sure dismissible miniplayer is enabled in playback settings, and then swipe down the miniplayer
