### ISSUE TITLE
[ISSUE] Phone doesn't meet security requirements when player is installed

### ISSUE THREAD

**Issue by 042j2ppmg0** [namidaco/namida#350]
Hi, if I install the player I can't use Google Wallet to pay contactless anymore because "Phone doesn't meet security requirements":
https://support.google.com/wallet/answer/12200245
When I have it uninstalled I don't have any issue paying. There are no other differerences on the phone.
Should I be worried of this app?

## Expected Behavior
Security requirements should be met and NFC contactless payments should work.

## Possible Solution
Maybe having the app installable from a store (Play Store or F-Droid)?

**Comment by VerySweetBread** [comment]
Google Wallet's issue, I guess, try another payment app

**Comment by MSOB7YY** [comment]
hey sorry for being late, which version is this?

**Comment by 042j2ppmg0** [comment]
> hey sorry for being late, which version is this?

Namida: latest release (3.8.5)
Google Wallet: latest and previous ones too
Android: 12

Do you need anything else?

**Comment by MSOB7YY** [comment]
not in particular, i dont think gwallet can scan for apps. if play protect says that namida is safe then everything should be fine.
i found this thread too https://www.reddit.com/r/GooglePixel/comments/s8ji8p/google_pay_reports_that_phone_doesnt_meet
which they all agree on how weird google wallet app is.
looked into official forums too (even the link u sent) and found nothing related to apps installed, this is probably not a namida issue.
i u can do more tests tho to check would be nice
