### ISSUE TITLE
[BUG] FormatException: Unexpected character (at character 1) SyntaxError: unexpected line terminator in regexp

### ISSUE THREAD

**Issue by SREESANTH373737** [namidaco/namida#354]
unable to play music or video 

## Expected Behavior
 it should play audio and video 

## Current Behavior
showing error ![Screenshot_20240926-003644.png](https://github.com/user-attachments/assets/d1edce88-dd21-450f-a175-c1fdc42a33c5)

## Steps to Reproduce

1. Just play any video in history 
2.
3.
4.

## Screenshots
yes

**Comment by VerySweetBread** [comment]
Version?

**Comment by AppleMangoOrange** [comment]
> > go to youtube settings -> flags at top right -> set client to ios
> 
> [From Discord](https://discord.com/channels/1156253663803740271/1156253664789397607/1288444931089629286)

Thank you for the solution. For future reference (and for others looking to fix this issue), the error shown is:

```
Error: FormatException: Unexpected character (at character 1)

SyntaxError: unexpected line

terminator in regexp

Error computing sig
```

**Comment by MSOB7YY** [comment]
@VerySweetBread thanks lmao

@AppleMangoOrange pls note that ios client has limited quality options

this whole thing is fixed in beta v4.5.0

> 1. update to beta v4.5.0 from here (use clone if u want to test it as a separate app) <https://github.com/namidaco/namida-snapshots/releases> 
> 2. optional: go to settings -> youtube -> flag icon at top right -> `REFRESH_JS_PLAYER` & make sure `INNERTUBE_CLIENT` is set to `Default`

**Comment by SREESANTH373737** [comment]
Then when we will get major update than this beta update?

**Comment by MSOB7YY** [comment]
@SREESANTH373737 no idea yet. most stuff are pretty stable already except for video indexing & playback. it can crash sometimes and tag editing is not very stable
