### ISSUE TITLE
[FEATURE REQUEST] Jellyfin Library addition

### ISSUE THREAD

**Issue by archziac** [namidaco/namida#356]
Would like this app to make it so that we can add Jellyfin music library.

**Comment by MSOB7YY** [comment]
there are no plans sadly, similar requests #38, #334, #91, #153

**Comment by MSOB7YY** [comment]
a bit too late but we have support for jellyfin and other providers in latest versions ^^ https://github.com/namidaco/namida-snapshots/releases
