### ISSUE TITLE
[FEATURE REQUEST]  from #344

### ISSUE THREAD

**Issue by SREESANTH373737** [namidaco/namida#358]
By the request of feature request #344 by me 

Here I requestly wanted to change the colour of video  scroll bar from solid colour to multiple colours like the instagram app background colour and for extra details I have sent a pic 

![Screenshot_20241001-013826~2.png](https://github.com/user-attachments/assets/0fd1f895-22ad-4128-8ba0-03be1ea4115b)

By @SREESANTH373737

**Comment by MSOB7YY** [comment]
so u basically mean gradient. sorry that still won't be possible. extra work on the gpu and unneccesary distraction

**Comment by MSOB7YY** [comment]
the local waveform bar has gradient tho, but it might not be very visible bcz both colors are kinda similar. i did it there for slight better look with the wave bar, while up here in yt player it won't be even worth or noticeable at all. unless u mean 2 different colors?

**Comment by SREESANTH373737** [comment]
Ok no problem , it's is best to keep the graphics low by increasing performance good idea 😉
