### ISSUE TITLE
[FEATURE REQUEST] prioritize embedded lyrics over online fetching

### ISSUE THREAD

**Issue by KyoHisoka** [namidaco/namida#36]
When it comes to my local library I usually make my own synced lyrics and then embed them into the files, it seems namida fetches these lyrics on its own, which is very convenient, but an option to use the embedded lyrics instead in case it fails to find them online would be great

**Comment by MSOB7YY** [comment]
hello kyo, if i understand correctly, you want to prioritize embedded lyrics over online fetching, am i right?

**Comment by KyoHisoka** [comment]
> hello kyo, if i understand correctly, you want to prioritize embedded lyrics over online fetching, am i right?

Yes, that'd be a better way to phrase it

**Comment by MSOB7YY** [comment]
thanks for the suggestion, implemented in b3e1ee11d928d8ce7be8732178649119f12a399b 🌺

**Comment by KyoHisoka** [comment]
> thanks for the suggestion, implemented in [b3e1ee1](https://github.com/namidaco/namida/commit/b3e1ee11d928d8ce7be8732178649119f12a399b) 🌺

Awesome, tyvm!
