### ISSUE TITLE
[ISSUE] after downloading a video+ audio the same song cannot be played in playlist, showing source error also tried to download audio only but it is showing already downloaded with no option to delete the downloaded song in app.

### ISSUE THREAD

**Issue by Rishabhknp666** [namidaco/namida#360]
as stated in title

## Expected Behavior

Song should have played
Also the downloaded songs are stored in namida folder's download and that folder is not visible in namida app
## Logs

[logs_tagger_3.1.7-beta_240711002.txt](https://github.com/user-attachments/files/17218749/logs_tagger_3.1.7-beta_240711002.txt)
[logs_3.1.7-beta_240711002.txt](https://github.com/user-attachments/files/17218750/logs_3.1.7-beta_240711002.txt)
[logs_clean_3.1.7-beta_240711002.txt](https://github.com/user-attachments/files/17218751/logs_clean_3.1.7-beta_240711002.txt)

**Comment by Rishabhknp666** [comment]
Also previously if without premium feature of we liked the video it would be added but in the new update it says to sign in to account. Can you make it to go back to same feature please.

**Comment by MSOB7YY** [comment]
update to [v3.8.5 stable](https://github.com/namidaco/namida/releases) or [v4.5.0 beta](https://github.com/namidaco/namida-snapshots/releases).

> Also previously if without premium feature of we liked the video it would be added but in the new update it says to sign in to account. Can you make it to go back to same feature please.

the previous like button just added the video to a local yt favourites playlist. this is now accessible by pressing menu then `favourites`. or just add it to favourite playlist manually

the current like button is linked with ur gaccount

**Comment by Rishabhknp666** [comment]
The source error problem still exists while many other songs which used to previously play also show source error, any idea what maybe causing it as most of the songs play just fine. And thanx bro for this app.

**Comment by MSOB7YY** [comment]
@Rishabhknp666 try clearing cached files for that video bcz it can cause issues sometimes. press the menu -> clear -> select video & audio cache -> delete
