### ISSUE TITLE
[QUESTION] Animated album Art

### ISSUE THREAD

**Issue by pheedback** [namidaco/namida#363]
I thought that animated album Art is a thing on the app, but how does one go about making it show up? So when the player is playing the music I would like to show the cover as an animation.

Animated artwork something like at the link.
[](https://youtu.be/JfQX3Fwgg8M?si=dzd3_iARJiDuBv9c)

## Screenshots
No screenshot

## Logs
No logs

**Comment by pheedback** [comment]
Not sure if link posted.
https://youtu.be/JfQX3Fwgg8M?si=dzd3_iARJiDuBv9c

**Comment by MSOB7YY** [comment]
hmmm have u missed this section? https://github.com/namidaco/namida?tab=readme-ov-file#video-integration

in your case, copy `https://youtu.be/JfQX3Fwgg8M` and put it in the track comment tag
or put the id in the filename like this `artist - title v=JfQX3Fwgg8M` (and refresh library after)

and then just make sure video playback is enabled (by pressing the audio button in player bottom left, or from playback settings)
