### ISSUE TITLE
[FEATURE REQUEST] You must add a sleep timer.😮‍💨

### ISSUE THREAD

**Issue by Edward079** [namidaco/namida#364]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Apps**
Add any other known apps/service that does this in a good way

**Comment by MSOB7YY** [comment]
sorry i will not do that.

bcz its already there
![Screenshot_20241005-123322_Namida](https://github.com/user-attachments/assets/53e6c3e0-fa78-4f44-9db5-1661e58c5aad)
