### ISSUE TITLE
[BUG] won't let me download audio

### ISSUE THREAD

**Issue by Daniel10-jpg** [namidaco/namida#372]
Went to download some new music and as usual searched for it, tapped downloaded and then removed the video option as I only need audio but instead of downloading as normal it gave me an error message saying something about innertube. Messed around with settings and then it gave me a different error message(screenshot below)

## Expected 
When tap on download button it should download the song 

## Current Behavior
When i tap download an error message pops up 

## Steps to Reproduce
1. Search song 
2. Download audio only 

## Screenshots
![Screenshot_20241017_083037](https://github.com/user-attachments/assets/ae8cc60c-9cb4-4147-b690-a738db3d4c4b)

## Logs
{
  "android": {
    "product": "e3qxeea",
    "supportedAbis": [
      "arm64-v8a"
    ],
    "serialNumber": "unknown",
    "display": "UP1A.231005.007.S928BXXS2AXD6",
    "type": "user",
    "isPhysicalDevice": true,
    "version": {
      "baseOS": "samsung/e3qxeea/e3q:14/UP1A.231005.007/S928BXXU1AXCB:user/release-keys",
      "securityPatch": "2024-05-01",
      "sdkInt": 34,
      "release": "14",
      "codename": "REL",
      "previewSdkInt": 0,
      "incremental": "S928BXXS2AXD6"
    },
    "manufacturer": "samsung",
    "tags": "release-keys",
    "bootloader": "S928BXXS2AXD6",
    "fingerprint": "samsung/e3qxeea/e3q:14/UP1A.231005.007/S928BXXS2AXD6:user/release-keys",
    "host": "SWDK6710",
    "isLowRamDevice": false,
    "model": "SM-S928B",
    "id": "UP1A.231005.007",
    "brand": "samsung",
    "device": "e3q",
    "board": "pineapple",
    "hardware": "qcom"
  },
  "package": {
    "appName": "Namida",
    "buildNumber": "241011011",
    "packageName": "com.msob7y.namida",
    "version": "4.5.5-beta",
    "buildSignature": "CB8C070CBDB5E2350ACBAC4DDB1A9DEE89816ECDAFD116D41EFFC14890D98E1C",
    "installerStore": "com.google.android.packageinstaller"
  }

**Comment by MSOB7YY** [comment]
that was the usual yt updating their player code and possibly breaking any dependant.

go to youtube settings -> flag icon at top -> change client to ios

**Comment by Daniel10-jpg** [comment]
Thank you love using this app it's great and looks unique feels premium compared to others keep it up

**Comment by MSOB7YY** [comment]
ty so much cutie 💞
