### ISSUE TITLE
[BUG] Error playing video

### ISSUE THREAD

**Issue by Notesuree** [namidaco/namida#376]
It gives an error message when playing the video

## Expected Behavior

Play the video stably

## Current Behavior

https://github.com/user-attachments/assets/95158d6d-d6e6-427f-8a8b-a0fc5b4ca9b1

## Steps to Reproduce

1. https://www.youtube.com/watch?v=Ze0-2_GmzWk / play
2. Error playing video / Not always

## Screenshots

I sent a video

## Logs

[logs_3.8.5_240805177.txt](https://github.com/user-attachments/files/17449676/logs_3.8.5_240805177.txt)
[logs_tagger_3.8.5_240805177.txt](https://github.com/user-attachments/files/17449678/logs_tagger_3.8.5_240805177.txt)

## Possible Solution

Maybe youtube is blocking. The application does not support DASH/auto quality

**Comment by MSOB7YY** [comment]
this might be an issue with caching. open the video menu -> clear -> clear audio and video cache
