### ISSUE TITLE
[FEATURE REQUEST] Jellyfin support

### ISSUE THREAD

**Issue by Piecuuu** [namidaco/namida#379]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Jellyfin music streaming support

**Describe alternatives you've considered**
What you can do right now, is download the music externally, but that's not quite streaming it.

**Additional context**
N/A

**Apps**
Finamp

**Comment by MSOB7YY** [comment]
duplicate of #356.
the focus currently is on local & yt. no plans to support other streaming services even if its local

**Comment by MSOB7YY** [comment]
a bit too late but we have support for jellyfin and other providers in latest versions ^^ https://github.com/namidaco/namida-snapshots/releases
