### ISSUE TITLE
[ISSUE] The undo button is the wrong colour

### ISSUE THREAD

**Issue by FastCocobo** [namidaco/namida#382]
I pressed undo ans the button was purple instead of my blue

## Expected Behavior
It should be the same colour as you set it to in settings

## Screenshot
![Screenshot_20241027_182705](https://github.com/user-attachments/assets/899dd57f-f792-44be-b70d-35c21e257b27)

## Possible Solution
Make it the same colour

**Comment by MSOB7YY** [comment]
buttons have different theming/colors, it makes more sense with light mode or when pitch black is disabled
