### ISSUE TITLE
[ISSUE] Cover image embedded in .flac file does not load systematically.

### ISSUE THREAD

**Issue by TheFlomax** [namidaco/namida#384]
## Expected Behavior
The application should load and display the embedded cover image of each track in the playlist automatically without requiring manual intervention.

## Screenshots
 
![image](https://github.com/user-attachments/assets/8cb27cb9-d66b-4cb9-a129-2c3a7c025216)
![image](https://github.com/user-attachments/assets/4d0f2f36-93ce-4e43-9b1c-5d5d24a78626)

## Possible Solution
The application could be updated to automatically detect and display embedded cover images for each track without relying on an external file like “cover.jpg.” This would streamline the process and make it consistent with other players that handle this functionality without issue.

**Comment by MSOB7YY** [comment]
which version is this? we have files of various type and their thumbnails are all extracted and displayed properly.
also did u refresh/reindex or is this an m3u playlist??

**Comment by iWisp360** [comment]
Also happening to me. All my songs are in .flac format and Namida doesn't detect them, but another players and my file manager does. Tried reindexing and nothing happened

**Comment by MSOB7YY** [comment]
there was a recent issue regarding this, can yall try [v3.8.1](https://github.com/namidaco/namida-snapshots/releases), reindex  and see?

**Comment by iWisp360** [comment]
Yes, it's solved in the latest version

**Comment by MSOB7YY** [comment]
@TheFlomax should be fixed for u too. pls reopen if u still face it after doing https://github.com/namidaco/namida/issues/384#issuecomment-2536047386

**Comment by TheAweSum1** [comment]
hi, I'm also facing the same issue. But with .opus file. .mp3 files show their album art normally. Tried the mentioned 4.8.1 , as well as 4.9.2 but it simply aint working. Other music players like AIMP for example do show the album art. i think the album arts pretty important and i reallyreally like namida's UI so i would like to use it. Please guide me on how to fix it or if it can be fixed, thanks!

**Comment by MSOB7YY** [comment]
@TheFlomax lets continue in ur opened issue

for anyone here having the same issue, make sure ur on v4.9.7 or later https://github.com/namidaco/namida-snapshots/releases

**Comment by TheFlomax** [comment]
> [@TheFlomax](https://github.com/TheFlomax) lets continue in ur opened issue
> 
> for anyone here having the same issue, make sure ur on v4.9.7 or later https://github.com/namidaco/namida-snapshots/releases

Personally, I don't use the application any more as I've set up a Subsonic server, but I'd be delighted to help if I can.

**Comment by MSOB7YY** [comment]
ah i see, thank u u already did help, have fun using it 💖
