### ISSUE TITLE
[QUESTION] I can't add track 

### ISSUE THREAD

**Issue by Reoackerman** [namidaco/namida#386]
I can't add tracks i tried adding song folder to excluded but it doesn't work

## Logs

[0.zip](https://github.com/user-attachments/files/17590898/0.zip)

**Comment by Reoackerman** [comment]
Can you explain me what is indexer folder it the excluded folder right in the library settings

**Comment by MSOB7YY** [comment]
excluded means you dont want that folder (and all subfolders)

add your music folders to the "list of folder", if u enabled "media store" then it will rely on it and not the folder system so u probably need to turn that off

let me know if u have further questions

**Comment by Reoackerman** [comment]
How do i disable media store

**Comment by Reoackerman** [comment]
Even if i did everything the scanning takes all lot time and gets stuck in
50% doesn't go more than that

**Comment by MSOB7YY** [comment]
i made improvements for this part in beta 4.6.7, can u try it? https://github.com/namidaco/namida-snapshots/releases
