### ISSUE TITLE
[BUG] Lyrics not syncing after opening expanded view

### ISSUE THREAD

**Issue by ToolDroidYT** [namidaco/namida#387]
Lyrics stops syncing when opening in expanded view and closing it

## Expected Behavior

Lyrics should continue syncing when in normal vew

## Current Behavior

Lyrics stops syncing and just stays in the line where it last synced when opening the expanded lyrics view

## Steps to Reproduce

1. Play a song with lyrics enabled
2. Expand lyrics (by long pressing)
3. Close expanded view
4. *normal view lyrics not syncing to musi

## Screenshots

https://github.com/user-attachments/assets/68e1cc05-946a-4e02-a77d-74a04417edfd

## Logs

HEHE

## Possible Solution

Check when the expanded view is closed and resume syncing on the normal view lyrics? IDK
Disabling/enabling lyrics syncs it again.

**Comment by MSOB7YY** [comment]
this has been fixed long ago in beta https://github.com/namidaco/namida-snapshots/releases/

not sure when the next stable is but should be soon
