### ISSUE TITLE
[ISSUE] Waveform is not displaying

### ISSUE THREAD

**Issue by fakeowl1** [namidaco/namida#390]
OS: Lineage 21 Unofficial
Android: 14

## Screenshots
![photo_2024-11-04_23-11-14](https://github.com/user-attachments/assets/495c9e8d-49dc-4a3e-9ee2-4e5e65287ff7)

## Logs
[logs_3.8.5_240805177 (2).txt](https://github.com/user-attachments/files/17623873/logs_3.8.5_240805177.2.txt)
Another log file is empty idk why

**Comment by Antiwh0re** [comment]
I confirm. And it happens seemingly randomly - one song has the waveform, and then the next one from the same album in the same format doesn't have it. My OS is based on Android 11.

**Comment by MSOB7YY** [comment]
this most likely due to the format being unsupported by the waveform library, can u send a sample file?

**Comment by MSOB7YY** [comment]
@fakeowl1 
what da..
![Screenshot_20241106-153025_Namida](https://github.com/user-attachments/assets/73af8ca2-759c-4002-af7b-d6806cd9e673)

**Comment by MSOB7YY** [comment]
i forgot to ask are these playing from yt or they local? cuz if yt, it needs to be fully cached/downloaded first

**Comment by fakeowl1** [comment]
@MSOB7YY 
I downloaded from YouTube

**Comment by MSOB7YY** [comment]
damn thats crazy

**Comment by Antiwh0re** [comment]
It's not just youtube. It happens to local files as well. And I've written above that it's not a certain format issue - app shows the wave for one song of certain format and then fails to show it for the next song of the same format.

**Comment by MSOB7YY** [comment]
so "sentinel" and "tomorrow never ends" both **still** doesnt show waveform no matter what?

**Comment by Antiwh0re** [comment]
As stupid as it is, they don't. I've just launched the player again (it was truly closed) and despite a fresh start they're still not showing. Pro Victoria is showing, some other songs are showing too, but these don't (and some others don't). And these are all from the same album, thus encoded in the same way!

**Comment by MSOB7YY** [comment]
i dont think being in the same album gurantees same encoding, the underlying library for waveform is based on ffmpeg, if it extracted a format successfully once then it will always.
i asked for a sample and it showed fine on my device so i suspect it might be smth with ur device/android version.
anyways i will check again using android 14 emulator and see how it goes, if u can send these 3 tracks it would help more

**Comment by Antiwh0re** [comment]
As me and the author have different Android versions (14 vs 11), version is not the reason.
Flac files are big in size, so I'll send 2 tracks - one that shows wave and one that doesn't. I'll wrap them in archives and split in volumes and wrap volumes again, so that Shithub let them through. Let me know if you can't unwrap them.
[track1.zip](https://github.com/user-attachments/files/17717782/track1.zip)
[track2-1.zip](https://github.com/user-attachments/files/17718209/track2-1.zip)
[track2-2.zip](https://github.com/user-attachments/files/17718345/track2-2.zip)

**Comment by Antiwh0re** [comment]
Have you managed to unwrap these files?

**Comment by MSOB7YY** [comment]
@Antiwh0re yes, and both show waveform perfectly fine

![Screenshot_20241117-230008_Namida](https://github.com/user-attachments/assets/6783ba81-e2a4-40e5-885d-888e00950551)
![Screenshot_20241117-225952_Namida](https://github.com/user-attachments/assets/46c47b4f-ffee-4b3b-b5d6-aff99d2a9061)

**Comment by Antiwh0re** [comment]
This proves my point - it's not an issue with a certain format, but with the program itself (or Android). And it manifests itself irregularly.

**Comment by fakeowl1** [comment]
I change my rom to crDroid Android 15. Everething works fine.

**Comment by fakeowl1** [comment]
![image](https://github.com/user-attachments/assets/3335c841-1641-495c-a120-b404510b85b2)

**Comment by MSOB7YY** [comment]
yippiee

**Comment by Antiwh0re** [comment]
@MSOB7YY, and what version did you test it on?

**Comment by MSOB7YY** [comment]
@Antiwh0re v4.7.0 and generally previous versions cuz i changed nothing related to that part

**Comment by Antiwh0re** [comment]
I meant Android version. But as you mentioned the program itself, I thought you published all releases here, but now I see that this version is not here (I'm using 3.8.5, which is the latest here).

**Comment by MSOB7YY** [comment]
@Antiwh0re im using android 11, beta versions are available here https://github.com/namidaco/namida-snapshots/releases

**Comment by MSOB7YY** [comment]
namida doesnt rely on system covers unless u enabled "media store" so yah

about waveform its not android that provide this data but a dedicated library based on ffmpeg (Amplituda), it caches what was extracted successfully, otherwise u can still clear waveform cache by selecting tracks -> dialog -> advanced -> clear -> waveform. altho this might not help, if it didnt extract then thats how it is, can do nun about it hehe

**Comment by Antiwh0re** [comment]
This media store is disabled. I don't see Waveform in that menu you pointed to (just lyrics and artwork), but now the waveform is shown for those files. I've recently rebooted the device, this may be the reason.

**Comment by MSOB7YY** [comment]
wow a reboot does allat 💀

**Comment by MSOB7YY** [comment]
@Antiwh0re @fakeowl1 there was also a small bug that might caused this issue, fixed in 3.8.0 so if anyone still face it u can try that version https://github.com/namidaco/namida-snapshots/releases
