### ISSUE TITLE
[FEATURE REQUEST] option to not remove song from queue when I swipe leeft or right

### ISSUE THREAD

**Issue by victorjon68** [namidaco/namida#391]
When swiping up/down and navigating the queue I sometimes swipe right by mistake, which removes a song from queue and is I am not fast enough I miss the undo prompt. Can you maybe add an option to disable that gesture?

**Comment by MSOB7YY** [comment]
not really sure since queue is supposed to be flexible and there is no other way to remove it from queue currently
