### ISSUE TITLE
[ISSUE] 
art work glitch

### ISSUE THREAD

**Issue by AbhishekSingh-glitch** [namidaco/namida#392]
sometimes any random art work of any song is attached to all songs when they are playing 

## Screenshots

![Screenshot_2024_1107_135645.png](https://github.com/user-attachments/assets/f55015ae-755e-4611-a3f1-645883a48faa)

![Screenshot_2024_1107_135715.png](https://github.com/user-attachments/assets/81de470b-a3bb-4258-b542-bd79478035f4)

**Comment by MSOB7YY** [comment]
just recently knew that media store can also provide non-accurate artworks. thanks for confirmation lmao imma disable the media store artwork fallback if the option is disabled

it might be also that ur tracks have the same filename (bcz artworks are organized by filenames)

can u open track dialog -> edit tags
and send screenshot? we need to confirm the exact artwork of these songs and the file name
