### ISSUE TITLE
[FEATURE REQUEST] Sorting in Folder and Playlists

### ISSUE THREAD

**Issue by amanyadav-s** [namidaco/namida#393]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Apps**
Add any other known apps/service that does this in a good way

**Comment by MSOB7YY** [comment]
sorting in folders is already possible
sorting in playlist is duplicate of #164

**Comment by MSOB7YY** [comment]
sorting in playlists was added in v4.8.6 https://github.com/namidaco/namida/releases
