### ISSUE TITLE
[FEATURE REQUEST] Hi-Fi support 

### ISSUE THREAD

**Issue by Sumith3699** [namidaco/namida#395]
Hey my smartphone has a Hi-fi chipset but in my smartphone this app is not supported (not shown in the list) can you add Hi-fi support 

![IMG_20241109_015207.jpg](https://github.com/user-attachments/assets/6e754fa8-4fe2-42a7-b8b3-7a327e2b9dfd)

**Comment by MSOB7YY** [comment]
im pretty sure this is a custom list made by ur phone provider, do u know any other external app (preferably open source) that shows on the list?

**Comment by Sumith3699** [comment]
> im pretty sure this is a custom list made by ur phone provider, do u know any other external app (preferably open source) that shows on the list?

The only open source i could see work is VLC 
I couldn't find any other music players that work :)

**Comment by MSOB7YY** [comment]
then it's probably as i said. not smth from our side

**Comment by MSOB7YY** [comment]
the fact that snapchat is included makes it crystal clear ☠️☠️

**Comment by Sumith3699** [comment]
Yeah i looked for some open source if any are compatible but sadly none just have to enjoy what i have now 
Thanks anyway

**Comment by Sumith3699** [comment]
Hey bro there's one more issue im getting  a loud glitchy noise when im on Wired earphones and turn off the Equalizer It's gotten annoying :(

**Comment by MSOB7YY** [comment]
yo welcome mate 💖

**Comment by Sumith3699** [comment]
> Hey bro there's one more issue im getting  a loud glitchy noise when im on Wired earphones and turn off the Equalizer It's gotten annoying :(

Any solution for this ?
I tried the earphones on  other software but there is no problem but here there's a loud glitchy noise for a second when i turn off Equalizer

**Comment by MSOB7YY** [comment]
u mean the equalizer inside namida right? u should at least pause playback before switching bcz there might be a delay while changing the audio processor

i haven't faced this before tho and im using a system equalizer so u might do that too

**Comment by Sumith3699** [comment]
> u mean the equalizer inside namida right? u should at least pause playback before switching bcz there might be a delay while changing the audio processor
> 
> i haven't faced this before tho and im using a system equalizer so u might do that too

Yeah the one inside namida 
It's ok when it's in low volume but at mid to high volume it's gonna burst your eardrum 🫨
Anyways i just wanted to inform you that, look into it if possible fix it in future and take you time 
Peace out ✌🏻

**Comment by MSOB7YY** [comment]
thanks, not sure if i can do smth about it tho but will try

**Comment by Sumith3699** [comment]
> thanks, not sure if i can do smth about it tho but will try

No worries bro take your time
