### ISSUE TITLE
[FEATURE REQUEST] Speed configuration streamed from memory to avoid distortion

### ISSUE THREAD

**Issue by Ceynou** [namidaco/namida#397]
**Is your feature request related to a problem? Please describe.**
Changing speed doesn't change the pitch as it should, otherwise it has really annoying audio distortion 

**Describe the solution you'd like**
Anything that prevents the above problem

**Describe alternatives you've considered**
I don't know what that means

**Additional context**

**Apps**
foobar2000 has the speed and the tempo sliders, the latter keeps the same pitch, but you I guess you would like to let the user set an arbitrary pitch

mpv keeps the pitch by default and you can change that behavior with this argument `audio-pitch-correction=no`

Thanks for this great app!

**Comment by MSOB7YY** [comment]
exoplayer has separate speed and pitch, why would u hate/dislike a separated speed/pitch controls? for me at least i keep them slightly different which removes distortion and allow custom values
linking both doesn't sound good to me

**Comment by Ceynou** [comment]
I don't know where you saw that I didn't want separate controls

I just don't want the song to sound like ass when setting both the speed and the pitch to 50%, could be an another option

but I don't know how exoplayer works, I only know a game that uses the bass library, and optionally when it reads the audio from memory it automatically ""scales" the pitch to the speed without distortion (bad quality audio)

**Comment by MSOB7YY** [comment]
sorry dealing with audio filters/etc is not my expertise, for a similar behavior that u asking for, there might be a need to write a specific advanced filter as i didnt find any related issues/etc

but isnt distortion a must specially when putting it at half the speed?

**Comment by Ceynou** [comment]
Actually I think we get no distortion, so like the slow motion effect, without filter, but I barely know anything about audio decoding

I don't know it seems everyone wants half the speed with the same pitch as normal pitch and I really don't get it, to me it's like listening to a 32kbps mp3.

Feel free to close it, I have nothing else to add

**Comment by MSOB7YY** [comment]
> it seems everyone wants half the speed with the same pitch as normal pitch and I really don't get it

it's just that pitch should not be linked with speed, otherwise u might start hearing alien voices
u may put speed to 50% (idk who does that) and pitch to 70%-80% for example and that should do it. there is no magic solution as far as i know unless u discover a way to fill the missing gaps

**Comment by MSOB7YY** [comment]
i am pretty sure "playback rate" internally changes both but with reasonable amount, have u tried setting speed to 60%-70% and pitch to -4 or -6 ? try getting the values that sounds like playback rate of 50% and let me know

**Comment by MSOB7YY** [comment]
oh haha it's not like i dont want to do it it's just that the only possible configuration exposed by exoplayer is speed and pitch. nothing about playback rate. so the naming confused me at first until u sent da video
so yah and ffmpeg is only used as a fallback decoder so no options are exposed for it

here is a similar thing in newpipe https://www.reddit.com/r/NewPipe/comments/v8doz6/pitch_shift_algorithm/, they treat pitch -12 as 50%, but still manually changed, not automatically like playback rate

**Comment by Ceynou** [comment]
Okay I see now, interesting, well thanks for sticking with me until the end haha
