### ISSUE TITLE
[BUG] latest release crash

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#40]
installed latest arm (32) apk, it crashes but indexer keeps running on every start and the crashing (local songs are over 300 though).

install a old version with doesn't crash, yet.

**Comment by MSOB7YY** [comment]
hello, can you confirm wether it crashes on v1.4.8 and v1.3.0 or not? this might be due to concurrent tags extractions introduced in v1.4.8

**Comment by MSOB7YY** [comment]
so it's working fine on v1.4.8?
and crashing on v1.5.4?

-----
- currently videos are automatically played when
1. track has a youtube link
2. there is a "linked" local video to the music
> refer to [video-integration](https://github.com/namidaco/namida#video-integration) for more info

- i should focus on bringing full video support soon, it was initially delayed to after few stuff be ready, like:
   - [x] video player screen (and related gestures)
   - [x] general queue system 
   - [x] general history system
   - [x] general playlist system
   - [x] heirarchy view for files
   - [x] video tags (information) extractor (and editor if needed)
- now that all these stuff are ready, only thing left is a UI adaptation, shouldn't be so hard but gonna require some time, gonna work on it soon isa

**Comment by MSOB7YY** [comment]
@idontveapc can you please check again on v1.6.8?

**Comment by MSOB7YY** [comment]
glad its working fine now, closing as done.
-----
and yeah local videos is soon, after few YouTube related stuff
