### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SREESANTH373737** [namidaco/namida#403]
Well I have words to tell this but it doesn't let me to play audio or vid it shows error as this in pic ![Screenshot_20241121-000732~2.png](https://github.com/user-attachments/assets/fa3959e2-0271-49a7-b9ee-b4b557996976)

**Comment by MSOB7YY** [comment]
things are fine in beta https://github.com/namidaco/namida-snapshots/releases 
use it or wait next stable soon

**Comment by SREESANTH373737** [comment]
@MSOB7YY  well my app is beta updated version (latest)  but stillll I am getting same error

**Comment by SREESANTH373737** [comment]
![Screenshot_20241121-124449.png](https://github.com/user-attachments/assets/5bd0033c-9ef7-4e54-a321-d247caee283d)

See

**Comment by MSOB7YY** [comment]
oh in that case try to clear the audio/video cache of that video
press this menu button on the right -> clear -> select all and delete
![image](https://github.com/user-attachments/assets/1cda721b-dd0e-4c71-8aa2-292d7c6ac6d4)

and then close and play again

**Comment by SREESANTH373737** [comment]
![Screenshot_20241122-014313.png](https://github.com/user-attachments/assets/fac0842d-9e27-4c03-8eff-ceccc0620573)

![Screenshot_20241122-014326.png](https://github.com/user-attachments/assets/09a69c8d-d1d1-4ff3-9623-219a44c1bbaf)

Still same but there is no audio or vid data is formed all is empty

**Comment by MSOB7YY** [comment]
does this happen with all videos? and what quality u are choosing? 2k+ av1 might not work
also send logs from settings->about pls

**Comment by SREESANTH373737** [comment]
-![logs_4.7.1-beta_241120014.txt](https://github.com/user-attachments/files/17866786/logs_4.7.1-beta_241120014.txt)

Well here it is and it is happening to new audio and vids

**Comment by SREESANTH373737** [comment]
144p or audio mode only me

**Comment by MSOB7YY** [comment]
ur requests return 403 status code meaning they are blocked or unauthorized. have u tried to sign in? and do u have adblocker/dns/vpn etc enabled?

**Comment by MSOB7YY** [comment]
also try settings -> youtube -> flag icon at top right -> set client to ios

**Comment by SREESANTH373737** [comment]
> ur requests return 403 status code meaning they are blocked or unauthorized. have u tried to sign in? and do u have adblocker/dns/vpn etc enabled?

Nop no vpn no sign in

**Comment by SREESANTH373737** [comment]
> also try settings -> youtube -> flag icon at top right -> set client to ios
 Well it's done it's working now
 But why default is not working in client

**Comment by SREESANTH373737** [comment]
Bruh the log is full of 403 errors 😮‍💨

**Comment by MSOB7YY** [comment]
weird that web urls return 403 after requesting cuz there is this header request check to ensure that urls are functional. anyways ios client links are more fine
