### ISSUE TITLE
[ISSUE] Queue size

### ISSUE THREAD

**Issue by victorjon68** [namidaco/namida#404]
I have a music folder which has 2700 songs in total, so I click a song to play expecting all the songs in the folder to be added to the queue, but only 501 songs are added. I didn't realize at first so I was wondering how I have listened to 2700 songs in 4 days. Kindly make the queue size bigger to accomodate more songs.

**Comment by victorjon68** [comment]
I just realized the reason they did this, quote: "it shuffles them all and then take 1000 for performance
to bypass that, play 1 track, select all others and play last
open queue and long press shuffle button to shuffle all"
So, easiest way is just search the exact name of the first song you see and play it so that it is the only one in queue, then select the folder or playlist you want to play and 'play next'.

**Comment by victorjon68** [comment]
I just realized the reason they did this, quote: "it shuffles them all and then take 1000 for performance
to bypass that, play 1 track, select all others and play last
open queue and long press shuffle button to shuffle all"
So, easiest way is just search the exact name of the first song you see and play it so that it is the only one in queue, then select the folder or playlist you want to play and 'play next'.

**Comment by MSOB7YY** [comment]
oh sorry for being late this discussed multiple times before, #245 and https://github.com/namidaco/namida/issues/31#issuecomment-1770926250

> So, easiest way is just search the exact name of the first song you see and play it so that it is the only one in queue, then select the folder or playlist you want to play and 'play next'.

the easiest way is to go normally to the folder, open any track dialog, play it. and then the other steps to select all (or the select folder) and (play next/play last) and shuffle if needed

might think about increasing the limit a bit more but idk the queue u play is saved on each change both as "latest queue" and permanenly inside "queue" page so allowing more tracks means more storage and possible performance issues, while u won't even play all of them

**Comment by MSOB7YY** [comment]
so uh update to this, i allowed unlimited queue if u play using any button (except when pressing the track tile itself)
can be checked in v4.8.3 beta here https://github.com/namidaco/namida-snapshots/releases
