### ISSUE TITLE
[ISSUE] Won't play

### ISSUE THREAD

**Issue by myfavisgrey** [namidaco/namida#405]
I'm searching a song and it won't play but it's not on pause 

## Expected Behavior
 To play 

## Screenshots

https://github.com/user-attachments/assets/aed7f483-53b3-45bb-b83a-9845f1fa702a

**Comment by MSOB7YY** [comment]
trying playing smth else and coming back to it? tried clearing cache (using steps https://github.com/namidaco/namida/issues/403#issuecomment-2492107408)? and which version u on ?

**Comment by MSOB7YY** [comment]
should be fixed in v4.8.3 https://github.com/namidaco/namida-snapshots/releases
