### ISSUE TITLE
System font by default

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#41]
Please add option to use system font as default font in Namida I'm using rosemary it's not apply in namida

**Comment by MSOB7YY** [comment]
Unfortunately, this is currently not possible in flutter v3.13, refer to https://github.com/flutter/flutter/issues/48381 for more info

closing as not intended for now

**Comment by DwainZwerg** [comment]
@MSOB7YY There is a plugin: https://github.com/re7gog/android_system_font

**Comment by MSOB7YY** [comment]
@DwainZwerg it doesn't work
