### ISSUE TITLE
[FEATURE REQUEST] Feature to sync local playlists and Spotify playlists or option to add local songs to Spotify playlist.

### ISSUE THREAD

**Issue by amanyadav-s** [namidaco/namida#411]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Apps**
Add any other known apps/service that does this in a good way

**Comment by amanyadav-s** [comment]
> thats not possible. the only possible thing here is maybe fetching info/tracks of spotify playlists, and even if there was a way for syncing playlists, spotify tracks are drm protected so u cant even download them

Ya I just want the fetching feature using metadata of tracks and with the help of that I can manually add that to Spotify playlist.

**Comment by MSOB7YY** [comment]
this would be useless and spotify is already out of scope, sorry
