### ISSUE TITLE
[BUG] Media player notifications not working on Android 13

### ISSUE THREAD

**Issue by ZYGYU** [namidaco/namida#413]
Media player notifications won't able to pause resume and skipping music 

Device: **Realme C33**
OS: **Android 13**

## Expected Behavior

Media player notifications can run seamlessly on Android 13

## Current Behavior

When I want to pause music from the media player notification it doesn't work

## Steps to Reproduce

1.  Play Music
2. Open up notification 
3. Pausing music 
4. Damn the notification is not working

## Screenshots

https://github.com/user-attachments/assets/980aa31a-f41e-443b-bc5c-2dfa87772e90

## Logs

[logs_4.7.3-beta_241126215.txt](https://github.com/user-attachments/files/17963735/logs_4.7.3-beta_241126215.txt)

## Possible Solution

I don't know about coding 🤷🏿‍♂️

**Comment by ZYGYU** [comment]
it's working again, I don't know why

**Comment by MSOB7YY** [comment]
lmaooo glad its fixed cuz i got no idea, it might have been just the player having a stroke
