### ISSUE TITLE
Some songs just aren't playing

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#42]
First of all i like your app a lot, it's very unique. It ticks most of the boxes for me and I've enjoyed using it however this is a one major problem I'm facing

![Screenshot_2023-10-30-12-07-27-488_com msob7y namida](https://github.com/namidaco/namida/assets/99175083/22e0bfc7-477c-4b74-a6c7-55aea03c1106)

**The app showed "error playing track" in few songs**
 
![Screenshot_2023-10-30-12-07-29-790_com msob7y namida](https://github.com/namidaco/namida/assets/99175083/d14e8f69-66f0-4830-bec2-a2f361e2f1f5)

**So i tried updating it**

![Screenshot_2023-10-30-12-07-35-189_com msob7y namida](https://github.com/namidaco/namida/assets/99175083/275e3ce3-e16f-41ad-a7eb-d4fcb9bd398d)

**Even tho the file hasn't been deleted, moved or renamed outside of Namida (as you can see the new name is same as old one) it's still not working after confirming the option**

![Screenshot_2023-10-30-12-07-41-455_com msob7y namida](https://github.com/namidaco/namida/assets/99175083/d9d29ca3-99bf-4d97-ad5b-4d76f42ba13c)

I tried updating path directory and reindexing the artwork too but still no luck. I tried playing them in Poweramp, Musicolet and Metro and they're playing fine. I don't know what's happening exactly.

**Comment by MSOB7YY** [comment]
hmmmmm interesting, thanks for liking Namida tho

well the issue seems kinda weird, i would say `all_file_access` permission is needed it the track was in a root directory, but its not.

i can't predict any possible reason except that the file contains `#`, can you please send this track and share the logs from "About section"? 
also can u confirm other music is playing normally inside "`storage/emulated/0/Music`"? sorry for inconvenience

**Comment by NikunjKhangwal** [comment]
Turns out that was exactly the problem. Every file with # in title wasn't playing but they played normally after i renamed them.

**Comment by NikunjKhangwal** [comment]
Thanks for your efforts. While i'm at it, can i suggest a few other things as well here or should i open seperate issues for them? Sorry for the dumb question idk much about how github works.

**Comment by MSOB7YY** [comment]
ofc you can! I would love to hear more!
but its better to open a new issue since it will have different topic, ty
