### ISSUE TITLE
[FEATURE REQUEST] Option to replace close button to favorite button on the notification window

### ISSUE THREAD

**Issue by Ceynou** [namidaco/namida#421]
**Is your feature request related to a problem? Please describe.**
I would like to favorite a song without unlocking the phone if possible, so it has to be from the notification window of the app right?

Again, thank you for the app

**Comment by MSOB7YY** [comment]
thank you, u can enable this option to show fav button
![Screenshot_20241211-154313_Namida](https://github.com/user-attachments/assets/df888bce-794f-4293-b9c0-4d7927126e9c)

(we can't remove close button bcz notification is sticky(not dismissible) so that we dont get killed by android)

**Comment by Ceynou** [comment]
Oh I didn't know it was in Playback, I thought it would be in customization, my bad, thanks
