### ISSUE TITLE
[BUG] Downloaded MP4 files not showing up

### ISSUE THREAD

**Issue by YarielBaerga** [namidaco/namida#422]
I was downloading a few m4a's and MP4's but it only shows the M4A files and not the MP4 files. It shows in it's folder in zarchiver but not on the app.

## Expected Behavior
 That it would show in my downloaded folder and would be able to play it

## Steps to Reproduce

1. Download a MP4 from youtube
2. Refresh the download page
3. Only show M4A files

## Screenshots
 

![Screenshot_20241211_134138_ZArchiver](https://github.com/user-attachments/assets/a0318dc3-b2a0-4635-bd1f-d18283340c2d)

https://github.com/user-attachments/assets/8e5fa677-e6e0-4503-9ec4-fe0ef0309bd2

## Logs
 
[logs_3.8.5_240805177.txt](https://github.com/user-attachments/files/18100041/logs_3.8.5_240805177.txt)

**Comment by MSOB7YY** [comment]
ur on an old version. download latest from here https://github.com/namidaco/namida-snapshots/releases
