### ISSUE TITLE
[BUG] Leaving the player loaded in the background and then opening it(the player is already loaded) makes the actual paused track not to play

### ISSUE THREAD

**Issue by iWisp360** [namidaco/namida#425]
I started playing a song, then I left the player opened in the background (the notification center panel from the player is there). After some hours I opened the player again, (the player was already loaded in the background) and resuming the track results in the sound not playing, the play button changes from paused to playing but the wave indicator and the track playing itself isn't working (maybe a thread involved in the song playing is killed?)

## Expected Behavior
You can pause the track and continue playing it anytime.

## Steps to Reproduce

1. Open the player
2. Start playing a song
3. Pause it at any time
4. Leave the player in the background (you should see a notification from the player)
5. After an hour or more doing random things like browsing the internet or playing a game open the player again from the notification and play it

## Logs
[logs_4.8.1-beta_241208024.txt](https://github.com/user-attachments/files/18129020/logs_4.8.1-beta_241208024.txt)

**Comment by iWisp360** [comment]
https://github.com/user-attachments/assets/f10c2cd5-09a6-4a34-bdb7-f1e6f81a5a13

**Comment by MSOB7YY** [comment]
this seems similar to #184

i realized what caused the issue and fixed here https://github.com/MSOB7YY/just_audio/commit/41a49732cb9ef3f05b14e437a3f6cde930ad0a3b, pls wait the [new beta here](https://github.com/namidaco/namida-snapshots/releases) (v4.8.3+) in few days or less

**Comment by MSOB7YY** [comment]
the beta is out btw https://github.com/namidaco/namida-snapshots/releases
