### ISSUE TITLE
[BUG] Multiple Synced Lyrics Display Incorrectly and Cause Unexpected Scrolling

### ISSUE THREAD

**Issue by deusvagus** [namidaco/namida#429]
When multiple lines of synced lyrics share the same timestamp, only the last line is displayed, and the earlier lines are not shown. Additionally, the screen scrolls more than necessary, moving past the intended line for that timestamp.

## Expected Behavior

When multiple lines of synced lyrics share the same timestamp, all lines should be displayed simultaneously without affecting scrolling behavior.

## Current Behavior

Only the last line of lyrics with the same timestamp is displayed, while the earlier lines are omitted.

The screen scrolls excessively, going past the intended line that should be displayed for the corresponding timestamp.

## Steps to Reproduce

1. Add synced lyrics to a song.

2. Set multiple lines of lyrics to have the same timestamp.

3. Play the song and enable the lyrics display feature.

## Possible Solution

Update the lyrics rendering logic to ensure all lines with the same timestamp are displayed simultaneously.

Suggestion: Add More Settings for Lyrics

I recommend adding options to customize lyrics tags (e.g., LYRICS, UNSYNCEDLYRICS) and basic display settings to enhance user control and flexibility.

**Comment by MSOB7YY** [comment]
download 4.8.2 lmao https://github.com/namidaco/namida-snapshots/releases/

**Comment by MSOB7YY** [comment]
and thank u for the detailed issue!
