### ISSUE TITLE
[SUGGESTIONS] Some qol suggestions/features

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#43]
**I know this app is still new and needs time to mature. I understand if these doesn't get implemented anytime soon or never**

- [ ] A thicker Scroll Bar
- [x] Recently added sorting option aside from recently modified
- [x] Having seperate sorting option for both searched content and tracks. I usually like to view all of my tracks in alphabetical order and searched content in recently added
- [ ] Accidently pressing the tracks button on navigation bar doesn't reset the list/doesn't scroll to the top (An option to disable this behaviour)
- [x] Having a search option in Settings to find things easily, specially with how customizable the app is and has more to come

**Comment by MSOB7YY** [comment]
thanks for these awesome suggestions, some will get implemented soon and others idk yet, u can keep track of progress or further notices

**Comment by NikunjKhangwal** [comment]
I see, thanks i must've missed recently added and yeah i understand remaking the whole settings page could take time. Keep up the good work.

**Comment by MSOB7YY** [comment]
okay update: settings search is implemented in 204d4da745ebc720b03431093e42f3805649b04d ... idk how

**Comment by NikunjKhangwal** [comment]
A welcome change, thanks

**Comment by MSOB7YY** [comment]
update: separate sorting for search tracks is now available in 17bcf73f8f8edf084acc4636dd4366fd9a838a18

**Comment by MSOB7YY** [comment]
soo i been leaving this in case i changed my mind but i really not want to
1. thicker scroll bar:
   - no the design gonna be ass + thats already how it behaves on ios. on android usually u dont even have smth to hold, the hit test is fairly accessible in my opinion and balanced since there are other ui parts near it (ex: track menu)
2. option to disable scrolling to top:
   - not necessary at all honestly, just dont press down there. i understand that it would be still nice to include but settings are already bloated, sorry for that

**Comment by MSOB7YY** [comment]
if i had the chance to tweak scrollbar in a better way, i will dw

**Comment by NikunjKhangwal** [comment]
Reset list was low priority so I'm good with that. I always struggle with scroll bar but guess I'll manage for now.

**Comment by NikunjKhangwal** [comment]
Also leaving this idea of scrollbar here which i think might good in Namida too
![IMG_20240412_084206](https://github.com/namidaco/namida/assets/99175083/c7c3f7e3-3394-4f3d-92a6-c4245ca73ea7)

Mockup:-
![IMG_20240412_085953](https://github.com/namidaco/namida/assets/99175083/6c60c0c7-4ced-484b-b3f5-22a0f1461eff)

**Comment by MSOB7YY** [comment]
@NikunjKhangwal alr it will sure be in mind for now, just so u know u should hold slightly on left, like this 
![Screenshot_20240412-140654_Namida](https://github.com/namidaco/namida/assets/85245079/1a92dc94-d2f3-4e8a-b146-7a9a543f5ee0)
