### ISSUE TITLE
[QUESTION] Track Thumbnail Size

### ISSUE THREAD

**Issue by turkey76** [namidaco/namida#430]
I just downloaded the app. It's great. The question i have is I have a Galaxy Z Fold 5 and I want to know if the track thumbnail size can be fitted for the screen to where its not covering the track title and favorite button. I've tried to do it in the settings but it's not working. Can you provide any guidance on resizing? I've attached a picture of the issue. 

Thank you for any help 
![Screenshot_20241219_195243](https://github.com/user-attachments/assets/f637c6b7-f50e-490c-bbba-925efa504ff5)

**Comment by MSOB7YY** [comment]
1. seems like u on old version, on new versions it should look like this #428
   - latest beta version https://github.com/namidaco/namida-snapshots/releases
2. there is no proper foldable/landscape support yet, requested at #202 & #142
3. if u want to resize the artwork, go to customization settings -> miniplayer -> artwork gestures -> scale multiplier -> enable. then u can resize artwork manually (turn it off again if u no longer need it)
