### ISSUE TITLE
[FEATURE REQUEST] add lastfm scrabble support

### ISSUE THREAD

**Issue by rajarshikhatua100** [namidaco/namida#431]
**Describe the solution you'd like**
spottube app's implementation https://github.com/KRTirtho/spotube

**Describe alternatives 
https://github.com/KRTirtho/spotube

**Additional context**
could not scrabble music with last FM without downloading additional apps

**Apps**
https://github.com/KRTirtho/spotube

**Comment by MSOB7YY** [comment]
no. it might be simple but i dont currently plan to.
use https://github.com/kawaiiDango/pano-scrobbler
this app can scrobble from any app that posts media notification and has other many features

**Comment by MSOB7YY** [comment]
it wont be really nice. an app to scrobble from anywhere is better than scrobbler in each app.
there is a lot to worry about as it won't just post scrobbles to lastfm, but a lot more to do

**Comment by MSOB7YY** [comment]
scrobbling is a way to save listens from multiple sources and get charts stats etc, and not as history.
in namida u should be using history & most played playlist for that, lastfm scrobbles are totally separate even if we implemented it
