### ISSUE TITLE
[ISSUE] Notification buttons not working :(

### ISSUE THREAD

**Issue by zeraevis** [namidaco/namida#437]
The play/pause, next/previous, favourite, and the "x" buttons on the notification player are NOT working.
## Expected Behavior

The audio should pause/play, skip, or rewind when the respective buttons are pressed, but nothing happens...
## Possible Solution

It's probably a small issue that can easily be fixed so please do..thank you :)

**Comment by Antiwh0re** [comment]
Checked it out just now, buttons work both on lock screen and in notifications area. Version 4.7.1. So it's specific to your system - pull the log out of the app and attach it here so that developer could locate the reason.

**Comment by zeraevis** [comment]
The issue seems to be solved. Both the notification and lock screen buttons are working now! Thank you.

**Comment by zeraevis** [comment]
The issue has been solved. Both the notification area and the lock screen buttons are working now! Thank you!

**Comment by MSOB7YY** [comment]
lmao glad it worked magically
