### ISSUE TITLE
Screen not appearing

### ISSUE THREAD

**Issue by Muckmmmmm** [namidaco/namida#45]
While importing youtube history it the other screen did not show up i was useing a Android A5

**Comment by MSOB7YY** [comment]
what should i understand from this 💀 what screen? and how it wasn't showing? do you have a screenshot?

**Comment by Muckmmmmm** [comment]
When importing the youtube watch history it says to select the .jason file on the next screen the next screen did not appear when i did the same on .fm the next screen appeared im not sure what to call this next screen

**Comment by Muckmmmmm** [comment]
Sorry if im just really stupid and dont understand

**Comment by MSOB7YY** [comment]
aha, its basically a file provider, it's a native android package that allows us "apps" to pick files

the file provider can take some to load especially the first time, it's tightly bounded to your device specs/rom, not an issue with Namida or any other app

anyways, you are now able to choose and import right?

and no you are not, its really a confusing screen to name 😅

**Comment by Muckmmmmm** [comment]
I see so after pressing conform i just wait a few minutes and it should open right? Thank you in advance

**Comment by MSOB7YY** [comment]
normally it shouldnt take more than 20-30 seconds for a first launch, if its taking too long, try restarting ur phone.

closing since its not a Namida issue
