### ISSUE TITLE
[SUGGESTION] A Floating Search Button

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#47]
A Floating search button would be great for ease of use. The place directly over mini player is perfect for thumb placement.
A few other ideas i have:-
An option to make it disappear temporarily while scrolling up.
It should follow the same color as song artwork just like mini player does.
It should work in every list like albums, artists and youtube.

![IMG_20231102_145444](https://github.com/namidaco/namida/assets/99175083/000da580-0def-4ec3-b2aa-f574ee83b4bf)

**Comment by MSOB7YY** [comment]
hellow, this sounds like a great idea, but it will kind of break the design 

currently you can include search button in bottom navigation bar, which seems very good option for me
![Screenshot_20231102-123753_Namida](https://github.com/namidaco/namida/assets/85245079/caed081e-9cfd-4b85-8dff-c8dc2ab02442)

- to tweak library tabs, go to settings > extra > library tabs, then add/reorder/remove
- let me know if this is a good solution, i don't think i can add a floating button

**Comment by NikunjKhangwal** [comment]
I feel like navigation bar gets a bit cluttered, it already has a lot of buttons. It's a matter of personal preference, i thought a floating button would be easier to use. But search in navigation bar is also usable for now. 👍

**Comment by Shivamhobbyist** [comment]
> A Floating search button would be great for ease of use. The place directly over mini player is perfect for thumb placement.
> A few other ideas i have:-
> An option to make it disappear temporarily while scrolling up.
> It should follow the same color as song artwork just like mini player does.
> It should work in every list like albums, artists and youtube.
> 
> ![IMG_20231102_145444](https://github.com/namidaco/namida/assets/99175083/000da580-0def-4ec3-b2aa-f574ee83b4bf)
> 

Not search button place suffle button

**Comment by MSOB7YY** [comment]
okay this was implemented in 302bfd6029b16101844f01b84b920d8215bff2ad & 0031d46df4df2dc119bc0ab98e0a8bf92c03bed7

- optioned to `none`, `shuffle` or `search` (other ideas are welcomed)
- it hides when scrolling up in tracks page only
- it always shows while search box is shown (to clear and close search)
- it supports local tracks only now (i still didnt trace youtube pages, its quite pain)
- it follows the current color scheme ofc

thanks for the suggestion 🌺

**Comment by NikunjKhangwal** [comment]
Holy! You're the 🐐 for implementing niche stuffs that weren't initially planned so quickly.

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 
mughhaghhagha what can i say 🤷.. i got some cute users i cant say no 😺

thank you again 💖
