### ISSUE TITLE
[SUGGESTION] Update Notification

### ISSUE THREAD

**Issue by FoxInSmoke** [namidaco/namida#51]
I suggest notifying application users about the release of an update in the application itself, and not through other sources

**Comment by MSOB7YY** [comment]
thanks for the suggestion, not really priority since it will require additional setup, but will see soon, thanks!

**Comment by MSOB7YY** [comment]
after a second thought, i dont think i will implement this.
the setup required is a hassle and not functional imo, why?
- if the update is checked inside app:
  - we'll need to keep track of the current release, and constantly check on every app launch, if found then fetch the proper variant for the device, and grab the link, download... downloading will be rate limited/throttled too on github.
  - each part is just a big hassle
- if the update is checked on background:
  - we'll need to keep a thread running just to check for updates when available, or use an online service (like firebase) to send messages that invokes the check, then add the previous point, not something i consider at all.
  
  
## Please use [Obtanium](https://github.com/ImranR98/Obtainium), a cute app for managing app updates hosted on different sources.
#### Obtanium does all of the above perfectly, and works for all repos/apps, i find it a better solution.
