### ISSUE TITLE
[FEATURE REQUEST] Dismissible YouTube miniplayer

### ISSUE THREAD

**Issue by FoxInSmoke** [namidaco/namida#52]
The YouTube miniplayer closes only when opening a local file or when exiting the application, while the local music player can be closed by swiping down...

![Screenshot_2023-11-07-21-08-42-263-edit_com.msob7y.namida.jpg](https://github.com/namidaco/namida/assets/121617579/85253e96-51df-40b1-8eda-2453d080487e)

**Comment by MSOB7YY** [comment]
Currently dismissing works only for local miniplayer, it was just recently implemented.
Dismissible YouTube miniplayer is on the way soon.

**Comment by MSOB7YY** [comment]
this now is implemented in a3a5d310b333aa1c6dbee0cbc7634e257ccd7f5c, thanks
