### ISSUE TITLE
Add search in settings 

### ISSUE THREAD

**Issue by VerySweetBread** [namidaco/namida#54]

**Comment by NikunjKhangwal** [comment]
I already suggested this before in #43

**Comment by MSOB7YY** [comment]
@NikunjKhangwal thanks for finding the issue lmao,
leaving it open as a separate issue 

for reference, settings search will require complete refactor and might not come any soon

**Comment by NikunjKhangwal** [comment]
Yup, you mentioned this before. It's understandable.

**Comment by MSOB7YY** [comment]
okay for some reasons, this now is implemented in 204d4da745ebc720b03431093e42f3805649b04d
dont ask me how or why, it is what it is

**Comment by MSOB7YY** [comment]
okay for some reasons, this now is implemented in 204d4da745ebc720b03431093e42f3805649b04d
dont ask me how or why, it is what it is

**Comment by VerySweetBread** [comment]
> okay for some reasons, this now is implemented in [204d4da](https://github.com/namidaco/namida/commit/204d4da745ebc720b03431093e42f3805649b04d) dont ask me how or why, it is what it is

How _and_ why?

**Comment by MSOB7YY** [comment]
💀 dont ask me how and why..
