### ISSUE TITLE
Enhancement: home screen smooth scrolling 

### ISSUE THREAD

**Issue by fedikhatib** [namidaco/namida#56]
Hi , I have around 70 track and I noticed that when scrolling in the home screen it feels lagging and not smooth

**Comment by MSOB7YY** [comment]
just to make sure, by home screen u mean the one having (mixes, recent listens, top recents, lost memories.. etc), right? if thats the case then can you please provide a video showcasing it

it works smooth on my machine

u can also try enabling "performance mode" from advanced and see
