### ISSUE TITLE
[Feature Request] ReplayGain tag support

### ISSUE THREAD

**Issue by thezeroalpha** [namidaco/namida#57]
[ReplayGain tags](https://en.wikipedia.org/wiki/ReplayGain) store info that allows media players to normalize the perceived loudness of audio across files. The media player can read that tag, and amplify or attenuate a given track based on the value. This is nice because you can set your volume to a certain level, and all tracks will play at around that level. ReplayGain values can either be per-track (so each track plays at a certain volume), or per-album (so the whole album plays at a certain level, with tracks in the album at dfferent levels). It would be great if Namida supported this.

(As a follow up, since this would mean implementing gain/attenuation functionality, that could also be exposed to the user as a setting, so they can boost the volume of playback if needed.)

**Comment by MSOB7YY** [comment]
that's interesting, this might require internal setup for the audio library, gonna check it out.
can you provide some 1-2 files that has the `replayGain` tag? also is it only an ID3v2 tag?

**Comment by thezeroalpha** [comment]
Sure, I'm [attaching two royalty-free tracks that have both track and album replaygain values](https://github.com/namidaco/namida/files/13326321/replaygain.zip), calculated with [mp3gain](https://mp3gain.sourceforge.net/).

There's a few options, the newest format uses only ID3v2 frames, and there's two legacy formats -- [here's the spec](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification). The spec also supports Vorbis comments and APEv2. But either way I don't think it's something that would be supported by Media Store, I found a [similar discussion in the Auxio repo](https://github.com/OxygenCobalt/Auxio/issues/7).

**Comment by MSOB7YY** [comment]
thanks so much for the detailed eport, i will look into this after finishing some stuff with YouTube and local video playback, so it might take some time, thanks again 🌺

**Comment by thezeroalpha** [comment]
Of course, thanks for your work and openness to feedback! (I'm also the dude from reddit)

**Comment by MSOB7YY** [comment]
oh coolio! nice to see you here lmao, thank u for ur recommendations and patience too!

**Comment by MSOB7YY** [comment]
hey its been a while
quick update, [the recent changes to audio tagger](https://github.com/namidaco/namida/blob/0222ad46cf4184716a08d3d09784f9c8b617e18a/android/app/src/main/kotlin/com/example/namida/FAudioTagger.kt#L278-L293) allowed extracting raw TXXX data, which made it so easier to implement replay gain
here is the info extracted for "titatnium" track in the sample u sent
```json
{
  "replaygain_album_gain": "-0.040000 dB",
  "replaygain_album_peak": "0.449919",
  "replaygain_track_gain": "-0.515000 dB",
  "replaygain_track_peak": "0.449919",
  "replaygain_reference_loudness": "89.0 dB",
  "MP3GAIN_ALBUM_MINMAX": "061,205",
  "MP3GAIN_MINMAX": "061,205",
  "MP3GAIN_UNDO": "+005,+005,N",
  "bitRate": 256,
  "sampleRate": 48000,
  "channels": "Joint Stereo",
  "encodingType": "MPEG-1 Layer 3"
}
```
there are info like `MP3GAIN_ALBUM_MINMAX`, `MP3GAIN_MINMAX`, `MP3GAIN_UNDO` which i dont understand, i think it has no use but if u know smth about them let me know

i will now start working on this, sorry for being late and thanks for requesting.

**Comment by MSOB7YY** [comment]
woaah forgot to mention THIS was done long ago. it's implemented for local library currently and im still working on yt side replay gain

u can try latest beta from here https://github.com/namidaco/namida-snapshots/releases
