### ISSUE TITLE
Library not fully indexed

### ISSUE THREAD

**Issue by Joeeeeb5** [namidaco/namida#58]
It gets stuck at 62% 312 tracks. Using media store fixes it but I want to use the YouTube integration, which I also couldn't get working

**Comment by Joeeeeb5** [comment]
Fixed it by restarting my phone, still can't get youtube videos playing along with local tracks, though![Screenshot_2023-11-11-21-15-03-336_com.msob7y.namida.jpg](https://github.com/namidaco/namida/assets/125207782/a9aa1cbc-d386-44de-9db0-338d39164fbe)

**Comment by Joeeeeb5** [comment]
WORKSSSS!!!!

**Comment by MSOB7YY** [comment]
glad its working now.
for more info how videos are linked, refer to https://github.com/namidaco/namida#video-integration
