### ISSUE TITLE
Feature request: automatically look for youtube videos when playing local songs

### ISSUE THREAD

**Issue by Joeeeeb5** [namidaco/namida#59]

**Comment by MSOB7YY** [comment]
that's exactly what is already happening, if YouTube link is found either in `comment` tag or in `filename`, it is fetched and played, read more in [#video-integration](https://github.com/namidaco/namida#video-integration)

reopen if thats not what u mean

**Comment by Joeeeeb5** [comment]
When pressing video (the menu I had opened in my previous issue), it should show results from youtube containing the artist and song name in its title, after selecting the video it'll automatically be associated with that audio file

**Comment by MSOB7YY** [comment]
in that case, it won't be automatic, u have to manually select the video u want
one way to achieve this is to
1. open "set yt link" dialog (screenshot) 
![Screenshot_20231111-214115_Namida](https://github.com/namidaco/namida/assets/85245079/56dae704-a609-41fd-a606-e5ce086255bb)
2. press "search"
3. this will open a dialog and automatically do a search using the track title & artist, u can there edit search text if u want and then select the video
4. this will put the link in the text field, now do save
5. done
