### ISSUE TITLE
Feature Request - .lrc file support

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#6]
The .lrc file is a file that allows for importing lyrics and their timestamps in the format [minute.second.centisecond]lyric. An example would be [0:32.48]No more holding back. Would go extremely well with a timed lyrics page, like Spotify.

**Comment by MSOB7YY** [comment]
thanks, this has actually been planned long ago, currently lyrics are fetched and saved as txt files, lrc support should include:
1. support for parsing lrc
2. reading from same directory or from lyrics tag
3. ui screen with timed animations

- i will try to focus on this sooner

**Comment by MSOB7YY** [comment]
🎉 closed as completed in 5b53f979bb9131185d776760f1fcb81eb40c8795
