### ISSUE TITLE
[Feature Request] Being able to reorder the songs in the Playlist

### ISSUE THREAD

**Issue by Heus-Sueh** [namidaco/namida#65]
As the title suggests, it would be cool and necessary to be able to reorder the songs in the playlist

**Comment by MSOB7YY** [comment]
this already is possible by clicking the "lock" icon in appbar
this will enable reordering & dismissing (removing)
![Screenshot_20231118-183112_Namida](https://github.com/namidaco/namida/assets/85245079/4733e8d2-ef5d-4a9b-b9f1-4b01c712b81f)

**Comment by Heus-Sueh** [comment]
> this already is possible by clicking the "lock" icon in appbar this will enable reordering & dismissing (removing) ![Screenshot_20231118-183112_Namida](https://user-images.githubusercontent.com/85245079/284010612-4733e8d2-ef5d-4a9b-b9f1-4b01c712b81f.png)

Oh, now I understand, wouldn't there be a better way to present this function or explain to the user what each button does when starting the app for the first time?

**Comment by MSOB7YY** [comment]
i didnt find any better way than a toggling button, this isn't a queue where u may reorder frequently, playlists should be protected from accidental reorders imo, if u have any better concept then sure!

about explaining while opening ui, no. this will need unmeasurable effort and just not worth it, people will skip it anyway, and people who want to actually learn, will do by exploring the app
that being said, i frequently publish some tips from time to time on telegram channel and/or discord

and ofc u are free anytime to ask about smth!
