### ISSUE TITLE
SD card audio not indexing 

### ISSUE THREAD

**Issue by AdityaMishra135** [namidaco/namida#67]
![Screenshot_20231124-202945_Namida](https://github.com/namidaco/namida/assets/94228705/ea53227d-02ac-4787-8c3f-b5d918f43798)

**Comment by MSOB7YY** [comment]
please provide logs
settings > about > share logs

also there might be an issue with ur sd card, try removing it and inserting again and/or restart ur phone

**Comment by MSOB7YY** [comment]
another thing here u may have forgot to add the music folder on ur sd card, by default "Music" folder is added automatically, so u should add any others if u have them somewhere else

**Comment by MSOB7YY** [comment]
hmmm it seems like scanning is not even started yet, again i can't guess much without logs

currently u can use Media Store as a temporarily solution

**Comment by MSOB7YY** [comment]
after v2.0.6, this should be gone
