### ISSUE TITLE
Bug Reports

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#70]
- [x] 1. There was a bug where instead of showing synced lyrics normally the app was showing lyrics in plain format with their timestamps before lines. Also they become left aligned instead of center. Refreshing the library fixed it. Sorry, i forgot to take the screenshot of this.

- [x] 2. Backups aren't being created in my specified folder. They're still going to Internal Storage/Namida/Backups

- [x] 3. Not sure if this is on purpose but "Use Collapsed Setting Tiles" option exist in both the main Settings page and under Extras

- [x] ~4. The app doesn't show Disc Number for songs even after re-indexing. (Musicolet screenshot on right for reference)
![photo_2_2023-11-28_19-47-09](https://github.com/namidaco/namida/assets/99175083/e6c869ab-7f6a-4f50-9594-aae74b836bf2)~

- [x] ~5. Searching a song by artist name doesn't show the results
![photo_3_2023-11-28_19-47-09](https://github.com/namidaco/namida/assets/99175083/b8605a57-6f3e-4c66-80ad-13b55c5877c9)~

**Comment by NikunjKhangwal** [comment]
Just wanted to mention the screenshot i attached isn't showing youtube link in comment either, this was before i re-indexed my library. This is not a bug, only disc number is.

**Comment by NikunjKhangwal** [comment]
1. Yes the song did had embedded lyrics. The lrc file was working fine before, it kinda happened for once.
4. Strange since Musicolet was showing it. I guess I'll test other tracks and then give update about it. I'm not using media store.
5. Dang it, my dumbass probably messed around with this setting at some point and forgot.
6. Not yet, I'll inform if i find one.

**Comment by NikunjKhangwal** [comment]
Yes, update it.

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 
can you please confirm the status of issue 4? (disc number issue)

also open a separate issue for number 6, as its a feature request not a bug

**Comment by NikunjKhangwal** [comment]
Nope. Musicolet still does. I'm sharing [these files](https://drive.google.com/drive/folders/1A3OjGeCueCa2maqWFXZkZRRg15l-hX-1) so you can further investigate.

**Comment by NikunjKhangwal** [comment]
Good to know it's not a problem with Namida itself. Yes, the fallback disc number should be unknown. Showing number creates confusion which happened in this case lol.
