### ISSUE TITLE
[QUESTION] how to stop track last position from being restored

### ISSUE THREAD

**Issue by Blabla22bla** [namidaco/namida#72]
There's an issue I'm having for this app, on some songs if I click on it, it plays at the exact part I left on, even if I clicked another song and went back to it, I don't know how to fix this.

**Comment by Blabla22bla** [comment]
And some songs are showing the incorrect lyrics, even though I have the correct ones attached to the lrc file

**Comment by MSOB7YY** [comment]
it's not a bug, i have answered u on telegram

u can control this behavior using this option in playback settings, make it above 5min
![Screenshot_20231205-015733_Namida](https://github.com/namidaco/namida/assets/85245079/7f511842-51d9-4e0b-9a24-f56fbd22b33e)
