### ISSUE TITLE
[Feature Suggestion] Reminder when there is no youtube link

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#83]
The "Open YouTube Link" button should show a toast message clarifying when there's no youtube link available for the song. That's it

**Comment by NikunjKhangwal** [comment]
Btw the new update is nice. After using it for some time now, the app is much easier to navigate around and I'm genuinely having a good time using it.

**Comment by MSOB7YY** [comment]
@idontveapc mugahaghhaha it's an incorrectly encoded track tags (non UTF-8 i guess) 
i keep it for tests

**Comment by NikunjKhangwal** [comment]
Ah! I see. I meant the first one. Either i didn't noticed the message or it got overriden by something else. Thanks for clarifying.

**Comment by NikunjKhangwal** [comment]
Ah! I see. I meant the first one. Either i didn't noticed the message or it got overriden by something else. Thanks for clarifying.
