### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by mrast26** [namidaco/namida#84]
After closing the app and reopening it, the app hangs and crashes. Force closing and deleting cache* doesnt do anything. I have to reinstall the app when this happens. I've locked the app so it always runs in background to prevent this from happening

Thank you Grammer police*

**Comment by MSOB7YY** [comment]
woah 2 weeks already sorry lmao
i remember asking u on telegram if you could access log file directory from file explorer, this should help, otherwise i cant do much
logs are in 
`0/Android/data/com.msob7y.namida/files/logs.txt`

there should be better crash reporting system I understand

**Comment by MSOB7YY** [comment]
delulu after v2.0.6
