### ISSUE TITLE
Full songs

### ISSUE THREAD

**Issue by Harleynother** [namidaco/namida#85]
I find that this app can't access all my 2k+ songs, only around 500 of them. My phone doesn't allow it gain access to my root storage but with other music apps, they automatically access my root storage. What could be the issue??

**Comment by MSOB7YY** [comment]
make sure to add all ur music folder in "Indexer Settings > List of Folders"

other music apps most prolly using Media Store, if adding folders manually didnt fix it, then enable Media Store from Indexer Settings
