### ISSUE TITLE
[FEATURE REQUEST] add accessible shuffle button.

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#88]
Add a shuffle button that is easily accessible because, currently, you need to go to the queue to find the shuffle button. Also, there is a small problem if I start listening to a song in the middle of a playlist, then use the shuffle button it only shuffles songs that are after the song's position in the playlist. It would be better if it also included the songs before. Like Spotify and YouTube music.

**Comment by MSOB7YY** [comment]
it actually already exists
settings > extras > floating action button
and choose "shuffle"

for the second part, u can also long press "shuffle" button and choose "shuffle all", this will shuffle the whole queue instead of the next tracks

**Comment by z9xx7o0** [comment]
There is still a little problem. See this video of me comparing Namida, Spotify, and YouTube music. Notice how when I shuffle in Namida, the current track goes to a random location in the queue. While in YouTube music and Spotify, it is always the first in the queue. Also, see the conveniently placed shuffle button. That is mandatory for any music player. https://github.com/namidaco/namida/assets/83415416/5865c183-a389-43e7-b539-8e25809fd345

**Comment by MSOB7YY** [comment]
oh i see then. shuffling all should definitely put the playing track at first.

as for shuffle button in the player ui, i dont think its really possible, the ui is pretty condensed, moving the duration text above and putting buttons instead will kinda feel cluttered (the bottom buttons are a replacement for this)
also the shuffling here is quite different, u just shuffle when u want to shuffle. enabling/disabling shuffling doesnt make sense to me, so putting it directly in the ui won't make sense

**Comment by z9xx7o0** [comment]
@MSOB7YY , I apologise for stretching this out it is a very small thing. If it's alright, I have a suggestion. You could add a small shuffle button next to the loop button or long press the loop to shuffle. ![Example.jpg](https://github.com/namidaco/namida/assets/83415416/ba56d799-7c6f-48ad-ab19-554cd06733b4)
Again, I'm sorry for wasting your time. If you don't want to add it, don't add it. After all, this isn't my project.

**Comment by MSOB7YY** [comment]
@z9xx7o0 ikr but the left button can contain some info which can cause overflow
wether video playback is enabled, or "audio info" is enabled in customization

and also as said shuffling mechanism doesnt suit the player ui, it has to be with the queue itself or idk thats how i think

nice editing skills tho :>
