### ISSUE TITLE
Feature Request - .mp3 support on downloaded YouTube videos.

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#9]
Currently, when you go to download a YouTube video, it only gives you the option of .m4a for audio. .m4as are higher quality, however I feel the option should be there in case someone wishes to keep their audio library in one uniform file format, or alternatively, if they are using Namida to download YouTube videos and playing through something else.

**Comment by MSOB7YY** [comment]
thanks for the suggestion, currently available formats on youtube are `m4a (acc)` & `webm (opus)`, mp3 is **not** available 

which means that to download mp3, u will download in any format available, then **convert** it, which will for sure losen audio original quality & will take time, im against conversion unless its really worth it

is it worth it? does mp3 have smth better than m4a? in fact m4a is more performant with seeking

let me know what u think

**Comment by Red6785** [comment]
I wrote this suggestion under the false assumption that you were using yt-dlp, which just has a native option to download as an .mp3. Sorry!

**Comment by MSOB7YY** [comment]
no worries, but just to let you know, yt-dlp doesnt download in mp3, it **converts** after downloading in whatever format
