### ISSUE TITLE
[FEATURE REQUEST] Sort tracks by most played

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#90]

**Comment by MSOB7YY** [comment]
i thought about this, but no. there is a dedicated most played screen which is more advanced than just sorting. i know sorting can be faster but most played screen is also fast

**Comment by z9xx7o0** [comment]
@MSOB7YY , thanks for the reply. I have some issues i hope you can fix. I gathered 4 issues in this video: https://github.com/namidaco/namida/assets/83415416/1b578461-baa6-48ee-80aa-a1576cd9bbcd

The first one is if the track is paused, I can't resume it from the notifications.

The second is when I download from YouTube, it stays in ongoing. It never goes to the finished section.

The third is more of a suggestion, but anyways in most players, when you press the "previous" button, it starts the current track from the beginning. You could maybe have an option in the setting to select if it goes back or replays.

The 4th is when the track stops playing because of an interruption it doesn't resume by itself after the interruption is gone even though I have the setting enabled (btw the first demonstration from YouTube music).

**Comment by MSOB7YY** [comment]
@z9xx7o0 woah these are lotta of good stuff, can u convert your comment to an issue please?
about widgets, maybe but not so near, requires lot of setup.
