### ISSUE TITLE
two songs play at once

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#94]
how to replicate:
- you'd play any preferable song.
- then from home (page) you'd play (recent one) "that" song again.
- then (either pause or keep playing "that" song) in "tracks" play any song.
  - both play together (from home and tracks).
  - you can't see the one from home but if you pause both pause.

**Comment by MSOB7YY** [comment]
this can no longer be replicated, mostly was fixed by https://github.com/namidaco/namida/commit/40fa46796b3daef69674d9b2e1f1893e328ed19c
the new logic will only rebuild the queue if u tried played the same item in another list/queue, without affecting the play process
