### ISSUE TITLE
[Bug Report] Files not downloading from Youtube

### ISSUE THREAD

**Issue by aandrew-me** [namidaco/namida#95]
First of all I would like to say, it's a very well crafted, well designed app with many features. So, great job and thank you for making it.
Back to the issue, I tried downloading an m4a file from youtube (tried downloading a video file too) but it just keeps loading and doesn't download. I gave the app all the necessary permissions. I provided a screenshot.
![Screenshot_20240106-150245_Namida](https://github.com/namidaco/namida/assets/66430340/fbca7488-674e-456f-8ad8-abc1df4bfec0)

Also I didn't find any option to delete songs, is there one?

**Comment by MSOB7YY** [comment]
no delete option for tracks yet, see #66

hmm u sure all_file_access is granted? 
![image](https://github.com/namidaco/namida/assets/85245079/a1d5bff0-69f9-400a-a373-01edb0f0d24c)
try checking it + deleting the download and trying again still doesnt solve it?

**Comment by aandrew-me** [comment]
I tried a couple of times yesterday but it failed. I just tried now and it worked! Strange, but it is what it is

**Comment by MSOB7YY** [comment]
it is what it is 💀 might be a network issue, anyways reopen if u noticed similar behavior again
