### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#96]
Plz fix if I click on YouTube tab then open yt home by default not playlists and when search from local tab then open local search and when search from yt tab then open yt search

And also fix 2 line in 1 line

![Screenshot_20240107_073842.png](https://github.com/namidaco/namida/assets/78287172/f4c99b6c-3000-49e8-9818-dddd0c9b1f0a)

**Comment by MSOB7YY** [comment]
in next release:
1. youtube section tab will be restored on startup
2. 2 lines issue is fixed

about search local/youtube tab, no, local should be always the default
