### ISSUE TITLE
[Feature Request] Reorder YouTube Playlists

### ISSUE THREAD

**Issue by Krackitty** [namidaco/namida#97]
One of my favorite things about YouTube playlists is that i can easily rearrange change the order of songs by dragging and drooping them into the desired spot, as I personally like having my playlists follow a certain order. So I wonder if you could make something similar to that for this app, either having it as a drag-and-drop feature like YouTube does, or a simple 'move up/down' option when selecting one or multiple tracks.
Thanks in advance

**Comment by MSOB7YY** [comment]
you mean reorder YouTube playlists right? local playlists can be reordered already tho, unlock reordering by clicking the "lock" icon on top right

will add the same for YouTube playlists soon
