### ISSUE TITLE
Indexing or refreshing problem

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#98]
Afer updating to latest version(1.9.2) when refresh getting multipal song with same name
I have only 116 and showing 500+ song because of thiss bug
![Screenshot_20240108_063609.png](https://github.com/namidaco/namida/assets/78287172/2e11360d-3cea-4dcd-9f8c-5a34a1cffd97)

**Comment by MSOB7YY** [comment]
yeah just fixed, prolly was a media store only issue, thanks for reporting
