### ISSUE TITLE
Swipe to refresh suggestion

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#99]
Don't add confirmation pop-up when refreshing using gesture

![Screenshot_20240108_075805.png](https://github.com/namidaco/namida/assets/78287172/a031ec89-fa0b-4780-8b4b-4553b71a6e1e)

and if u want to notify just notify like thiss

![Screenshot_20240108_080659_YouTube.png](https://github.com/namidaco/namida/assets/78287172/2dee7c25-0d83-4d6a-99e4-f2f85eb8378b)

**Comment by MSOB7YY** [comment]
its not just a confirmation, its a report indicating how many is going to be added and REMOVED
this is critical as to not suddenly remove tracks that werent found for some reason
